///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SmokeTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Cert recording.
    /// </summary>
    [TestModule("d55e470e-eec1-4552-b6e9-8ceef4940272", ModuleType.Recording, 1)]
    public partial class Cert : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::SmokeTest.Repositories.SmokeTestRepository repository.
        /// </summary>
        public static global::SmokeTest.Repositories.SmokeTestRepository repo = global::SmokeTest.Repositories.SmokeTestRepository.Instance;

        static Cert instance = new Cert();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Cert()
        {
            Downloads = "doc";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Cert Instance
        {
            get { return instance; }
        }

#region Variables

        string _Downloads;

        /// <summary>
        /// Gets or sets the value of variable Downloads.
        /// </summary>
        [TestVariable("83068832-3264-4206-b8a7-b401d2c21346")]
        public string Downloads
        {
            get { return _Downloads; }
            set { _Downloads = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
