///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace SmokeTest.Repositories
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Communications element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("63e883df-2179-478e-9275-1291cb869d56")]
    public partial class Communications : RepoGenBaseFolder
    {
        static Communications instance = new Communications();
        CommunicationsFolders.MainFormAppFolder _mainform;
        CommunicationsFolders.AmicusAttorneyXWinAppFolder _amicusattorneyxwin;
        CommunicationsFolders.PhoneDetailFormAppFolder _phonedetailform;
        CommunicationsFolders.FileSelectFormAppFolder _fileselectform;
        CommunicationsFolders.FindFilesFormAppFolder _findfilesform;
        CommunicationsFolders.PromptFormAppFolder _promptform;
        CommunicationsFolders.MessageDetailFormAppFolder _messagedetailform;
        CommunicationsFolders.PeopleSelectFormAppFolder _peopleselectform;
        CommunicationsFolders.NewEmailFormAppFolder _newemailform;
        CommunicationsFolders.ContextMenuAppFolder _contextmenu;

        /// <summary>
        /// Gets the singleton class instance representing the Communications element repository.
        /// </summary>
        [RepositoryFolder("63e883df-2179-478e-9275-1291cb869d56")]
        public static Communications Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Communications() 
            : base("Communications", "/", null, 0, false, "63e883df-2179-478e-9275-1291cb869d56", ".\\RepositoryImages\\Communications63e883df.rximgres")
        {
            _mainform = new CommunicationsFolders.MainFormAppFolder(this);
            _amicusattorneyxwin = new CommunicationsFolders.AmicusAttorneyXWinAppFolder(this);
            _phonedetailform = new CommunicationsFolders.PhoneDetailFormAppFolder(this);
            _fileselectform = new CommunicationsFolders.FileSelectFormAppFolder(this);
            _findfilesform = new CommunicationsFolders.FindFilesFormAppFolder(this);
            _promptform = new CommunicationsFolders.PromptFormAppFolder(this);
            _messagedetailform = new CommunicationsFolders.MessageDetailFormAppFolder(this);
            _peopleselectform = new CommunicationsFolders.PeopleSelectFormAppFolder(this);
            _newemailform = new CommunicationsFolders.NewEmailFormAppFolder(this);
            _contextmenu = new CommunicationsFolders.ContextMenuAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("63e883df-2179-478e-9275-1291cb869d56")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The MainForm folder.
        /// </summary>
        [RepositoryFolder("655498a9-3925-4370-84a4-49670f3581d2")]
        public virtual CommunicationsFolders.MainFormAppFolder MainForm
        {
            get { return _mainform; }
        }

        /// <summary>
        /// The AmicusAttorneyXWin folder.
        /// </summary>
        [RepositoryFolder("17aad7c7-c3f7-4710-ac59-a22fc05f32f2")]
        public virtual CommunicationsFolders.AmicusAttorneyXWinAppFolder AmicusAttorneyXWin
        {
            get { return _amicusattorneyxwin; }
        }

        /// <summary>
        /// The PhoneDetailForm folder.
        /// </summary>
        [RepositoryFolder("9d587d7a-f73e-468a-bc93-5f88a76bafba")]
        public virtual CommunicationsFolders.PhoneDetailFormAppFolder PhoneDetailForm
        {
            get { return _phonedetailform; }
        }

        /// <summary>
        /// The FileSelectForm folder.
        /// </summary>
        [RepositoryFolder("a78c6644-988b-4ce0-b2e9-c28a46ea5fb1")]
        public virtual CommunicationsFolders.FileSelectFormAppFolder FileSelectForm
        {
            get { return _fileselectform; }
        }

        /// <summary>
        /// The FindFilesForm folder.
        /// </summary>
        [RepositoryFolder("0e67f61b-234a-470f-abca-20b4a43840bc")]
        public virtual CommunicationsFolders.FindFilesFormAppFolder FindFilesForm
        {
            get { return _findfilesform; }
        }

        /// <summary>
        /// The PromptForm folder.
        /// </summary>
        [RepositoryFolder("bf0eb807-2d1f-47b3-b271-73e46b391100")]
        public virtual CommunicationsFolders.PromptFormAppFolder PromptForm
        {
            get { return _promptform; }
        }

        /// <summary>
        /// The MessageDetailForm folder.
        /// </summary>
        [RepositoryFolder("aca7f0c5-ba85-48e3-a0ac-12a3842f8ab4")]
        public virtual CommunicationsFolders.MessageDetailFormAppFolder MessageDetailForm
        {
            get { return _messagedetailform; }
        }

        /// <summary>
        /// The PeopleSelectForm folder.
        /// </summary>
        [RepositoryFolder("d45a8cb3-f807-4139-98be-7730fb5878eb")]
        public virtual CommunicationsFolders.PeopleSelectFormAppFolder PeopleSelectForm
        {
            get { return _peopleselectform; }
        }

        /// <summary>
        /// The NewEmailForm folder.
        /// </summary>
        [RepositoryFolder("439b703a-b5f2-43b4-b28b-7169db41d32c")]
        public virtual CommunicationsFolders.NewEmailFormAppFolder NewEmailForm
        {
            get { return _newemailform; }
        }

        /// <summary>
        /// The ContextMenu folder.
        /// </summary>
        [RepositoryFolder("5fe197e3-e329-4307-8602-ba1f0167b538")]
        public virtual CommunicationsFolders.ContextMenuAppFolder ContextMenu
        {
            get { return _contextmenu; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class CommunicationsFolders
    {
        /// <summary>
        /// The MainFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("655498a9-3925-4370-84a4-49670f3581d2")]
        public partial class MainFormAppFolder : RepoGenBaseFolder
        {
            CommunicationsFolders.EmailOnTopOfTheListFolder _emailontopofthelist;
            RepoItemInfo _btncommunicationsInfo;
            RepoItemInfo _btnnewmenuitemInfo;
            RepoItemInfo _listfirstfileInfo;
            RepoItemInfo _btnallfilesInfo;
            RepoItemInfo _btnshowallfilesInfo;
            RepoItemInfo _btncommunications1Info;
            RepoItemInfo _newitemdropdownInfo;
            RepoItemInfo _newemailInfo;
            RepoItemInfo _btnsyncnowInfo;
            RepoItemInfo _tblcommunicationsInfo;

            /// <summary>
            /// Creates a new MainForm  folder.
            /// </summary>
            public MainFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MainForm", "/form[@controlname='MainForm']", parentFolder, 30000, null, true, "655498a9-3925-4370-84a4-49670f3581d2", "")
            {
                _emailontopofthelist = new CommunicationsFolders.EmailOnTopOfTheListFolder(this);
                _btncommunicationsInfo = new RepoItemInfo(this, "btnCommunications", "?/?/tree[@accessiblerole='Outline']/button[@accessiblename='Communications']", 30000, null, "ae01bbe5-4309-4641-b67e-27fc5439cf85");
                _btnnewmenuitemInfo = new RepoItemInfo(this, "btnNewMenuItem", "?/?/form[@controlname='CommIndexForm']/container[@controlname='menubar_Fill_Panel']//toolbar[@accessiblename='Toolbar']/menuitem[@accessiblename='']", 30000, null, "897ca1c5-902b-4e0a-8506-7e8920a5dd78");
                _listfirstfileInfo = new RepoItemInfo(this, "listFirstFile", "?/?/form[@controlname='CommIndexForm']/container[@controlname='splitContainer']//row[@accessiblename='Band 0 row 1']/cell[@accessiblename='File']", 30000, null, "8c766cd0-ba5e-4950-8eb2-7e60ad516829");
                _btnallfilesInfo = new RepoItemInfo(this, "btnAllFiles", "container[@controlname='pLeft']//container[@controlname='CommIndexControlPanel']/container[@controlname='pnlBase']/container[@controlname='atcOutstandingOrToday']/container[@controlname='<Selected>k__BackingField']/?/?/text[@accessiblename='All']", 30000, null, "a9c9068b-720b-44aa-89ef-165764efa2c3");
                _btnshowallfilesInfo = new RepoItemInfo(this, "btnShowAllFiles", "container[@controlname='pLeft']//container[@controltypename='UltraExplorerBarContainerControl' and @instance='0']/?/?/container[@controlname='CommIndexControlPanel']/container[@controlname='pnlBase']/container[@controlname='atcOutstandingOrToday']//text[@accessiblename='All']", 30000, null, "8bcea222-82ed-4502-83c7-fa6f2cfedc4c");
                _btncommunications1Info = new RepoItemInfo(this, "btnCommunications1", "?/?/tree[@accessiblerole='Outline']/button[@accessiblename='Communications']", 5000, null, "b420c0de-1885-45f6-bc52-92f3da546437");
                _newitemdropdownInfo = new RepoItemInfo(this, "newItemDropDown", "?/?/form[@controlname='CommIndexForm']//?/menuitem[@name='New']", 30000, null, "f227d675-d472-41ed-bfc7-ef5a8c4385e4");
                _newemailInfo = new RepoItemInfo(this, "newEmail", ".//menuitem[@accessiblename='E-mail']", 30000, null, "20fd97b5-0fa6-4bfc-9498-7115d29544ab");
                _btnsyncnowInfo = new RepoItemInfo(this, "btnSyncNow", "?/?/form[@controlname='CommIndexForm']//?/button[@text='Synchronize now']", 30000, null, "53e376b3-fa0b-425a-9ac1-47febc8a641a");
                _tblcommunicationsInfo = new RepoItemInfo(this, "tblCommunications", "?/?/form[@controlname='CommIndexForm']/container[@controlname='splitContainer']//table[@accessiblename='Band 0']", 30000, null, "9f593331-1c6e-463a-91ec-a8c7956e014f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("655498a9-3925-4370-84a4-49670f3581d2")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("655498a9-3925-4370-84a4-49670f3581d2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btnCommunications item.
            /// </summary>
            [RepositoryItem("ae01bbe5-4309-4641-b67e-27fc5439cf85")]
            public virtual Ranorex.Button btnCommunications
            {
                get
                {
                    return _btncommunicationsInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnCommunications item info.
            /// </summary>
            [RepositoryItemInfo("ae01bbe5-4309-4641-b67e-27fc5439cf85")]
            public virtual RepoItemInfo btnCommunicationsInfo
            {
                get
                {
                    return _btncommunicationsInfo;
                }
            }

            /// <summary>
            /// The btnNewMenuItem item.
            /// </summary>
            [RepositoryItem("897ca1c5-902b-4e0a-8506-7e8920a5dd78")]
            public virtual Ranorex.MenuItem btnNewMenuItem
            {
                get
                {
                    return _btnnewmenuitemInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The btnNewMenuItem item info.
            /// </summary>
            [RepositoryItemInfo("897ca1c5-902b-4e0a-8506-7e8920a5dd78")]
            public virtual RepoItemInfo btnNewMenuItemInfo
            {
                get
                {
                    return _btnnewmenuitemInfo;
                }
            }

            /// <summary>
            /// The listFirstFile item.
            /// </summary>
            [RepositoryItem("8c766cd0-ba5e-4950-8eb2-7e60ad516829")]
            public virtual Ranorex.Cell listFirstFile
            {
                get
                {
                    return _listfirstfileInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The listFirstFile item info.
            /// </summary>
            [RepositoryItemInfo("8c766cd0-ba5e-4950-8eb2-7e60ad516829")]
            public virtual RepoItemInfo listFirstFileInfo
            {
                get
                {
                    return _listfirstfileInfo;
                }
            }

            /// <summary>
            /// The btnAllFiles item.
            /// </summary>
            [RepositoryItem("a9c9068b-720b-44aa-89ef-165764efa2c3")]
            public virtual Ranorex.Text btnAllFiles
            {
                get
                {
                    return _btnallfilesInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The btnAllFiles item info.
            /// </summary>
            [RepositoryItemInfo("a9c9068b-720b-44aa-89ef-165764efa2c3")]
            public virtual RepoItemInfo btnAllFilesInfo
            {
                get
                {
                    return _btnallfilesInfo;
                }
            }

            /// <summary>
            /// The btnShowAllFiles item.
            /// </summary>
            [RepositoryItem("8bcea222-82ed-4502-83c7-fa6f2cfedc4c")]
            public virtual Ranorex.Text btnShowAllFiles
            {
                get
                {
                    return _btnshowallfilesInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The btnShowAllFiles item info.
            /// </summary>
            [RepositoryItemInfo("8bcea222-82ed-4502-83c7-fa6f2cfedc4c")]
            public virtual RepoItemInfo btnShowAllFilesInfo
            {
                get
                {
                    return _btnshowallfilesInfo;
                }
            }

            /// <summary>
            /// The btnCommunications1 item.
            /// </summary>
            [RepositoryItem("b420c0de-1885-45f6-bc52-92f3da546437")]
            public virtual Ranorex.Button btnCommunications1
            {
                get
                {
                    return _btncommunications1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnCommunications1 item info.
            /// </summary>
            [RepositoryItemInfo("b420c0de-1885-45f6-bc52-92f3da546437")]
            public virtual RepoItemInfo btnCommunications1Info
            {
                get
                {
                    return _btncommunications1Info;
                }
            }

            /// <summary>
            /// The newItemDropDown item.
            /// </summary>
            [RepositoryItem("f227d675-d472-41ed-bfc7-ef5a8c4385e4")]
            public virtual Ranorex.MenuItem newItemDropDown
            {
                get
                {
                    return _newitemdropdownInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The newItemDropDown item info.
            /// </summary>
            [RepositoryItemInfo("f227d675-d472-41ed-bfc7-ef5a8c4385e4")]
            public virtual RepoItemInfo newItemDropDownInfo
            {
                get
                {
                    return _newitemdropdownInfo;
                }
            }

            /// <summary>
            /// The newEmail item.
            /// </summary>
            [RepositoryItem("20fd97b5-0fa6-4bfc-9498-7115d29544ab")]
            public virtual Ranorex.MenuItem newEmail
            {
                get
                {
                    return _newemailInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The newEmail item info.
            /// </summary>
            [RepositoryItemInfo("20fd97b5-0fa6-4bfc-9498-7115d29544ab")]
            public virtual RepoItemInfo newEmailInfo
            {
                get
                {
                    return _newemailInfo;
                }
            }

            /// <summary>
            /// The btnSyncNow item.
            /// </summary>
            [RepositoryItem("53e376b3-fa0b-425a-9ac1-47febc8a641a")]
            public virtual Ranorex.Button btnSyncNow
            {
                get
                {
                    return _btnsyncnowInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnSyncNow item info.
            /// </summary>
            [RepositoryItemInfo("53e376b3-fa0b-425a-9ac1-47febc8a641a")]
            public virtual RepoItemInfo btnSyncNowInfo
            {
                get
                {
                    return _btnsyncnowInfo;
                }
            }

            /// <summary>
            /// The tblCommunications item.
            /// </summary>
            [RepositoryItem("9f593331-1c6e-463a-91ec-a8c7956e014f")]
            public virtual Ranorex.Table tblCommunications
            {
                get
                {
                    return _tblcommunicationsInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The tblCommunications item info.
            /// </summary>
            [RepositoryItemInfo("9f593331-1c6e-463a-91ec-a8c7956e014f")]
            public virtual RepoItemInfo tblCommunicationsInfo
            {
                get
                {
                    return _tblcommunicationsInfo;
                }
            }

            /// <summary>
            /// The EmailOnTopOfTheList folder.
            /// </summary>
            [RepositoryFolder("24cfb1ef-af90-4e72-8b3c-0ba6502ab1ce")]
            public virtual CommunicationsFolders.EmailOnTopOfTheListFolder EmailOnTopOfTheList
            {
                get { return _emailontopofthelist; }
            }
        }

        /// <summary>
        /// The EmailOnTopOfTheListFolder folder.
        /// </summary>
        [RepositoryFolder("24cfb1ef-af90-4e72-8b3c-0ba6502ab1ce")]
        public partial class EmailOnTopOfTheListFolder : RepoGenBaseFolder
        {
            RepoItemInfo _subjectInfo;
            RepoItemInfo _dateInfo;
            RepoItemInfo _fromfieldInfo;

            /// <summary>
            /// Creates a new EmailOnTopOfTheList  folder.
            /// </summary>
            public EmailOnTopOfTheListFolder(RepoGenBaseFolder parentFolder) :
                    base("EmailOnTopOfTheList", "?/?/form[@controlname='CommIndexForm']//tree[@automationid='ColScrollRegion: 0, RowScrollRegion: 0']", parentFolder, 30000, null, false, "24cfb1ef-af90-4e72-8b3c-0ba6502ab1ce", "")
            {
                _subjectInfo = new RepoItemInfo(this, "subject", "treeitem[@automationid='0']/text[@automationid='15']/text[@automationid='[Editor] Edit Area']", 30000, null, "cd647659-c7e6-410e-af05-487053a381e6");
                _dateInfo = new RepoItemInfo(this, "date", "treeitem[@automationid='0']/text[@automationid='6']/text[@automationid='[Editor] Edit Area']", 30000, null, "40298b21-c842-4f6a-bdbc-b3a6fd6a3b12");
                _fromfieldInfo = new RepoItemInfo(this, "fromField", "treeitem[@automationid='0']/text[@automationid='8']/text[@automationid='[Editor] Edit Area']", 30000, null, "02b7684e-cea0-4c51-8cda-fda76c4dacc6");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("24cfb1ef-af90-4e72-8b3c-0ba6502ab1ce")]
            public virtual Ranorex.Tree Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Tree>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("24cfb1ef-af90-4e72-8b3c-0ba6502ab1ce")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The subject item.
            /// </summary>
            [RepositoryItem("cd647659-c7e6-410e-af05-487053a381e6")]
            public virtual Ranorex.Text subject
            {
                get
                {
                    return _subjectInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The subject item info.
            /// </summary>
            [RepositoryItemInfo("cd647659-c7e6-410e-af05-487053a381e6")]
            public virtual RepoItemInfo subjectInfo
            {
                get
                {
                    return _subjectInfo;
                }
            }

            /// <summary>
            /// The date item.
            /// </summary>
            [RepositoryItem("40298b21-c842-4f6a-bdbc-b3a6fd6a3b12")]
            public virtual Ranorex.Text date
            {
                get
                {
                    return _dateInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The date item info.
            /// </summary>
            [RepositoryItemInfo("40298b21-c842-4f6a-bdbc-b3a6fd6a3b12")]
            public virtual RepoItemInfo dateInfo
            {
                get
                {
                    return _dateInfo;
                }
            }

            /// <summary>
            /// The fromField item.
            /// </summary>
            [RepositoryItem("02b7684e-cea0-4c51-8cda-fda76c4dacc6")]
            public virtual Ranorex.Text fromField
            {
                get
                {
                    return _fromfieldInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The fromField item info.
            /// </summary>
            [RepositoryItemInfo("02b7684e-cea0-4c51-8cda-fda76c4dacc6")]
            public virtual RepoItemInfo fromFieldInfo
            {
                get
                {
                    return _fromfieldInfo;
                }
            }
        }

        /// <summary>
        /// The AmicusAttorneyXWinAppFolder folder.
        /// </summary>
        [RepositoryFolder("17aad7c7-c3f7-4710-ac59-a22fc05f32f2")]
        public partial class AmicusAttorneyXWinAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _menupopupInfo;

            /// <summary>
            /// Creates a new AmicusAttorneyXWin  folder.
            /// </summary>
            public AmicusAttorneyXWinAppFolder(RepoGenBaseFolder parentFolder) :
                    base("AmicusAttorneyXWin", "/form[@processname='AmicusAttorney.XWin' and @controltypename='DropDownForm']", parentFolder, 30000, null, true, "17aad7c7-c3f7-4710-ac59-a22fc05f32f2", "")
            {
                _menupopupInfo = new RepoItemInfo(this, "MenuPopup", "?/?/contextmenu[@accessiblerole='MenuPopup']", 30000, null, "4f621365-d0bd-48ba-add7-5395c076892b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("17aad7c7-c3f7-4710-ac59-a22fc05f32f2")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("17aad7c7-c3f7-4710-ac59-a22fc05f32f2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MenuPopup item.
            /// </summary>
            [RepositoryItem("4f621365-d0bd-48ba-add7-5395c076892b")]
            public virtual Ranorex.ContextMenu MenuPopup
            {
                get
                {
                    return _menupopupInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The MenuPopup item info.
            /// </summary>
            [RepositoryItemInfo("4f621365-d0bd-48ba-add7-5395c076892b")]
            public virtual RepoItemInfo MenuPopupInfo
            {
                get
                {
                    return _menupopupInfo;
                }
            }
        }

        /// <summary>
        /// The PhoneDetailFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("9d587d7a-f73e-468a-bc93-5f88a76bafba")]
        public partial class PhoneDetailFormAppFolder : RepoGenBaseFolder
        {
            CommunicationsFolders.MenubarFillPanelFolder _menubarfillpanel;

            /// <summary>
            /// Creates a new PhoneDetailForm  folder.
            /// </summary>
            public PhoneDetailFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("PhoneDetailForm", "/form[@controlname='PhoneDetailForm']", parentFolder, 30000, null, true, "9d587d7a-f73e-468a-bc93-5f88a76bafba", "")
            {
                _menubarfillpanel = new CommunicationsFolders.MenubarFillPanelFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9d587d7a-f73e-468a-bc93-5f88a76bafba")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9d587d7a-f73e-468a-bc93-5f88a76bafba")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MenubarFillPanel folder.
            /// </summary>
            [RepositoryFolder("185d02f6-45bc-47b5-94ea-b1a8119328d1")]
            public virtual CommunicationsFolders.MenubarFillPanelFolder MenubarFillPanel
            {
                get { return _menubarfillpanel; }
            }
        }

        /// <summary>
        /// The MenubarFillPanelFolder folder.
        /// </summary>
        [RepositoryFolder("185d02f6-45bc-47b5-94ea-b1a8119328d1")]
        public partial class MenubarFillPanelFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btnokInfo;
            RepoItemInfo _btnaddfileInfo;
            RepoItemInfo _txtphonecallnoteInfo;
            RepoItemInfo _btndeleteInfo;
            RepoItemInfo _rdodealtwithInfo;
            RepoItemInfo _rdooutstandingInfo;

            /// <summary>
            /// Creates a new MenubarFillPanel  folder.
            /// </summary>
            public MenubarFillPanelFolder(RepoGenBaseFolder parentFolder) :
                    base("MenubarFillPanel", "container[@controlname='menubar_Fill_Panel']", parentFolder, 30000, null, false, "185d02f6-45bc-47b5-94ea-b1a8119328d1", "")
            {
                _btnokInfo = new RepoItemInfo(this, "btnOK", ".//toolbar[@accessiblename='Toolbar']/button[@accessiblename='OK']", 30000, null, "7b267506-d26d-46dd-b250-d6e2d804a27e");
                _btnaddfileInfo = new RepoItemInfo(this, "btnAddFile", "container[@controlname='pnlBase']//container[@controlname='pnlFiles']//button[@accessiblerole='PushButton']", 30000, true, "77799e61-2567-481e-b629-07fbece8545d");
                _txtphonecallnoteInfo = new RepoItemInfo(this, "txtPhoneCallNote", "container[@controlname='pnlBase']//container[@controlname='pnlSummary']/?/?/text[@controltypename='EmbeddableTextBoxWithUIPermissions']/text[@accessiblerole='Text']", 30000, null, "d8934aa4-795b-4630-9a76-135dda99b373");
                _btndeleteInfo = new RepoItemInfo(this, "btnDelete", ".//toolbar[@accessiblename='Toolbar']/button[@accessiblename='Delete']", 30000, null, "0465641d-6a1d-4f8e-b1e7-ad5372e4279b");
                _rdodealtwithInfo = new RepoItemInfo(this, "rdoDealtWith", "container[@controlname='pnlBase']//container[@controlname='pnlStatus']/?/?/list[@accessiblename='Dealt with']/?/?/radiobutton[@accessiblename='Dealt with']", 30000, null, "848a57cb-4232-4139-aebf-829981816d8f");
                _rdooutstandingInfo = new RepoItemInfo(this, "rdoOutstanding", "container[@controlname='pnlBase']//container[@controlname='pnlStatus']/?/?/list[@accessiblename='Dealt with']/?/?/radiobutton[@accessiblename='Outstanding']", 30000, null, "d4bb7473-dcec-43b6-813f-241b3ba0166d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("185d02f6-45bc-47b5-94ea-b1a8119328d1")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("185d02f6-45bc-47b5-94ea-b1a8119328d1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btnOK item.
            /// </summary>
            [RepositoryItem("7b267506-d26d-46dd-b250-d6e2d804a27e")]
            public virtual Ranorex.Button btnOK
            {
                get
                {
                    return _btnokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnOK item info.
            /// </summary>
            [RepositoryItemInfo("7b267506-d26d-46dd-b250-d6e2d804a27e")]
            public virtual RepoItemInfo btnOKInfo
            {
                get
                {
                    return _btnokInfo;
                }
            }

            /// <summary>
            /// The btnAddFile item.
            /// </summary>
            [RepositoryItem("77799e61-2567-481e-b629-07fbece8545d")]
            public virtual Ranorex.Button btnAddFile
            {
                get
                {
                    return _btnaddfileInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnAddFile item info.
            /// </summary>
            [RepositoryItemInfo("77799e61-2567-481e-b629-07fbece8545d")]
            public virtual RepoItemInfo btnAddFileInfo
            {
                get
                {
                    return _btnaddfileInfo;
                }
            }

            /// <summary>
            /// The txtPhoneCallNote item.
            /// </summary>
            [RepositoryItem("d8934aa4-795b-4630-9a76-135dda99b373")]
            public virtual Ranorex.Text txtPhoneCallNote
            {
                get
                {
                    return _txtphonecallnoteInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txtPhoneCallNote item info.
            /// </summary>
            [RepositoryItemInfo("d8934aa4-795b-4630-9a76-135dda99b373")]
            public virtual RepoItemInfo txtPhoneCallNoteInfo
            {
                get
                {
                    return _txtphonecallnoteInfo;
                }
            }

            /// <summary>
            /// The btnDelete item.
            /// </summary>
            [RepositoryItem("0465641d-6a1d-4f8e-b1e7-ad5372e4279b")]
            public virtual Ranorex.Button btnDelete
            {
                get
                {
                    return _btndeleteInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnDelete item info.
            /// </summary>
            [RepositoryItemInfo("0465641d-6a1d-4f8e-b1e7-ad5372e4279b")]
            public virtual RepoItemInfo btnDeleteInfo
            {
                get
                {
                    return _btndeleteInfo;
                }
            }

            /// <summary>
            /// The rdoDealtWith item.
            /// </summary>
            [RepositoryItem("848a57cb-4232-4139-aebf-829981816d8f")]
            public virtual Ranorex.RadioButton rdoDealtWith
            {
                get
                {
                    return _rdodealtwithInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The rdoDealtWith item info.
            /// </summary>
            [RepositoryItemInfo("848a57cb-4232-4139-aebf-829981816d8f")]
            public virtual RepoItemInfo rdoDealtWithInfo
            {
                get
                {
                    return _rdodealtwithInfo;
                }
            }

            /// <summary>
            /// The rdoOutstanding item.
            /// </summary>
            [RepositoryItem("d4bb7473-dcec-43b6-813f-241b3ba0166d")]
            public virtual Ranorex.RadioButton rdoOutstanding
            {
                get
                {
                    return _rdooutstandingInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The rdoOutstanding item info.
            /// </summary>
            [RepositoryItemInfo("d4bb7473-dcec-43b6-813f-241b3ba0166d")]
            public virtual RepoItemInfo rdoOutstandingInfo
            {
                get
                {
                    return _rdooutstandingInfo;
                }
            }
        }

        /// <summary>
        /// The FileSelectFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("a78c6644-988b-4ce0-b2e9-c28a46ea5fb1")]
        public partial class FileSelectFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btnquickfindInfo;
            RepoItemInfo _listfirstfoundfileInfo;

            /// <summary>
            /// Creates a new FileSelectForm  folder.
            /// </summary>
            public FileSelectFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FileSelectForm", "/form[@controlname='FileSelectForm']", parentFolder, 30000, null, true, "a78c6644-988b-4ce0-b2e9-c28a46ea5fb1", "")
            {
                _btnquickfindInfo = new RepoItemInfo(this, "btnQuickFind", ".//toolbar[@accessiblename='Toolbar']/button[@accessiblename='QuickFind']", 30000, null, "e25ba604-e39a-4a6c-a706-488a9fd48687");
                _listfirstfoundfileInfo = new RepoItemInfo(this, "listFirstFoundFile", "container[@controlname='panel1']//row[@accessiblename='Band 0 row 1']/cell[@accessiblename='File']", 30000, null, "b94c3369-4a5a-4669-a270-77f33ae91d97");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a78c6644-988b-4ce0-b2e9-c28a46ea5fb1")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a78c6644-988b-4ce0-b2e9-c28a46ea5fb1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btnQuickFind item.
            /// </summary>
            [RepositoryItem("e25ba604-e39a-4a6c-a706-488a9fd48687")]
            public virtual Ranorex.Button btnQuickFind
            {
                get
                {
                    return _btnquickfindInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnQuickFind item info.
            /// </summary>
            [RepositoryItemInfo("e25ba604-e39a-4a6c-a706-488a9fd48687")]
            public virtual RepoItemInfo btnQuickFindInfo
            {
                get
                {
                    return _btnquickfindInfo;
                }
            }

            /// <summary>
            /// The listFirstFoundFile item.
            /// </summary>
            [RepositoryItem("b94c3369-4a5a-4669-a270-77f33ae91d97")]
            public virtual Ranorex.Cell listFirstFoundFile
            {
                get
                {
                    return _listfirstfoundfileInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The listFirstFoundFile item info.
            /// </summary>
            [RepositoryItemInfo("b94c3369-4a5a-4669-a270-77f33ae91d97")]
            public virtual RepoItemInfo listFirstFoundFileInfo
            {
                get
                {
                    return _listfirstfoundfileInfo;
                }
            }
        }

        /// <summary>
        /// The FindFilesFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("0e67f61b-234a-470f-abca-20b4a43840bc")]
        public partial class FindFilesFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _txtfindfileInfo;
            RepoItemInfo _btnokInfo;

            /// <summary>
            /// Creates a new FindFilesForm  folder.
            /// </summary>
            public FindFilesFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FindFilesForm", "/form[@controlname='FindFilesForm']", parentFolder, 30000, null, true, "0e67f61b-234a-470f-abca-20b4a43840bc", "")
            {
                _txtfindfileInfo = new RepoItemInfo(this, "txtFindFile", "container[@controlname='pnlBase']//text[@automationid='atxtSearch_EmbeddableTextBox']", 30000, null, "43686e97-97a4-4242-86f6-aae6887cec13");
                _btnokInfo = new RepoItemInfo(this, "btnOK", ".//toolbar[@accessiblename='Toolbar']/button[@accessiblename='OK']", 30000, null, "0c51ebc5-7ff3-41a3-b730-86c25a4d6ff5");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("0e67f61b-234a-470f-abca-20b4a43840bc")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("0e67f61b-234a-470f-abca-20b4a43840bc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The txtFindFile item.
            /// </summary>
            [RepositoryItem("43686e97-97a4-4242-86f6-aae6887cec13")]
            public virtual Ranorex.Text txtFindFile
            {
                get
                {
                    return _txtfindfileInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txtFindFile item info.
            /// </summary>
            [RepositoryItemInfo("43686e97-97a4-4242-86f6-aae6887cec13")]
            public virtual RepoItemInfo txtFindFileInfo
            {
                get
                {
                    return _txtfindfileInfo;
                }
            }

            /// <summary>
            /// The btnOK item.
            /// </summary>
            [RepositoryItem("0c51ebc5-7ff3-41a3-b730-86c25a4d6ff5")]
            public virtual Ranorex.Button btnOK
            {
                get
                {
                    return _btnokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnOK item info.
            /// </summary>
            [RepositoryItemInfo("0c51ebc5-7ff3-41a3-b730-86c25a4d6ff5")]
            public virtual RepoItemInfo btnOKInfo
            {
                get
                {
                    return _btnokInfo;
                }
            }
        }

        /// <summary>
        /// The PromptFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("bf0eb807-2d1f-47b3-b271-73e46b391100")]
        public partial class PromptFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btnyesInfo;
            RepoItemInfo _txtpromptInfo;
            RepoItemInfo _btnnoInfo;
            RepoItemInfo _btnokInfo;

            /// <summary>
            /// Creates a new PromptForm  folder.
            /// </summary>
            public PromptFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("PromptForm", "/form[@controlname='PromptForm']", parentFolder, 30000, null, true, "bf0eb807-2d1f-47b3-b271-73e46b391100", "")
            {
                _btnyesInfo = new RepoItemInfo(this, "btnYes", ".//toolbar[@accessiblename='Toolbar']/button[@accessiblename='Yes']", 30000, null, "a831ec57-3192-47fd-aa3a-8d9146c3067b");
                _txtpromptInfo = new RepoItemInfo(this, "txtPrompt", "container[@controlname='pnlBase']/?/?/container[@controlname='pnlMessage']/?/?/text", 30000, null, "22690823-bbc8-4df5-a355-3076c6c6f0fd");
                _btnnoInfo = new RepoItemInfo(this, "btnNo", ".//toolbar[@accessiblename='Toolbar']/button[@accessiblename='No']", 30000, null, "4e3ae3c4-21b6-45e6-bbf4-8c0a5b4e5f4c");
                _btnokInfo = new RepoItemInfo(this, "btnOK", ".//toolbar[@accessiblename='Toolbar']/button[@accessiblename='OK']", 30000, null, "268497ef-5fa8-4682-bb47-b79d67b28324");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("bf0eb807-2d1f-47b3-b271-73e46b391100")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("bf0eb807-2d1f-47b3-b271-73e46b391100")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btnYes item.
            /// </summary>
            [RepositoryItem("a831ec57-3192-47fd-aa3a-8d9146c3067b")]
            public virtual Ranorex.Button btnYes
            {
                get
                {
                    return _btnyesInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnYes item info.
            /// </summary>
            [RepositoryItemInfo("a831ec57-3192-47fd-aa3a-8d9146c3067b")]
            public virtual RepoItemInfo btnYesInfo
            {
                get
                {
                    return _btnyesInfo;
                }
            }

            /// <summary>
            /// The txtPrompt item.
            /// </summary>
            [RepositoryItem("22690823-bbc8-4df5-a355-3076c6c6f0fd")]
            public virtual Ranorex.Text txtPrompt
            {
                get
                {
                    return _txtpromptInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txtPrompt item info.
            /// </summary>
            [RepositoryItemInfo("22690823-bbc8-4df5-a355-3076c6c6f0fd")]
            public virtual RepoItemInfo txtPromptInfo
            {
                get
                {
                    return _txtpromptInfo;
                }
            }

            /// <summary>
            /// The btnNo item.
            /// </summary>
            [RepositoryItem("4e3ae3c4-21b6-45e6-bbf4-8c0a5b4e5f4c")]
            public virtual Ranorex.Button btnNo
            {
                get
                {
                    return _btnnoInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnNo item info.
            /// </summary>
            [RepositoryItemInfo("4e3ae3c4-21b6-45e6-bbf4-8c0a5b4e5f4c")]
            public virtual RepoItemInfo btnNoInfo
            {
                get
                {
                    return _btnnoInfo;
                }
            }

            /// <summary>
            /// The btnOK item.
            /// </summary>
            [RepositoryItem("268497ef-5fa8-4682-bb47-b79d67b28324")]
            public virtual Ranorex.Button btnOK
            {
                get
                {
                    return _btnokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnOK item info.
            /// </summary>
            [RepositoryItemInfo("268497ef-5fa8-4682-bb47-b79d67b28324")]
            public virtual RepoItemInfo btnOKInfo
            {
                get
                {
                    return _btnokInfo;
                }
            }
        }

        /// <summary>
        /// The MessageDetailFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("aca7f0c5-ba85-48e3-a0ac-12a3842f8ab4")]
        public partial class MessageDetailFormAppFolder : RepoGenBaseFolder
        {
            CommunicationsFolders.MenubarFillPanelFolder1 _menubarfillpanel;
            RepoItemInfo _btnaddfileInfo;

            /// <summary>
            /// Creates a new MessageDetailForm  folder.
            /// </summary>
            public MessageDetailFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MessageDetailForm", "/form[@controlname='MessageDetailForm']", parentFolder, 30000, null, true, "aca7f0c5-ba85-48e3-a0ac-12a3842f8ab4", "")
            {
                _menubarfillpanel = new CommunicationsFolders.MenubarFillPanelFolder1(this);
                _btnaddfileInfo = new RepoItemInfo(this, "btnAddFile", "container[@controlname='menubar_Fill_Panel']/container[@controlname='pnlBase']//container[@controlname='scFiles']/?/?/button[@accessiblerole='PushButton']", 30000, null, "7d4ea142-2413-4752-9e16-eaccbe2d4086");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("aca7f0c5-ba85-48e3-a0ac-12a3842f8ab4")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("aca7f0c5-ba85-48e3-a0ac-12a3842f8ab4")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btnAddFile item.
            /// </summary>
            [RepositoryItem("7d4ea142-2413-4752-9e16-eaccbe2d4086")]
            public virtual Ranorex.Button btnAddFile
            {
                get
                {
                    return _btnaddfileInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnAddFile item info.
            /// </summary>
            [RepositoryItemInfo("7d4ea142-2413-4752-9e16-eaccbe2d4086")]
            public virtual RepoItemInfo btnAddFileInfo
            {
                get
                {
                    return _btnaddfileInfo;
                }
            }

            /// <summary>
            /// The MenubarFillPanel folder.
            /// </summary>
            [RepositoryFolder("985987e5-4472-4077-8e05-5ac732ea7110")]
            public virtual CommunicationsFolders.MenubarFillPanelFolder1 MenubarFillPanel
            {
                get { return _menubarfillpanel; }
            }
        }

        /// <summary>
        /// The MenubarFillPanelFolder1 folder.
        /// </summary>
        [RepositoryFolder("985987e5-4472-4077-8e05-5ac732ea7110")]
        public partial class MenubarFillPanelFolder1 : RepoGenBaseFolder
        {
            RepoItemInfo _btnsendInfo;
            RepoItemInfo _btnaddcontactInfo;
            RepoItemInfo _txtmessageInfo;

            /// <summary>
            /// Creates a new MenubarFillPanel  folder.
            /// </summary>
            public MenubarFillPanelFolder1(RepoGenBaseFolder parentFolder) :
                    base("MenubarFillPanel", "container[@controlname='menubar_Fill_Panel']", parentFolder, 30000, null, false, "985987e5-4472-4077-8e05-5ac732ea7110", "")
            {
                _btnsendInfo = new RepoItemInfo(this, "btnSend", ".//toolbar[@accessiblename='Toolbar']/button[@accessiblename='Send']", 30000, null, "d99a0cdb-fbe3-43c2-ab0b-d03c1f0a7892");
                _btnaddcontactInfo = new RepoItemInfo(this, "btnAddContact", "container[@controlname='pnlBase']//container[@controlname='scToPeople']/?/?/button[@accessiblerole='PushButton']", 30000, null, "26203887-7c7a-47e0-ae18-06c1cb6acbe9");
                _txtmessageInfo = new RepoItemInfo(this, "txtMessage", "container[@controlname='pnlBase']//element[@controlname='txtSummary']/text[@accessiblerole='Text']/text[@accessiblerole='Text']", 30000, null, "ccd07f6b-e04d-440f-89d2-e9f57ca1357b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("985987e5-4472-4077-8e05-5ac732ea7110")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("985987e5-4472-4077-8e05-5ac732ea7110")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btnSend item.
            /// </summary>
            [RepositoryItem("d99a0cdb-fbe3-43c2-ab0b-d03c1f0a7892")]
            public virtual Ranorex.Button btnSend
            {
                get
                {
                    return _btnsendInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnSend item info.
            /// </summary>
            [RepositoryItemInfo("d99a0cdb-fbe3-43c2-ab0b-d03c1f0a7892")]
            public virtual RepoItemInfo btnSendInfo
            {
                get
                {
                    return _btnsendInfo;
                }
            }

            /// <summary>
            /// The btnAddContact item.
            /// </summary>
            [RepositoryItem("26203887-7c7a-47e0-ae18-06c1cb6acbe9")]
            public virtual Ranorex.Button btnAddContact
            {
                get
                {
                    return _btnaddcontactInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnAddContact item info.
            /// </summary>
            [RepositoryItemInfo("26203887-7c7a-47e0-ae18-06c1cb6acbe9")]
            public virtual RepoItemInfo btnAddContactInfo
            {
                get
                {
                    return _btnaddcontactInfo;
                }
            }

            /// <summary>
            /// The txtMessage item.
            /// </summary>
            [RepositoryItem("ccd07f6b-e04d-440f-89d2-e9f57ca1357b")]
            public virtual Ranorex.Text txtMessage
            {
                get
                {
                    return _txtmessageInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txtMessage item info.
            /// </summary>
            [RepositoryItemInfo("ccd07f6b-e04d-440f-89d2-e9f57ca1357b")]
            public virtual RepoItemInfo txtMessageInfo
            {
                get
                {
                    return _txtmessageInfo;
                }
            }
        }

        /// <summary>
        /// The PeopleSelectFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("d45a8cb3-f807-4139-98be-7730fb5878eb")]
        public partial class PeopleSelectFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _listcontactInfo;

            /// <summary>
            /// Creates a new PeopleSelectForm  folder.
            /// </summary>
            public PeopleSelectFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("PeopleSelectForm", "/form[@controlname='PeopleSelectForm']", parentFolder, 30000, null, true, "d45a8cb3-f807-4139-98be-7730fb5878eb", "")
            {
                _listcontactInfo = new RepoItemInfo(this, "listContact", "container[@controlname='panel1']//row[@accessiblename='Band 0 row 1']/cell[@accessiblename='Name']", 30000, null, "e332c515-231a-4f17-b41b-87ace848d8a0");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d45a8cb3-f807-4139-98be-7730fb5878eb")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d45a8cb3-f807-4139-98be-7730fb5878eb")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The listContact item.
            /// </summary>
            [RepositoryItem("e332c515-231a-4f17-b41b-87ace848d8a0")]
            public virtual Ranorex.Cell listContact
            {
                get
                {
                    return _listcontactInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The listContact item info.
            /// </summary>
            [RepositoryItemInfo("e332c515-231a-4f17-b41b-87ace848d8a0")]
            public virtual RepoItemInfo listContactInfo
            {
                get
                {
                    return _listcontactInfo;
                }
            }
        }

        /// <summary>
        /// The NewEmailFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("439b703a-b5f2-43b4-b28b-7169db41d32c")]
        public partial class NewEmailFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _toemailInfo;

            /// <summary>
            /// Creates a new NewEmailForm  folder.
            /// </summary>
            public NewEmailFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("NewEmailForm", "/form[@controlname='NewEmailForm']", parentFolder, 30000, null, true, "439b703a-b5f2-43b4-b28b-7169db41d32c", "")
            {
                _toemailInfo = new RepoItemInfo(this, "ToEmail", "form[@controlname='NewEmailForm']/?/?/container[@controlname='scToPeople']/element[@controlname='ubtnIcon']", 30000, null, "d27cabb0-bd51-448e-a3ea-382266622fb9");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("439b703a-b5f2-43b4-b28b-7169db41d32c")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("439b703a-b5f2-43b4-b28b-7169db41d32c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ToEmail item.
            /// </summary>
            [RepositoryItem("d27cabb0-bd51-448e-a3ea-382266622fb9")]
            public virtual Ranorex.Unknown ToEmail
            {
                get
                {
                    return _toemailInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The ToEmail item info.
            /// </summary>
            [RepositoryItemInfo("d27cabb0-bd51-448e-a3ea-382266622fb9")]
            public virtual RepoItemInfo ToEmailInfo
            {
                get
                {
                    return _toemailInfo;
                }
            }
        }

        /// <summary>
        /// The ContextMenuAppFolder folder.
        /// </summary>
        [RepositoryFolder("5fe197e3-e329-4307-8602-ba1f0167b538")]
        public partial class ContextMenuAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _openInfo;
            RepoItemInfo _menuitemnewInfo;
            RepoItemInfo _separatorInfo;
            RepoItemInfo _replyInfo;
            RepoItemInfo _forwardInfo;
            RepoItemInfo _separator1Info;
            RepoItemInfo _markInfo;
            RepoItemInfo _separator2Info;
            RepoItemInfo _timeentryInfo;
            RepoItemInfo _timesaverInfo;
            RepoItemInfo _followuptodoInfo;
            RepoItemInfo _addtofileInfo;
            RepoItemInfo _printInfo;
            RepoItemInfo _separator3Info;
            RepoItemInfo _deleteInfo;
            RepoItemInfo _separator4Info;
            RepoItemInfo _contextInfo;

            /// <summary>
            /// Creates a new ContextMenu  folder.
            /// </summary>
            public ContextMenuAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ContextMenu", "/contextmenu", parentFolder, 30000, null, false, "5fe197e3-e329-4307-8602-ba1f0167b538", "")
            {
                _openInfo = new RepoItemInfo(this, "Open", "?/?/menuitem[1]", 30000, null, "86002fde-13e5-434f-9c80-e9d8a295a392");
                _menuitemnewInfo = new RepoItemInfo(this, "MenuItemNew", "?/?/menuitem[2]", 30000, null, "188c7de1-0d81-423e-8c9e-ff39cc9e04b5");
                _separatorInfo = new RepoItemInfo(this, "Separator", "?/?/separator[1]", 30000, null, "e19d3aa0-49c3-40ef-8c58-7252d899e456");
                _replyInfo = new RepoItemInfo(this, "Reply", "?/?/menuitem[3]", 30000, null, "308c2924-971e-441e-abb1-0eadfa44edd4");
                _forwardInfo = new RepoItemInfo(this, "Forward", "?/?/menuitem[4]", 30000, null, "369691a6-33d3-430a-8bc0-00d8ae353ca2");
                _separator1Info = new RepoItemInfo(this, "Separator1", "?/?/separator[2]", 30000, null, "9ed4da31-9bdd-4df3-8185-c6ad96b2f560");
                _markInfo = new RepoItemInfo(this, "Mark", "?/?/menuitem[5]", 30000, null, "b4fb1489-ea6b-45e2-8364-53c5c4408888");
                _separator2Info = new RepoItemInfo(this, "Separator2", "?/?/separator[3]", 30000, null, "ce2a3cd3-2ec6-4e21-b8c0-773a79b1631a");
                _timeentryInfo = new RepoItemInfo(this, "TimeEntry", "?/?/menuitem[6]", 30000, null, "65f974b5-3d16-4937-8c75-5e8c9193e470");
                _timesaverInfo = new RepoItemInfo(this, "TimeSaver", "?/?/menuitem[7]", 30000, null, "7879b5e5-3072-4da7-838e-ccb172e6eb06");
                _followuptodoInfo = new RepoItemInfo(this, "FollowUpToDo", "?/?/menuitem[8]", 30000, null, "6697ee67-3f6d-44f8-950f-1e914fac7295");
                _addtofileInfo = new RepoItemInfo(this, "AddToFile", "?/?/menuitem[9]", 30000, null, "f6b30e7f-32c2-44ea-b5af-2e2be0afe804");
                _printInfo = new RepoItemInfo(this, "Print", "?/?/menuitem[10]", 30000, null, "8bfac731-4b53-4b06-b4fd-fa7361f0fd2f");
                _separator3Info = new RepoItemInfo(this, "Separator3", "?/?/separator[4]", 30000, null, "2d167705-7aa3-409d-aa65-186871f60b9b");
                _deleteInfo = new RepoItemInfo(this, "Delete", "?/?/menuitem[11]", 30000, null, "6f7618f2-b031-4812-bac0-bb4109813842");
                _separator4Info = new RepoItemInfo(this, "Separator4", "?/?/separator[5]", 30000, null, "44726aec-3325-4b35-bd7b-14cb91e32bd2");
                _contextInfo = new RepoItemInfo(this, "Context", "contextmenu", 30000, null, "e4b76eec-2ec5-4543-9f54-33eca241a2e5");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5fe197e3-e329-4307-8602-ba1f0167b538")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5fe197e3-e329-4307-8602-ba1f0167b538")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Open item.
            /// </summary>
            [RepositoryItem("86002fde-13e5-434f-9c80-e9d8a295a392")]
            public virtual Ranorex.MenuItem Open
            {
                get
                {
                    return _openInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Open item info.
            /// </summary>
            [RepositoryItemInfo("86002fde-13e5-434f-9c80-e9d8a295a392")]
            public virtual RepoItemInfo OpenInfo
            {
                get
                {
                    return _openInfo;
                }
            }

            /// <summary>
            /// The MenuItemNew item.
            /// </summary>
            [RepositoryItem("188c7de1-0d81-423e-8c9e-ff39cc9e04b5")]
            public virtual Ranorex.MenuItem MenuItemNew
            {
                get
                {
                    return _menuitemnewInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MenuItemNew item info.
            /// </summary>
            [RepositoryItemInfo("188c7de1-0d81-423e-8c9e-ff39cc9e04b5")]
            public virtual RepoItemInfo MenuItemNewInfo
            {
                get
                {
                    return _menuitemnewInfo;
                }
            }

            /// <summary>
            /// The Separator item.
            /// </summary>
            [RepositoryItem("e19d3aa0-49c3-40ef-8c58-7252d899e456")]
            public virtual Ranorex.Separator Separator
            {
                get
                {
                    return _separatorInfo.CreateAdapter<Ranorex.Separator>(true);
                }
            }

            /// <summary>
            /// The Separator item info.
            /// </summary>
            [RepositoryItemInfo("e19d3aa0-49c3-40ef-8c58-7252d899e456")]
            public virtual RepoItemInfo SeparatorInfo
            {
                get
                {
                    return _separatorInfo;
                }
            }

            /// <summary>
            /// The Reply item.
            /// </summary>
            [RepositoryItem("308c2924-971e-441e-abb1-0eadfa44edd4")]
            public virtual Ranorex.MenuItem Reply
            {
                get
                {
                    return _replyInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Reply item info.
            /// </summary>
            [RepositoryItemInfo("308c2924-971e-441e-abb1-0eadfa44edd4")]
            public virtual RepoItemInfo ReplyInfo
            {
                get
                {
                    return _replyInfo;
                }
            }

            /// <summary>
            /// The Forward item.
            /// </summary>
            [RepositoryItem("369691a6-33d3-430a-8bc0-00d8ae353ca2")]
            public virtual Ranorex.MenuItem Forward
            {
                get
                {
                    return _forwardInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Forward item info.
            /// </summary>
            [RepositoryItemInfo("369691a6-33d3-430a-8bc0-00d8ae353ca2")]
            public virtual RepoItemInfo ForwardInfo
            {
                get
                {
                    return _forwardInfo;
                }
            }

            /// <summary>
            /// The Separator1 item.
            /// </summary>
            [RepositoryItem("9ed4da31-9bdd-4df3-8185-c6ad96b2f560")]
            public virtual Ranorex.Separator Separator1
            {
                get
                {
                    return _separator1Info.CreateAdapter<Ranorex.Separator>(true);
                }
            }

            /// <summary>
            /// The Separator1 item info.
            /// </summary>
            [RepositoryItemInfo("9ed4da31-9bdd-4df3-8185-c6ad96b2f560")]
            public virtual RepoItemInfo Separator1Info
            {
                get
                {
                    return _separator1Info;
                }
            }

            /// <summary>
            /// The Mark item.
            /// </summary>
            [RepositoryItem("b4fb1489-ea6b-45e2-8364-53c5c4408888")]
            public virtual Ranorex.MenuItem Mark
            {
                get
                {
                    return _markInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Mark item info.
            /// </summary>
            [RepositoryItemInfo("b4fb1489-ea6b-45e2-8364-53c5c4408888")]
            public virtual RepoItemInfo MarkInfo
            {
                get
                {
                    return _markInfo;
                }
            }

            /// <summary>
            /// The Separator2 item.
            /// </summary>
            [RepositoryItem("ce2a3cd3-2ec6-4e21-b8c0-773a79b1631a")]
            public virtual Ranorex.Separator Separator2
            {
                get
                {
                    return _separator2Info.CreateAdapter<Ranorex.Separator>(true);
                }
            }

            /// <summary>
            /// The Separator2 item info.
            /// </summary>
            [RepositoryItemInfo("ce2a3cd3-2ec6-4e21-b8c0-773a79b1631a")]
            public virtual RepoItemInfo Separator2Info
            {
                get
                {
                    return _separator2Info;
                }
            }

            /// <summary>
            /// The TimeEntry item.
            /// </summary>
            [RepositoryItem("65f974b5-3d16-4937-8c75-5e8c9193e470")]
            public virtual Ranorex.MenuItem TimeEntry
            {
                get
                {
                    return _timeentryInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The TimeEntry item info.
            /// </summary>
            [RepositoryItemInfo("65f974b5-3d16-4937-8c75-5e8c9193e470")]
            public virtual RepoItemInfo TimeEntryInfo
            {
                get
                {
                    return _timeentryInfo;
                }
            }

            /// <summary>
            /// The TimeSaver item.
            /// </summary>
            [RepositoryItem("7879b5e5-3072-4da7-838e-ccb172e6eb06")]
            public virtual Ranorex.MenuItem TimeSaver
            {
                get
                {
                    return _timesaverInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The TimeSaver item info.
            /// </summary>
            [RepositoryItemInfo("7879b5e5-3072-4da7-838e-ccb172e6eb06")]
            public virtual RepoItemInfo TimeSaverInfo
            {
                get
                {
                    return _timesaverInfo;
                }
            }

            /// <summary>
            /// The FollowUpToDo item.
            /// </summary>
            [RepositoryItem("6697ee67-3f6d-44f8-950f-1e914fac7295")]
            public virtual Ranorex.MenuItem FollowUpToDo
            {
                get
                {
                    return _followuptodoInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The FollowUpToDo item info.
            /// </summary>
            [RepositoryItemInfo("6697ee67-3f6d-44f8-950f-1e914fac7295")]
            public virtual RepoItemInfo FollowUpToDoInfo
            {
                get
                {
                    return _followuptodoInfo;
                }
            }

            /// <summary>
            /// The AddToFile item.
            /// </summary>
            [RepositoryItem("f6b30e7f-32c2-44ea-b5af-2e2be0afe804")]
            public virtual Ranorex.MenuItem AddToFile
            {
                get
                {
                    return _addtofileInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The AddToFile item info.
            /// </summary>
            [RepositoryItemInfo("f6b30e7f-32c2-44ea-b5af-2e2be0afe804")]
            public virtual RepoItemInfo AddToFileInfo
            {
                get
                {
                    return _addtofileInfo;
                }
            }

            /// <summary>
            /// The Print item.
            /// </summary>
            [RepositoryItem("8bfac731-4b53-4b06-b4fd-fa7361f0fd2f")]
            public virtual Ranorex.MenuItem Print
            {
                get
                {
                    return _printInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Print item info.
            /// </summary>
            [RepositoryItemInfo("8bfac731-4b53-4b06-b4fd-fa7361f0fd2f")]
            public virtual RepoItemInfo PrintInfo
            {
                get
                {
                    return _printInfo;
                }
            }

            /// <summary>
            /// The Separator3 item.
            /// </summary>
            [RepositoryItem("2d167705-7aa3-409d-aa65-186871f60b9b")]
            public virtual Ranorex.Separator Separator3
            {
                get
                {
                    return _separator3Info.CreateAdapter<Ranorex.Separator>(true);
                }
            }

            /// <summary>
            /// The Separator3 item info.
            /// </summary>
            [RepositoryItemInfo("2d167705-7aa3-409d-aa65-186871f60b9b")]
            public virtual RepoItemInfo Separator3Info
            {
                get
                {
                    return _separator3Info;
                }
            }

            /// <summary>
            /// The Delete item.
            /// </summary>
            [RepositoryItem("6f7618f2-b031-4812-bac0-bb4109813842")]
            public virtual Ranorex.MenuItem Delete
            {
                get
                {
                    return _deleteInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Delete item info.
            /// </summary>
            [RepositoryItemInfo("6f7618f2-b031-4812-bac0-bb4109813842")]
            public virtual RepoItemInfo DeleteInfo
            {
                get
                {
                    return _deleteInfo;
                }
            }

            /// <summary>
            /// The Separator4 item.
            /// </summary>
            [RepositoryItem("44726aec-3325-4b35-bd7b-14cb91e32bd2")]
            public virtual Ranorex.Separator Separator4
            {
                get
                {
                    return _separator4Info.CreateAdapter<Ranorex.Separator>(true);
                }
            }

            /// <summary>
            /// The Separator4 item info.
            /// </summary>
            [RepositoryItemInfo("44726aec-3325-4b35-bd7b-14cb91e32bd2")]
            public virtual RepoItemInfo Separator4Info
            {
                get
                {
                    return _separator4Info;
                }
            }

            /// <summary>
            /// The Context item.
            /// </summary>
            [RepositoryItem("e4b76eec-2ec5-4543-9f54-33eca241a2e5")]
            public virtual Ranorex.ContextMenu Context
            {
                get
                {
                    return _contextInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Context item info.
            /// </summary>
            [RepositoryItemInfo("e4b76eec-2ec5-4543-9f54-33eca241a2e5")]
            public virtual RepoItemInfo ContextInfo
            {
                get
                {
                    return _contextInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
