///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace SmokeTest.Repositories
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Documents element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("ea52fcf3-9a43-460e-ae21-fd09d87ef9e5")]
    public partial class Documents : RepoGenBaseFolder
    {
        static Documents instance = new Documents();
        DocumentsFolders.MainFormAppFolder _mainform;
        DocumentsFolders.DocumentDetailAppFolder _documentdetail;
        DocumentsFolders.OpenAppFolder _open;
        DocumentsFolders.FileSelectFormAppFolder _fileselectform;
        DocumentsFolders.FindFilesFormAppFolder _findfilesform;
        DocumentsFolders.PromptFormAppFolder _promptform;
        DocumentsFolders.ProgressFormAppFolder _progressform;

        /// <summary>
        /// Gets the singleton class instance representing the Documents element repository.
        /// </summary>
        [RepositoryFolder("ea52fcf3-9a43-460e-ae21-fd09d87ef9e5")]
        public static Documents Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Documents() 
            : base("Documents", "/", null, 0, false, "ea52fcf3-9a43-460e-ae21-fd09d87ef9e5", ".\\RepositoryImages\\Documentsea52fcf3.rximgres")
        {
            _mainform = new DocumentsFolders.MainFormAppFolder(this);
            _documentdetail = new DocumentsFolders.DocumentDetailAppFolder(this);
            _open = new DocumentsFolders.OpenAppFolder(this);
            _fileselectform = new DocumentsFolders.FileSelectFormAppFolder(this);
            _findfilesform = new DocumentsFolders.FindFilesFormAppFolder(this);
            _promptform = new DocumentsFolders.PromptFormAppFolder(this);
            _progressform = new DocumentsFolders.ProgressFormAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("ea52fcf3-9a43-460e-ae21-fd09d87ef9e5")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The MainForm folder.
        /// </summary>
        [RepositoryFolder("60363a32-d8b4-4df5-a972-7f0acde8cc56")]
        public virtual DocumentsFolders.MainFormAppFolder MainForm
        {
            get { return _mainform; }
        }

        /// <summary>
        /// The DocumentDetail folder.
        /// </summary>
        [RepositoryFolder("99941e2d-5c77-4e95-a788-00f265028bdc")]
        public virtual DocumentsFolders.DocumentDetailAppFolder DocumentDetail
        {
            get { return _documentdetail; }
        }

        /// <summary>
        /// The Open folder.
        /// </summary>
        [RepositoryFolder("51eef256-da32-4f80-bddf-b71842b97b11")]
        public virtual DocumentsFolders.OpenAppFolder Open
        {
            get { return _open; }
        }

        /// <summary>
        /// The FileSelectForm folder.
        /// </summary>
        [RepositoryFolder("b44a82d5-8e21-45bf-9c27-407befd88902")]
        public virtual DocumentsFolders.FileSelectFormAppFolder FileSelectForm
        {
            get { return _fileselectform; }
        }

        /// <summary>
        /// The FindFilesForm folder.
        /// </summary>
        [RepositoryFolder("5b4e3fc8-de5d-4877-b8f5-e121f5c3053b")]
        public virtual DocumentsFolders.FindFilesFormAppFolder FindFilesForm
        {
            get { return _findfilesform; }
        }

        /// <summary>
        /// The PromptForm folder.
        /// </summary>
        [RepositoryFolder("c4c663cf-05a9-4605-8631-0ff73c7a297e")]
        public virtual DocumentsFolders.PromptFormAppFolder PromptForm
        {
            get { return _promptform; }
        }

        /// <summary>
        /// The ProgressForm folder.
        /// </summary>
        [RepositoryFolder("ee3e8a9a-c406-48d6-b0bd-076c5ea5bd2b")]
        public virtual DocumentsFolders.ProgressFormAppFolder ProgressForm
        {
            get { return _progressform; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class DocumentsFolders
    {
        /// <summary>
        /// The MainFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("60363a32-d8b4-4df5-a972-7f0acde8cc56")]
        public partial class MainFormAppFolder : RepoGenBaseFolder
        {
            DocumentsFolders.DocumentsIndexFormFolder _documentsindexform;
            RepoItemInfo _btndocumentsInfo;
            RepoItemInfo _btndocuments1Info;

            /// <summary>
            /// Creates a new MainForm  folder.
            /// </summary>
            public MainFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MainForm", "/form[@controlname='MainForm']", parentFolder, 30000, null, true, "60363a32-d8b4-4df5-a972-7f0acde8cc56", "")
            {
                _documentsindexform = new DocumentsFolders.DocumentsIndexFormFolder(this);
                _btndocumentsInfo = new RepoItemInfo(this, "btnDocuments", "container[@controlname='pLeft']//tree[@accessiblerole='Outline']/button[@accessiblename='Documents']", 30000, null, "0257a548-bfb7-40fe-b6c4-5be1531df3ce");
                _btndocuments1Info = new RepoItemInfo(this, "btnDocuments1", "?/?/tree[@accessiblerole='Outline']/button[@accessiblename='Documents']", 5000, null, "41cff213-e81a-4f4f-ba3b-1137cd932bb6");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("60363a32-d8b4-4df5-a972-7f0acde8cc56")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("60363a32-d8b4-4df5-a972-7f0acde8cc56")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btnDocuments item.
            /// </summary>
            [RepositoryItem("0257a548-bfb7-40fe-b6c4-5be1531df3ce")]
            public virtual Ranorex.Button btnDocuments
            {
                get
                {
                    return _btndocumentsInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnDocuments item info.
            /// </summary>
            [RepositoryItemInfo("0257a548-bfb7-40fe-b6c4-5be1531df3ce")]
            public virtual RepoItemInfo btnDocumentsInfo
            {
                get
                {
                    return _btndocumentsInfo;
                }
            }

            /// <summary>
            /// The btnDocuments1 item.
            /// </summary>
            [RepositoryItem("41cff213-e81a-4f4f-ba3b-1137cd932bb6")]
            public virtual Ranorex.Button btnDocuments1
            {
                get
                {
                    return _btndocuments1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnDocuments1 item info.
            /// </summary>
            [RepositoryItemInfo("41cff213-e81a-4f4f-ba3b-1137cd932bb6")]
            public virtual RepoItemInfo btnDocuments1Info
            {
                get
                {
                    return _btndocuments1Info;
                }
            }

            /// <summary>
            /// The DocumentsIndexForm folder.
            /// </summary>
            [RepositoryFolder("9eb199ef-fb4e-4968-9a31-7340c6824375")]
            public virtual DocumentsFolders.DocumentsIndexFormFolder DocumentsIndexForm
            {
                get { return _documentsindexform; }
            }
        }

        /// <summary>
        /// The DocumentsIndexFormFolder folder.
        /// </summary>
        [RepositoryFolder("9eb199ef-fb4e-4968-9a31-7340c6824375")]
        public partial class DocumentsIndexFormFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btnnewdocumentInfo;
            RepoItemInfo _listfirstitemInfo;

            /// <summary>
            /// Creates a new DocumentsIndexForm  folder.
            /// </summary>
            public DocumentsIndexFormFolder(RepoGenBaseFolder parentFolder) :
                    base("DocumentsIndexForm", "?/?/form[@controlname='DocumentsIndexForm']", parentFolder, 30000, null, false, "9eb199ef-fb4e-4968-9a31-7340c6824375", "")
            {
                _btnnewdocumentInfo = new RepoItemInfo(this, "btnNewDocument", "container[@controlname='menubar_Fill_Panel']//toolbar[@accessiblename='Toolbar']/button[@accessiblename='New']", 30000, null, "193d6c00-d75e-47f0-84f7-5bee14e3cd8a");
                _listfirstitemInfo = new RepoItemInfo(this, "listFirstItem", "container[@controlname='pnlBase']//container[@controlname='panel1' and @caption='' and @controltypename='SplitterPanel']/?/?/table/row[1]/cell[@accessiblename='File']", 30000, null, "c214fbaa-0743-4a06-99f2-bcb4e2c86e66");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9eb199ef-fb4e-4968-9a31-7340c6824375")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9eb199ef-fb4e-4968-9a31-7340c6824375")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btnNewDocument item.
            /// </summary>
            [RepositoryItem("193d6c00-d75e-47f0-84f7-5bee14e3cd8a")]
            public virtual Ranorex.Button btnNewDocument
            {
                get
                {
                    return _btnnewdocumentInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnNewDocument item info.
            /// </summary>
            [RepositoryItemInfo("193d6c00-d75e-47f0-84f7-5bee14e3cd8a")]
            public virtual RepoItemInfo btnNewDocumentInfo
            {
                get
                {
                    return _btnnewdocumentInfo;
                }
            }

            /// <summary>
            /// The listFirstItem item.
            /// </summary>
            [RepositoryItem("c214fbaa-0743-4a06-99f2-bcb4e2c86e66")]
            public virtual Ranorex.Cell listFirstItem
            {
                get
                {
                    return _listfirstitemInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The listFirstItem item info.
            /// </summary>
            [RepositoryItemInfo("c214fbaa-0743-4a06-99f2-bcb4e2c86e66")]
            public virtual RepoItemInfo listFirstItemInfo
            {
                get
                {
                    return _listfirstitemInfo;
                }
            }
        }

        /// <summary>
        /// The DocumentDetailAppFolder folder.
        /// </summary>
        [RepositoryFolder("99941e2d-5c77-4e95-a788-00f265028bdc")]
        public partial class DocumentDetailAppFolder : RepoGenBaseFolder
        {
            DocumentsFolders.PnlBaseFolder _pnlbase;
            DocumentsFolders.MenubarFillPanelFolder _menubarfillpanel;

            /// <summary>
            /// Creates a new DocumentDetail  folder.
            /// </summary>
            public DocumentDetailAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DocumentDetail", "/form[@controlname='DocumentDetail']", parentFolder, 30000, null, true, "99941e2d-5c77-4e95-a788-00f265028bdc", "")
            {
                _pnlbase = new DocumentsFolders.PnlBaseFolder(this);
                _menubarfillpanel = new DocumentsFolders.MenubarFillPanelFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("99941e2d-5c77-4e95-a788-00f265028bdc")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("99941e2d-5c77-4e95-a788-00f265028bdc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The PnlBase folder.
            /// </summary>
            [RepositoryFolder("9be14c92-27d3-4f11-aea1-21d8af2bf320")]
            public virtual DocumentsFolders.PnlBaseFolder PnlBase
            {
                get { return _pnlbase; }
            }

            /// <summary>
            /// The MenubarFillPanel folder.
            /// </summary>
            [RepositoryFolder("e9762cdc-822d-4c50-aee0-d6911df09ecc")]
            public virtual DocumentsFolders.MenubarFillPanelFolder MenubarFillPanel
            {
                get { return _menubarfillpanel; }
            }
        }

        /// <summary>
        /// The PnlBaseFolder folder.
        /// </summary>
        [RepositoryFolder("9be14c92-27d3-4f11-aea1-21d8af2bf320")]
        public partial class PnlBaseFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btnfilesandpeopleInfo;
            RepoItemInfo _btnlocationInfo;
            RepoItemInfo _txtdocumenttitleInfo;
            RepoItemInfo _btnaddfileInfo;
            RepoItemInfo _btnopenInfo;
            RepoItemInfo _filelocationpathtextInfo;

            /// <summary>
            /// Creates a new PnlBase  folder.
            /// </summary>
            public PnlBaseFolder(RepoGenBaseFolder parentFolder) :
                    base("PnlBase", "?/?/container[@controlname='pnlBase']", parentFolder, 30000, null, false, "9be14c92-27d3-4f11-aea1-21d8af2bf320", "")
            {
                _btnfilesandpeopleInfo = new RepoItemInfo(this, "btnFilesAndPeople", "?/?/container[@controlname='pnlBrad']/?/?/text[@controlname='alblFilesAndPeople']", 30000, null, "f8aa4e78-1a1b-45e8-93d1-1029c4b88207");
                _btnlocationInfo = new RepoItemInfo(this, "btnLocation", "?/?/element[@controlname='abtnLocation']/button[@accessiblename='Location...']", 30000, null, "28e770bc-1592-475f-b97e-965b14fbad16");
                _txtdocumenttitleInfo = new RepoItemInfo(this, "txtDocumentTitle", "?/?/text[@controlname='atbTitle']", 30000, null, "8b6306cd-c67f-4019-865b-ede12fa4b76f");
                _btnaddfileInfo = new RepoItemInfo(this, "btnAddFile", "?/?/container[@controlname='scFiles']/?/?/button[@accessiblerole='PushButton']", 30000, null, "67daa478-1860-44af-af9b-ff7680d070a0");
                _btnopenInfo = new RepoItemInfo(this, "btnOpen", "?/?/element[@controlname='abtnOpen']/button[@accessiblename='Open']", 30000, null, "9381130a-5871-4373-a637-1dd8e3b0a099");
                _filelocationpathtextInfo = new RepoItemInfo(this, "fileLocationPathText", "?/?/text[@controlname='atbLocationPath']", 30000, null, "f7beae1a-a1da-47fe-b07e-4cf7144b7c05");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9be14c92-27d3-4f11-aea1-21d8af2bf320")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9be14c92-27d3-4f11-aea1-21d8af2bf320")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btnFilesAndPeople item.
            /// </summary>
            [RepositoryItem("f8aa4e78-1a1b-45e8-93d1-1029c4b88207")]
            public virtual Ranorex.Text btnFilesAndPeople
            {
                get
                {
                    return _btnfilesandpeopleInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The btnFilesAndPeople item info.
            /// </summary>
            [RepositoryItemInfo("f8aa4e78-1a1b-45e8-93d1-1029c4b88207")]
            public virtual RepoItemInfo btnFilesAndPeopleInfo
            {
                get
                {
                    return _btnfilesandpeopleInfo;
                }
            }

            /// <summary>
            /// The btnLocation item.
            /// </summary>
            [RepositoryItem("28e770bc-1592-475f-b97e-965b14fbad16")]
            public virtual Ranorex.Button btnLocation
            {
                get
                {
                    return _btnlocationInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnLocation item info.
            /// </summary>
            [RepositoryItemInfo("28e770bc-1592-475f-b97e-965b14fbad16")]
            public virtual RepoItemInfo btnLocationInfo
            {
                get
                {
                    return _btnlocationInfo;
                }
            }

            /// <summary>
            /// The txtDocumentTitle item.
            /// </summary>
            [RepositoryItem("8b6306cd-c67f-4019-865b-ede12fa4b76f")]
            public virtual Ranorex.Text txtDocumentTitle
            {
                get
                {
                    return _txtdocumenttitleInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txtDocumentTitle item info.
            /// </summary>
            [RepositoryItemInfo("8b6306cd-c67f-4019-865b-ede12fa4b76f")]
            public virtual RepoItemInfo txtDocumentTitleInfo
            {
                get
                {
                    return _txtdocumenttitleInfo;
                }
            }

            /// <summary>
            /// The btnAddFile item.
            /// </summary>
            [RepositoryItem("67daa478-1860-44af-af9b-ff7680d070a0")]
            public virtual Ranorex.Button btnAddFile
            {
                get
                {
                    return _btnaddfileInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnAddFile item info.
            /// </summary>
            [RepositoryItemInfo("67daa478-1860-44af-af9b-ff7680d070a0")]
            public virtual RepoItemInfo btnAddFileInfo
            {
                get
                {
                    return _btnaddfileInfo;
                }
            }

            /// <summary>
            /// The btnOpen item.
            /// </summary>
            [RepositoryItem("9381130a-5871-4373-a637-1dd8e3b0a099")]
            public virtual Ranorex.Button btnOpen
            {
                get
                {
                    return _btnopenInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnOpen item info.
            /// </summary>
            [RepositoryItemInfo("9381130a-5871-4373-a637-1dd8e3b0a099")]
            public virtual RepoItemInfo btnOpenInfo
            {
                get
                {
                    return _btnopenInfo;
                }
            }

            /// <summary>
            /// The fileLocationPathText item.
            /// </summary>
            [RepositoryItem("f7beae1a-a1da-47fe-b07e-4cf7144b7c05")]
            public virtual Ranorex.Text fileLocationPathText
            {
                get
                {
                    return _filelocationpathtextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The fileLocationPathText item info.
            /// </summary>
            [RepositoryItemInfo("f7beae1a-a1da-47fe-b07e-4cf7144b7c05")]
            public virtual RepoItemInfo fileLocationPathTextInfo
            {
                get
                {
                    return _filelocationpathtextInfo;
                }
            }
        }

        /// <summary>
        /// The MenubarFillPanelFolder folder.
        /// </summary>
        [RepositoryFolder("e9762cdc-822d-4c50-aee0-d6911df09ecc")]
        public partial class MenubarFillPanelFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btndeleteInfo;
            RepoItemInfo _btnokInfo;
            RepoItemInfo _txtdocumentsummaryInfo;

            /// <summary>
            /// Creates a new MenubarFillPanel  folder.
            /// </summary>
            public MenubarFillPanelFolder(RepoGenBaseFolder parentFolder) :
                    base("MenubarFillPanel", "container[@controlname='menubar_Fill_Panel']", parentFolder, 30000, null, false, "e9762cdc-822d-4c50-aee0-d6911df09ecc", "")
            {
                _btndeleteInfo = new RepoItemInfo(this, "btnDelete", ".//toolbar[@accessiblename='Toolbar']/button[@accessiblename='Delete']", 30000, null, "3137c986-acc3-4850-b3cd-f73f6702baf3");
                _btnokInfo = new RepoItemInfo(this, "btnOK", ".//toolbar[@accessiblename='Toolbar']/button[@accessiblename='OK']", 30000, null, "7ecbc5bb-5909-40c1-843f-4a91ea1855fc");
                _txtdocumentsummaryInfo = new RepoItemInfo(this, "txtDocumentSummary", "container[@controlname='pnlBase']/?/?/container[@controlname='pnlBrad']/?/?/text[@controltypename='EmbeddableTextBoxWithUIPermissions']/text[@accessiblerole='Text']", 30000, null, "6f8399be-54ee-4866-992d-9b423768dbf7");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e9762cdc-822d-4c50-aee0-d6911df09ecc")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e9762cdc-822d-4c50-aee0-d6911df09ecc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btnDelete item.
            /// </summary>
            [RepositoryItem("3137c986-acc3-4850-b3cd-f73f6702baf3")]
            public virtual Ranorex.Button btnDelete
            {
                get
                {
                    return _btndeleteInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnDelete item info.
            /// </summary>
            [RepositoryItemInfo("3137c986-acc3-4850-b3cd-f73f6702baf3")]
            public virtual RepoItemInfo btnDeleteInfo
            {
                get
                {
                    return _btndeleteInfo;
                }
            }

            /// <summary>
            /// The btnOK item.
            /// </summary>
            [RepositoryItem("7ecbc5bb-5909-40c1-843f-4a91ea1855fc")]
            public virtual Ranorex.Button btnOK
            {
                get
                {
                    return _btnokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnOK item info.
            /// </summary>
            [RepositoryItemInfo("7ecbc5bb-5909-40c1-843f-4a91ea1855fc")]
            public virtual RepoItemInfo btnOKInfo
            {
                get
                {
                    return _btnokInfo;
                }
            }

            /// <summary>
            /// The txtDocumentSummary item.
            /// </summary>
            [RepositoryItem("6f8399be-54ee-4866-992d-9b423768dbf7")]
            public virtual Ranorex.Text txtDocumentSummary
            {
                get
                {
                    return _txtdocumentsummaryInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txtDocumentSummary item info.
            /// </summary>
            [RepositoryItemInfo("6f8399be-54ee-4866-992d-9b423768dbf7")]
            public virtual RepoItemInfo txtDocumentSummaryInfo
            {
                get
                {
                    return _txtdocumentsummaryInfo;
                }
            }
        }

        /// <summary>
        /// The OpenAppFolder folder.
        /// </summary>
        [RepositoryFolder("51eef256-da32-4f80-bddf-b71842b97b11")]
        public partial class OpenAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _linkdocumentsInfo;
            RepoItemInfo _listitemInfo;
            RepoItemInfo _btnopenInfo;

            /// <summary>
            /// Creates a new Open  folder.
            /// </summary>
            public OpenAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Open", "/form[@title='Open']", parentFolder, 30000, null, true, "51eef256-da32-4f80-bddf-b71842b97b11", "")
            {
                _linkdocumentsInfo = new RepoItemInfo(this, "linkDocuments", "element[@class='DUIViewWndClassName']/container/element[1]/?/?/tree[@controlid='100']//treeitem[@text='Documents']", 30000, null, "9f7cf95a-a585-42e3-95c4-cee108f15eb0");
                _listitemInfo = new RepoItemInfo(this, "listItem", "element[@class='DUIViewWndClassName']//container[@caption='ShellView']/?/?/listitem[@automationid='0']/text[@automationid='System.ItemNameDisplay']", 30000, null, "00aa1062-f87b-4faf-a344-d6fe15483eb3");
                _btnopenInfo = new RepoItemInfo(this, "btnOpen", "button[@text='&Open']", 30000, null, "b3317b5b-1ee6-4768-8a5c-1a2e440866c8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("51eef256-da32-4f80-bddf-b71842b97b11")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("51eef256-da32-4f80-bddf-b71842b97b11")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The linkDocuments item.
            /// </summary>
            [RepositoryItem("9f7cf95a-a585-42e3-95c4-cee108f15eb0")]
            public virtual Ranorex.TreeItem linkDocuments
            {
                get
                {
                    return _linkdocumentsInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The linkDocuments item info.
            /// </summary>
            [RepositoryItemInfo("9f7cf95a-a585-42e3-95c4-cee108f15eb0")]
            public virtual RepoItemInfo linkDocumentsInfo
            {
                get
                {
                    return _linkdocumentsInfo;
                }
            }

            /// <summary>
            /// The listItem item.
            /// </summary>
            [RepositoryItem("00aa1062-f87b-4faf-a344-d6fe15483eb3")]
            public virtual Ranorex.Text listItem
            {
                get
                {
                    return _listitemInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The listItem item info.
            /// </summary>
            [RepositoryItemInfo("00aa1062-f87b-4faf-a344-d6fe15483eb3")]
            public virtual RepoItemInfo listItemInfo
            {
                get
                {
                    return _listitemInfo;
                }
            }

            /// <summary>
            /// The btnOpen item.
            /// </summary>
            [RepositoryItem("b3317b5b-1ee6-4768-8a5c-1a2e440866c8")]
            public virtual Ranorex.Button btnOpen
            {
                get
                {
                    return _btnopenInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnOpen item info.
            /// </summary>
            [RepositoryItemInfo("b3317b5b-1ee6-4768-8a5c-1a2e440866c8")]
            public virtual RepoItemInfo btnOpenInfo
            {
                get
                {
                    return _btnopenInfo;
                }
            }
        }

        /// <summary>
        /// The FileSelectFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("b44a82d5-8e21-45bf-9c27-407befd88902")]
        public partial class FileSelectFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btnquickfindInfo;
            RepoItemInfo _listfirstfoundfileInfo;

            /// <summary>
            /// Creates a new FileSelectForm  folder.
            /// </summary>
            public FileSelectFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FileSelectForm", "/form[@controlname='FileSelectForm']", parentFolder, 30000, null, true, "b44a82d5-8e21-45bf-9c27-407befd88902", "")
            {
                _btnquickfindInfo = new RepoItemInfo(this, "btnQuickFind", ".//toolbar[@accessiblename='Toolbar']/button[@accessiblename='QuickFind']", 30000, null, "904efb63-44bf-4358-9532-7d94fbbf8f7a");
                _listfirstfoundfileInfo = new RepoItemInfo(this, "listFirstFoundFile", "container[@controlname='panel1']//row[@accessiblename='Band 0 row 1']/cell[@accessiblename='File']", 30000, null, "cdff6ec8-4ec8-41ad-8704-5a1d4c34061b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b44a82d5-8e21-45bf-9c27-407befd88902")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b44a82d5-8e21-45bf-9c27-407befd88902")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btnQuickFind item.
            /// </summary>
            [RepositoryItem("904efb63-44bf-4358-9532-7d94fbbf8f7a")]
            public virtual Ranorex.Button btnQuickFind
            {
                get
                {
                    return _btnquickfindInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnQuickFind item info.
            /// </summary>
            [RepositoryItemInfo("904efb63-44bf-4358-9532-7d94fbbf8f7a")]
            public virtual RepoItemInfo btnQuickFindInfo
            {
                get
                {
                    return _btnquickfindInfo;
                }
            }

            /// <summary>
            /// The listFirstFoundFile item.
            /// </summary>
            [RepositoryItem("cdff6ec8-4ec8-41ad-8704-5a1d4c34061b")]
            public virtual Ranorex.Cell listFirstFoundFile
            {
                get
                {
                    return _listfirstfoundfileInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The listFirstFoundFile item info.
            /// </summary>
            [RepositoryItemInfo("cdff6ec8-4ec8-41ad-8704-5a1d4c34061b")]
            public virtual RepoItemInfo listFirstFoundFileInfo
            {
                get
                {
                    return _listfirstfoundfileInfo;
                }
            }
        }

        /// <summary>
        /// The FindFilesFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("5b4e3fc8-de5d-4877-b8f5-e121f5c3053b")]
        public partial class FindFilesFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _txtfindfileInfo;
            RepoItemInfo _btnokInfo;

            /// <summary>
            /// Creates a new FindFilesForm  folder.
            /// </summary>
            public FindFilesFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FindFilesForm", "/form[@controlname='FindFilesForm']", parentFolder, 30000, null, true, "5b4e3fc8-de5d-4877-b8f5-e121f5c3053b", "")
            {
                _txtfindfileInfo = new RepoItemInfo(this, "txtFindFile", "container[@controlname='pnlBase']//text[@automationid='atxtSearch_EmbeddableTextBox']", 30000, null, "ca101bbd-bfee-4ebb-ac47-55bde64d4a10");
                _btnokInfo = new RepoItemInfo(this, "btnOK", ".//toolbar[@accessiblename='Toolbar']/button[@accessiblename='OK']", 30000, null, "ae2eab71-ec51-43d3-a510-974e9ec92e81");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5b4e3fc8-de5d-4877-b8f5-e121f5c3053b")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5b4e3fc8-de5d-4877-b8f5-e121f5c3053b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The txtFindFile item.
            /// </summary>
            [RepositoryItem("ca101bbd-bfee-4ebb-ac47-55bde64d4a10")]
            public virtual Ranorex.Text txtFindFile
            {
                get
                {
                    return _txtfindfileInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txtFindFile item info.
            /// </summary>
            [RepositoryItemInfo("ca101bbd-bfee-4ebb-ac47-55bde64d4a10")]
            public virtual RepoItemInfo txtFindFileInfo
            {
                get
                {
                    return _txtfindfileInfo;
                }
            }

            /// <summary>
            /// The btnOK item.
            /// </summary>
            [RepositoryItem("ae2eab71-ec51-43d3-a510-974e9ec92e81")]
            public virtual Ranorex.Button btnOK
            {
                get
                {
                    return _btnokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnOK item info.
            /// </summary>
            [RepositoryItemInfo("ae2eab71-ec51-43d3-a510-974e9ec92e81")]
            public virtual RepoItemInfo btnOKInfo
            {
                get
                {
                    return _btnokInfo;
                }
            }
        }

        /// <summary>
        /// The PromptFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("c4c663cf-05a9-4605-8631-0ff73c7a297e")]
        public partial class PromptFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btnokInfo;

            /// <summary>
            /// Creates a new PromptForm  folder.
            /// </summary>
            public PromptFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("PromptForm", "/form[@controlname='PromptForm']", parentFolder, 30000, null, true, "c4c663cf-05a9-4605-8631-0ff73c7a297e", "")
            {
                _btnokInfo = new RepoItemInfo(this, "btnOK", ".//toolbar[@accessiblename='Toolbar']/button[@accessiblename='OK']", 30000, null, "9db145b5-61b2-4bf9-92e0-9d40d85e4c7f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c4c663cf-05a9-4605-8631-0ff73c7a297e")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c4c663cf-05a9-4605-8631-0ff73c7a297e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btnOK item.
            /// </summary>
            [RepositoryItem("9db145b5-61b2-4bf9-92e0-9d40d85e4c7f")]
            public virtual Ranorex.Button btnOK
            {
                get
                {
                    return _btnokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnOK item info.
            /// </summary>
            [RepositoryItemInfo("9db145b5-61b2-4bf9-92e0-9d40d85e4c7f")]
            public virtual RepoItemInfo btnOKInfo
            {
                get
                {
                    return _btnokInfo;
                }
            }
        }

        /// <summary>
        /// The ProgressFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("ee3e8a9a-c406-48d6-b0bd-076c5ea5bd2b")]
        public partial class ProgressFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btncloseInfo;

            /// <summary>
            /// Creates a new ProgressForm  folder.
            /// </summary>
            public ProgressFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ProgressForm", "/form[@controlname='ProgressForm']", parentFolder, 30000, null, true, "ee3e8a9a-c406-48d6-b0bd-076c5ea5bd2b", "")
            {
                _btncloseInfo = new RepoItemInfo(this, "btnClose", "?/?/button[@accessiblename='Close']", 30000, null, "fb69b2a6-10b7-465e-893d-9f085e8fdc95");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ee3e8a9a-c406-48d6-b0bd-076c5ea5bd2b")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ee3e8a9a-c406-48d6-b0bd-076c5ea5bd2b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btnClose item.
            /// </summary>
            [RepositoryItem("fb69b2a6-10b7-465e-893d-9f085e8fdc95")]
            public virtual Ranorex.Button btnClose
            {
                get
                {
                    return _btncloseInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnClose item info.
            /// </summary>
            [RepositoryItemInfo("fb69b2a6-10b7-465e-893d-9f085e8fdc95")]
            public virtual RepoItemInfo btnCloseInfo
            {
                get
                {
                    return _btncloseInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
