///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace SmokeTest.Repositories
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MergeTemplates element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("a732d52e-ecb3-4057-a9a3-44e031d09052")]
    public partial class MergeTemplates : RepoGenBaseFolder
    {
        static MergeTemplates instance = new MergeTemplates();
        MergeTemplatesFolders.MainFormAppFolder _mainform;
        MergeTemplatesFolders.DocumentTemplateManagementFormAppFolder _documenttemplatemanagementform;

        /// <summary>
        /// Gets the singleton class instance representing the MergeTemplates element repository.
        /// </summary>
        [RepositoryFolder("a732d52e-ecb3-4057-a9a3-44e031d09052")]
        public static MergeTemplates Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MergeTemplates() 
            : base("MergeTemplates", "/", null, 0, false, "a732d52e-ecb3-4057-a9a3-44e031d09052", ".\\RepositoryImages\\MergeTemplatesa732d52e.rximgres")
        {
            _mainform = new MergeTemplatesFolders.MainFormAppFolder(this);
            _documenttemplatemanagementform = new MergeTemplatesFolders.DocumentTemplateManagementFormAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("a732d52e-ecb3-4057-a9a3-44e031d09052")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The MainForm folder.
        /// </summary>
        [RepositoryFolder("bc4675fd-6a1b-4c41-a21d-53bd5525b241")]
        public virtual MergeTemplatesFolders.MainFormAppFolder MainForm
        {
            get { return _mainform; }
        }

        /// <summary>
        /// The DocumentTemplateManagementForm folder.
        /// </summary>
        [RepositoryFolder("46a2429c-2d99-4bf8-8fca-7f116afedfd8")]
        public virtual MergeTemplatesFolders.DocumentTemplateManagementFormAppFolder DocumentTemplateManagementForm
        {
            get { return _documenttemplatemanagementform; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MergeTemplatesFolders
    {
        /// <summary>
        /// The MainFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("bc4675fd-6a1b-4c41-a21d-53bd5525b241")]
        public partial class MainFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _mergetemplatesInfo;

            /// <summary>
            /// Creates a new MainForm  folder.
            /// </summary>
            public MainFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MainForm", "/form[@controlname='MainForm']", parentFolder, 30000, null, true, "bc4675fd-6a1b-4c41-a21d-53bd5525b241", "")
            {
                _mergetemplatesInfo = new RepoItemInfo(this, "MergeTemplates", "container[@controlname='pLeft']//container[@controltypename='UltraExplorerBarContainerControl' and @instance='0']/container[@controlname='controlPanelWrapper']/container[@controlname='OfficeControlPanel']//container[@controltypename='Panel' and @instance='3']/?/?/text[@accessiblename='Merge Templates']", 30000, null, "2b77b641-3d84-41cc-b27f-51f402301341");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("bc4675fd-6a1b-4c41-a21d-53bd5525b241")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("bc4675fd-6a1b-4c41-a21d-53bd5525b241")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MergeTemplates item.
            /// </summary>
            [RepositoryItem("2b77b641-3d84-41cc-b27f-51f402301341")]
            public virtual Ranorex.Text MergeTemplates
            {
                get
                {
                    return _mergetemplatesInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The MergeTemplates item info.
            /// </summary>
            [RepositoryItemInfo("2b77b641-3d84-41cc-b27f-51f402301341")]
            public virtual RepoItemInfo MergeTemplatesInfo
            {
                get
                {
                    return _mergetemplatesInfo;
                }
            }
        }

        /// <summary>
        /// The DocumentTemplateManagementFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("46a2429c-2d99-4bf8-8fca-7f116afedfd8")]
        public partial class DocumentTemplateManagementFormAppFolder : RepoGenBaseFolder
        {
            MergeTemplatesFolders.Toolbar1Folder _toolbar1;
            MergeTemplatesFolders.PnlBaseFolder _pnlbase;
            RepoItemInfo _toolbarInfo;

            /// <summary>
            /// Creates a new DocumentTemplateManagementForm  folder.
            /// </summary>
            public DocumentTemplateManagementFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DocumentTemplateManagementForm", "/form[@controlname='DocumentTemplateManagementForm']", parentFolder, 30000, null, true, "46a2429c-2d99-4bf8-8fca-7f116afedfd8", "")
            {
                _toolbar1 = new MergeTemplatesFolders.Toolbar1Folder(this);
                _pnlbase = new MergeTemplatesFolders.PnlBaseFolder(this);
                _toolbarInfo = new RepoItemInfo(this, "Toolbar", "element[@controlname='_BaseForm_Toolbars_Dock_Area_Bottom']/?/?/toolbar[@accessiblename='Toolbar']", 30000, null, "c5f74ba9-67cb-4196-94f0-cef0ff8473ee");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("46a2429c-2d99-4bf8-8fca-7f116afedfd8")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("46a2429c-2d99-4bf8-8fca-7f116afedfd8")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Toolbar item.
            /// </summary>
            [RepositoryItem("c5f74ba9-67cb-4196-94f0-cef0ff8473ee")]
            public virtual Ranorex.ToolBar Toolbar
            {
                get
                {
                    return _toolbarInfo.CreateAdapter<Ranorex.ToolBar>(true);
                }
            }

            /// <summary>
            /// The Toolbar item info.
            /// </summary>
            [RepositoryItemInfo("c5f74ba9-67cb-4196-94f0-cef0ff8473ee")]
            public virtual RepoItemInfo ToolbarInfo
            {
                get
                {
                    return _toolbarInfo;
                }
            }

            /// <summary>
            /// The Toolbar1 folder.
            /// </summary>
            [RepositoryFolder("318b19fb-33d5-4b2e-b1fe-cfe071aad320")]
            public virtual MergeTemplatesFolders.Toolbar1Folder Toolbar1
            {
                get { return _toolbar1; }
            }

            /// <summary>
            /// The PnlBase folder.
            /// </summary>
            [RepositoryFolder("12d6bd78-6e9e-4ea9-aa3b-b1c83c22bb96")]
            public virtual MergeTemplatesFolders.PnlBaseFolder PnlBase
            {
                get { return _pnlbase; }
            }
        }

        /// <summary>
        /// The Toolbar1Folder folder.
        /// </summary>
        [RepositoryFolder("318b19fb-33d5-4b2e-b1fe-cfe071aad320")]
        public partial class Toolbar1Folder : RepoGenBaseFolder
        {
            RepoItemInfo _btncloseInfo;
            RepoItemInfo _btnprintInfo;

            /// <summary>
            /// Creates a new Toolbar1  folder.
            /// </summary>
            public Toolbar1Folder(RepoGenBaseFolder parentFolder) :
                    base("Toolbar1", ".//toolbar[@accessiblename='Toolbar']", parentFolder, 30000, null, false, "318b19fb-33d5-4b2e-b1fe-cfe071aad320", "")
            {
                _btncloseInfo = new RepoItemInfo(this, "btnClose", "button[@accessiblename='Close']", 30000, null, "91bba51b-7b19-4a43-a08f-02eadcd17cfa");
                _btnprintInfo = new RepoItemInfo(this, "btnPrint", "button[@accessiblename='Print']", 30000, null, "c29ab92e-0bd9-4040-b84f-38254e4c9215");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("318b19fb-33d5-4b2e-b1fe-cfe071aad320")]
            public virtual Ranorex.ToolBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ToolBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("318b19fb-33d5-4b2e-b1fe-cfe071aad320")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btnClose item.
            /// </summary>
            [RepositoryItem("91bba51b-7b19-4a43-a08f-02eadcd17cfa")]
            public virtual Ranorex.Button btnClose
            {
                get
                {
                    return _btncloseInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnClose item info.
            /// </summary>
            [RepositoryItemInfo("91bba51b-7b19-4a43-a08f-02eadcd17cfa")]
            public virtual RepoItemInfo btnCloseInfo
            {
                get
                {
                    return _btncloseInfo;
                }
            }

            /// <summary>
            /// The btnPrint item.
            /// </summary>
            [RepositoryItem("c29ab92e-0bd9-4040-b84f-38254e4c9215")]
            public virtual Ranorex.Button btnPrint
            {
                get
                {
                    return _btnprintInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnPrint item info.
            /// </summary>
            [RepositoryItemInfo("c29ab92e-0bd9-4040-b84f-38254e4c9215")]
            public virtual RepoItemInfo btnPrintInfo
            {
                get
                {
                    return _btnprintInfo;
                }
            }
        }

        /// <summary>
        /// The PnlBaseFolder folder.
        /// </summary>
        [RepositoryFolder("12d6bd78-6e9e-4ea9-aa3b-b1c83c22bb96")]
        public partial class PnlBaseFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btnedithotdocstemplateInfo;
            RepoItemInfo _btnlaunchhotdocsauthorInfo;
            RepoItemInfo _lnkstandardtemplatesInfo;
            RepoItemInfo _lnkhotdocsadvancetemplatesInfo;
            RepoItemInfo _tblhotdocsadvancetemplatesInfo;
            RepoItemInfo _treeoutlineInfo;
            RepoItemInfo _btnnewgroupInfo;
            RepoItemInfo _btnnewtemplateInfo;
            RepoItemInfo _btneditInfo;
            RepoItemInfo _btndeleteInfo;

            /// <summary>
            /// Creates a new PnlBase  folder.
            /// </summary>
            public PnlBaseFolder(RepoGenBaseFolder parentFolder) :
                    base("PnlBase", "container[@controlname='pnlBase']", parentFolder, 30000, null, false, "12d6bd78-6e9e-4ea9-aa3b-b1c83c22bb96", "")
            {
                _btnedithotdocstemplateInfo = new RepoItemInfo(this, "btnEditHotDocsTemplate", ".//button[@accessiblename='Edit HotDocs Template']", 30000, null, "71b434f3-4264-49b2-a955-d56a3b996676");
                _btnlaunchhotdocsauthorInfo = new RepoItemInfo(this, "btnLaunchHotDocsAuthor", ".//button[@accessiblename='Launch HotDocs Author']", 30000, null, "cd6f9808-d55a-4b40-b3c6-2946c177c583");
                _lnkstandardtemplatesInfo = new RepoItemInfo(this, "lnkStandardTemplates", "?/?/container[@controlname='dtvTemplates']/container[@controlname='pnlATC']//text[@accessiblename='Standard Templates']", 30000, null, "dc771ed5-7048-4a55-87c4-bd8d8511b339");
                _lnkhotdocsadvancetemplatesInfo = new RepoItemInfo(this, "lnkHotDocsAdvanceTemplates", "?/?/container[@controlname='dtvTemplates']/container[@controlname='pnlATC']//text[@accessiblename='HotDocs Advance Templates']", 30000, null, "1c6fc185-32a6-4dd7-b6e7-f4f96981125b");
                _tblhotdocsadvancetemplatesInfo = new RepoItemInfo(this, "tblHotDocsAdvanceTemplates", "?/?/container[@controlname='dtvTemplates']//table[@accessiblename='Band 0']", 30000, null, "8229667b-30e3-4b5e-9bcc-b55ceb909b3a");
                _treeoutlineInfo = new RepoItemInfo(this, "treeOutline", "?/?/container[@controlname='dtvTemplates']/container[@controlname='pnlStandard']//tree[@accessiblerole='Outline']", 30000, null, "ae0d8756-3ae2-420f-b228-308430ac4156");
                _btnnewgroupInfo = new RepoItemInfo(this, "btnNewGroup", ".//button[@accessiblename='New Group']", 30000, null, "8ccbd1fa-eec3-4174-a34f-f961a463838f");
                _btnnewtemplateInfo = new RepoItemInfo(this, "btnNewTemplate", ".//button[@accessiblename='New Template']", 30000, null, "d9e15d19-7d03-4714-83cc-c0cde8fb4bcd");
                _btneditInfo = new RepoItemInfo(this, "btnEdit", ".//button[@accessiblename='Edit']", 30000, null, "732af732-1bc5-499d-af3e-0e6d82e71d51");
                _btndeleteInfo = new RepoItemInfo(this, "btnDelete", ".//button[@accessiblename='Delete']", 30000, null, "0941b25d-2cc7-4b45-974d-6e78ef329a00");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("12d6bd78-6e9e-4ea9-aa3b-b1c83c22bb96")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("12d6bd78-6e9e-4ea9-aa3b-b1c83c22bb96")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btnEditHotDocsTemplate item.
            /// </summary>
            [RepositoryItem("71b434f3-4264-49b2-a955-d56a3b996676")]
            public virtual Ranorex.Button btnEditHotDocsTemplate
            {
                get
                {
                    return _btnedithotdocstemplateInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnEditHotDocsTemplate item info.
            /// </summary>
            [RepositoryItemInfo("71b434f3-4264-49b2-a955-d56a3b996676")]
            public virtual RepoItemInfo btnEditHotDocsTemplateInfo
            {
                get
                {
                    return _btnedithotdocstemplateInfo;
                }
            }

            /// <summary>
            /// The btnLaunchHotDocsAuthor item.
            /// </summary>
            [RepositoryItem("cd6f9808-d55a-4b40-b3c6-2946c177c583")]
            public virtual Ranorex.Button btnLaunchHotDocsAuthor
            {
                get
                {
                    return _btnlaunchhotdocsauthorInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnLaunchHotDocsAuthor item info.
            /// </summary>
            [RepositoryItemInfo("cd6f9808-d55a-4b40-b3c6-2946c177c583")]
            public virtual RepoItemInfo btnLaunchHotDocsAuthorInfo
            {
                get
                {
                    return _btnlaunchhotdocsauthorInfo;
                }
            }

            /// <summary>
            /// The lnkStandardTemplates item.
            /// </summary>
            [RepositoryItem("dc771ed5-7048-4a55-87c4-bd8d8511b339")]
            public virtual Ranorex.Text lnkStandardTemplates
            {
                get
                {
                    return _lnkstandardtemplatesInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The lnkStandardTemplates item info.
            /// </summary>
            [RepositoryItemInfo("dc771ed5-7048-4a55-87c4-bd8d8511b339")]
            public virtual RepoItemInfo lnkStandardTemplatesInfo
            {
                get
                {
                    return _lnkstandardtemplatesInfo;
                }
            }

            /// <summary>
            /// The lnkHotDocsAdvanceTemplates item.
            /// </summary>
            [RepositoryItem("1c6fc185-32a6-4dd7-b6e7-f4f96981125b")]
            public virtual Ranorex.Text lnkHotDocsAdvanceTemplates
            {
                get
                {
                    return _lnkhotdocsadvancetemplatesInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The lnkHotDocsAdvanceTemplates item info.
            /// </summary>
            [RepositoryItemInfo("1c6fc185-32a6-4dd7-b6e7-f4f96981125b")]
            public virtual RepoItemInfo lnkHotDocsAdvanceTemplatesInfo
            {
                get
                {
                    return _lnkhotdocsadvancetemplatesInfo;
                }
            }

            /// <summary>
            /// The tblHotDocsAdvanceTemplates item.
            /// </summary>
            [RepositoryItem("8229667b-30e3-4b5e-9bcc-b55ceb909b3a")]
            public virtual Ranorex.Table tblHotDocsAdvanceTemplates
            {
                get
                {
                    return _tblhotdocsadvancetemplatesInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The tblHotDocsAdvanceTemplates item info.
            /// </summary>
            [RepositoryItemInfo("8229667b-30e3-4b5e-9bcc-b55ceb909b3a")]
            public virtual RepoItemInfo tblHotDocsAdvanceTemplatesInfo
            {
                get
                {
                    return _tblhotdocsadvancetemplatesInfo;
                }
            }

            /// <summary>
            /// The treeOutline item.
            /// </summary>
            [RepositoryItem("ae0d8756-3ae2-420f-b228-308430ac4156")]
            public virtual Ranorex.Tree treeOutline
            {
                get
                {
                    return _treeoutlineInfo.CreateAdapter<Ranorex.Tree>(true);
                }
            }

            /// <summary>
            /// The treeOutline item info.
            /// </summary>
            [RepositoryItemInfo("ae0d8756-3ae2-420f-b228-308430ac4156")]
            public virtual RepoItemInfo treeOutlineInfo
            {
                get
                {
                    return _treeoutlineInfo;
                }
            }

            /// <summary>
            /// The btnNewGroup item.
            /// </summary>
            [RepositoryItem("8ccbd1fa-eec3-4174-a34f-f961a463838f")]
            public virtual Ranorex.Button btnNewGroup
            {
                get
                {
                    return _btnnewgroupInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnNewGroup item info.
            /// </summary>
            [RepositoryItemInfo("8ccbd1fa-eec3-4174-a34f-f961a463838f")]
            public virtual RepoItemInfo btnNewGroupInfo
            {
                get
                {
                    return _btnnewgroupInfo;
                }
            }

            /// <summary>
            /// The btnNewTemplate item.
            /// </summary>
            [RepositoryItem("d9e15d19-7d03-4714-83cc-c0cde8fb4bcd")]
            public virtual Ranorex.Button btnNewTemplate
            {
                get
                {
                    return _btnnewtemplateInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnNewTemplate item info.
            /// </summary>
            [RepositoryItemInfo("d9e15d19-7d03-4714-83cc-c0cde8fb4bcd")]
            public virtual RepoItemInfo btnNewTemplateInfo
            {
                get
                {
                    return _btnnewtemplateInfo;
                }
            }

            /// <summary>
            /// The btnEdit item.
            /// </summary>
            [RepositoryItem("732af732-1bc5-499d-af3e-0e6d82e71d51")]
            public virtual Ranorex.Button btnEdit
            {
                get
                {
                    return _btneditInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnEdit item info.
            /// </summary>
            [RepositoryItemInfo("732af732-1bc5-499d-af3e-0e6d82e71d51")]
            public virtual RepoItemInfo btnEditInfo
            {
                get
                {
                    return _btneditInfo;
                }
            }

            /// <summary>
            /// The btnDelete item.
            /// </summary>
            [RepositoryItem("0941b25d-2cc7-4b45-974d-6e78ef329a00")]
            public virtual Ranorex.Button btnDelete
            {
                get
                {
                    return _btndeleteInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnDelete item info.
            /// </summary>
            [RepositoryItemInfo("0941b25d-2cc7-4b45-974d-6e78ef329a00")]
            public virtual RepoItemInfo btnDeleteInfo
            {
                get
                {
                    return _btndeleteInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
