///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace SmokeTest.Repositories
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Note element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("de38a076-8e47-4455-9a53-8e9f6218336a")]
    public partial class Note : RepoGenBaseFolder
    {
        static Note instance = new Note();
        NoteFolders.MainFormAppFolder _mainform;
        NoteFolders.PeopleSelectFormAppFolder _peopleselectform;
        NoteFolders.StickyDetailsAppFolder _stickydetails;
        NoteFolders.FindFilesFormAppFolder _findfilesform;
        NoteFolders.FileSelectFormAppFolder _fileselectform;
        NoteFolders.NoteDetailAppFolder _notedetail;
        NoteFolders.PromptFormAppFolder _promptform;

        /// <summary>
        /// Gets the singleton class instance representing the Note element repository.
        /// </summary>
        [RepositoryFolder("de38a076-8e47-4455-9a53-8e9f6218336a")]
        public static Note Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Note() 
            : base("Note", "/", null, 0, false, "de38a076-8e47-4455-9a53-8e9f6218336a", ".\\RepositoryImages\\Notede38a076.rximgres")
        {
            _mainform = new NoteFolders.MainFormAppFolder(this);
            _peopleselectform = new NoteFolders.PeopleSelectFormAppFolder(this);
            _stickydetails = new NoteFolders.StickyDetailsAppFolder(this);
            _findfilesform = new NoteFolders.FindFilesFormAppFolder(this);
            _fileselectform = new NoteFolders.FileSelectFormAppFolder(this);
            _notedetail = new NoteFolders.NoteDetailAppFolder(this);
            _promptform = new NoteFolders.PromptFormAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("de38a076-8e47-4455-9a53-8e9f6218336a")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The MainForm folder.
        /// </summary>
        [RepositoryFolder("23762e79-ae30-4042-a701-23ee08bc77d2")]
        public virtual NoteFolders.MainFormAppFolder MainForm
        {
            get { return _mainform; }
        }

        /// <summary>
        /// The PeopleSelectForm folder.
        /// </summary>
        [RepositoryFolder("b1f4cf85-db15-43b9-8e57-af6ede980ec3")]
        public virtual NoteFolders.PeopleSelectFormAppFolder PeopleSelectForm
        {
            get { return _peopleselectform; }
        }

        /// <summary>
        /// The StickyDetails folder.
        /// </summary>
        [RepositoryFolder("07c60877-cbb9-44e9-be99-6ca1a0f4f5c4")]
        public virtual NoteFolders.StickyDetailsAppFolder StickyDetails
        {
            get { return _stickydetails; }
        }

        /// <summary>
        /// The FindFilesForm folder.
        /// </summary>
        [RepositoryFolder("9c1043e8-ccb4-4e0b-9ae1-ffdf053c6795")]
        public virtual NoteFolders.FindFilesFormAppFolder FindFilesForm
        {
            get { return _findfilesform; }
        }

        /// <summary>
        /// The FileSelectForm folder.
        /// </summary>
        [RepositoryFolder("d2b12fce-5506-4dc1-b058-8f628f54b120")]
        public virtual NoteFolders.FileSelectFormAppFolder FileSelectForm
        {
            get { return _fileselectform; }
        }

        /// <summary>
        /// The NoteDetail folder.
        /// </summary>
        [RepositoryFolder("01b7c8aa-6d22-4050-b6b8-bdc0607327c4")]
        public virtual NoteFolders.NoteDetailAppFolder NoteDetail
        {
            get { return _notedetail; }
        }

        /// <summary>
        /// The PromptForm folder.
        /// </summary>
        [RepositoryFolder("87c7bfbf-a3c5-4b39-a16a-b3b081bebf61")]
        public virtual NoteFolders.PromptFormAppFolder PromptForm
        {
            get { return _promptform; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class NoteFolders
    {
        /// <summary>
        /// The MainFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("23762e79-ae30-4042-a701-23ee08bc77d2")]
        public partial class MainFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btnnotesInfo;
            RepoItemInfo _btnnewstickyInfo;
            RepoItemInfo _listnoteoneInfo;
            RepoItemInfo _selecttodayInfo;
            RepoItemInfo _btnnotes1Info;

            /// <summary>
            /// Creates a new MainForm  folder.
            /// </summary>
            public MainFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MainForm", "/form[@controlname='MainForm']", parentFolder, 30000, null, true, "23762e79-ae30-4042-a701-23ee08bc77d2", "")
            {
                _btnnotesInfo = new RepoItemInfo(this, "btnNotes", "container[@controlname='pLeft']//tree[@accessiblerole='Outline']/button[@accessiblename='Notes']", 30000, null, "ac425c30-405d-4fac-9c3a-1bb0462df3e3");
                _btnnewstickyInfo = new RepoItemInfo(this, "btnNewSticky", "?/?/form[@controlname='NotesIndexForm']/container[@controlname='menubar_Fill_Panel']//toolbar[@accessiblename='Toolbar']/button[@accessiblename='Sticky']", 30000, null, "ab21e8d1-614f-4c13-a0d1-8d4413c296aa");
                _listnoteoneInfo = new RepoItemInfo(this, "listNoteOne", "?/?/form[@controlname='NotesIndexForm']/container[@controlname='pnlBase']/?/?/table/row[1]/cell[@accessiblename='Author']", 30000, null, "efa081ba-2fb6-47e3-af0b-ec5f5dbae3c4");
                _selecttodayInfo = new RepoItemInfo(this, "selectToday", "container[@controlname='pLeft']//container[@controltypename='UltraExplorerBarContainerControl' and @instance='0']/?/?/container[@controlname='NotesIndexControlPanelControl']/container[@controlname='panel3']/container[@controlname='atcUnassociatedOrToday']//text[@accessiblename='Today']", 30000, null, "b1f6da12-b83c-42a6-b95d-7f7100959747");
                _btnnotes1Info = new RepoItemInfo(this, "btnNotes1", "?/?/tree[@accessiblerole='Outline']/button[@accessiblename='Notes']", 5000, null, "299830ba-e506-40a2-bb3e-b0d076b5784e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("23762e79-ae30-4042-a701-23ee08bc77d2")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("23762e79-ae30-4042-a701-23ee08bc77d2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btnNotes item.
            /// </summary>
            [RepositoryItem("ac425c30-405d-4fac-9c3a-1bb0462df3e3")]
            public virtual Ranorex.Button btnNotes
            {
                get
                {
                    return _btnnotesInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnNotes item info.
            /// </summary>
            [RepositoryItemInfo("ac425c30-405d-4fac-9c3a-1bb0462df3e3")]
            public virtual RepoItemInfo btnNotesInfo
            {
                get
                {
                    return _btnnotesInfo;
                }
            }

            /// <summary>
            /// The btnNewSticky item.
            /// </summary>
            [RepositoryItem("ab21e8d1-614f-4c13-a0d1-8d4413c296aa")]
            public virtual Ranorex.Button btnNewSticky
            {
                get
                {
                    return _btnnewstickyInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnNewSticky item info.
            /// </summary>
            [RepositoryItemInfo("ab21e8d1-614f-4c13-a0d1-8d4413c296aa")]
            public virtual RepoItemInfo btnNewStickyInfo
            {
                get
                {
                    return _btnnewstickyInfo;
                }
            }

            /// <summary>
            /// The listNoteOne item.
            /// </summary>
            [RepositoryItem("efa081ba-2fb6-47e3-af0b-ec5f5dbae3c4")]
            public virtual Ranorex.Cell listNoteOne
            {
                get
                {
                    return _listnoteoneInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The listNoteOne item info.
            /// </summary>
            [RepositoryItemInfo("efa081ba-2fb6-47e3-af0b-ec5f5dbae3c4")]
            public virtual RepoItemInfo listNoteOneInfo
            {
                get
                {
                    return _listnoteoneInfo;
                }
            }

            /// <summary>
            /// The selectToday item.
            /// </summary>
            [RepositoryItem("b1f6da12-b83c-42a6-b95d-7f7100959747")]
            public virtual Ranorex.Text selectToday
            {
                get
                {
                    return _selecttodayInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The selectToday item info.
            /// </summary>
            [RepositoryItemInfo("b1f6da12-b83c-42a6-b95d-7f7100959747")]
            public virtual RepoItemInfo selectTodayInfo
            {
                get
                {
                    return _selecttodayInfo;
                }
            }

            /// <summary>
            /// The btnNotes1 item.
            /// </summary>
            [RepositoryItem("299830ba-e506-40a2-bb3e-b0d076b5784e")]
            public virtual Ranorex.Button btnNotes1
            {
                get
                {
                    return _btnnotes1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnNotes1 item info.
            /// </summary>
            [RepositoryItemInfo("299830ba-e506-40a2-bb3e-b0d076b5784e")]
            public virtual RepoItemInfo btnNotes1Info
            {
                get
                {
                    return _btnnotes1Info;
                }
            }
        }

        /// <summary>
        /// The PeopleSelectFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("b1f4cf85-db15-43b9-8e57-af6ede980ec3")]
        public partial class PeopleSelectFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _txtnameInfo;
            RepoItemInfo _btnaddtorightInfo;
            RepoItemInfo _btnokInfo;
            RepoItemInfo _listnameoneInfo;

            /// <summary>
            /// Creates a new PeopleSelectForm  folder.
            /// </summary>
            public PeopleSelectFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("PeopleSelectForm", "/form[@controlname='PeopleSelectForm']", parentFolder, 30000, null, true, "b1f4cf85-db15-43b9-8e57-af6ede980ec3", "")
            {
                _txtnameInfo = new RepoItemInfo(this, "txtName", "container[@controlname='pnlBase']//container[@controlname='panel']/element[@controlname='uteSearch']/?/?/text[@accessiblerole='Text']", 30000, null, "e2b51411-ba38-4b1b-93de-4b2d4aa1fba7");
                _btnaddtorightInfo = new RepoItemInfo(this, "btnAddToRight", "container[@controlname='panel1']/?/?/button[@accessiblename='>']", 30000, null, "308fb4fb-edd9-4492-a7ac-9e8bcc7c62b1");
                _btnokInfo = new RepoItemInfo(this, "btnOK", ".//toolbar[@accessiblename='Toolbar']/button[@accessiblename='OK']", 30000, null, "3813598d-42f5-4ae2-b41e-95efcf98c79f");
                _listnameoneInfo = new RepoItemInfo(this, "listNameOne", "container[@controlname='panel1']//row[@accessiblename='Band 0 row 1']/cell[@accessiblename='Name']", 30000, null, "ba1dcbfa-a709-4daa-80e9-13da200c8d00");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b1f4cf85-db15-43b9-8e57-af6ede980ec3")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b1f4cf85-db15-43b9-8e57-af6ede980ec3")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The txtName item.
            /// </summary>
            [RepositoryItem("e2b51411-ba38-4b1b-93de-4b2d4aa1fba7")]
            public virtual Ranorex.Text txtName
            {
                get
                {
                    return _txtnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txtName item info.
            /// </summary>
            [RepositoryItemInfo("e2b51411-ba38-4b1b-93de-4b2d4aa1fba7")]
            public virtual RepoItemInfo txtNameInfo
            {
                get
                {
                    return _txtnameInfo;
                }
            }

            /// <summary>
            /// The btnAddToRight item.
            /// </summary>
            [RepositoryItem("308fb4fb-edd9-4492-a7ac-9e8bcc7c62b1")]
            public virtual Ranorex.Button btnAddToRight
            {
                get
                {
                    return _btnaddtorightInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnAddToRight item info.
            /// </summary>
            [RepositoryItemInfo("308fb4fb-edd9-4492-a7ac-9e8bcc7c62b1")]
            public virtual RepoItemInfo btnAddToRightInfo
            {
                get
                {
                    return _btnaddtorightInfo;
                }
            }

            /// <summary>
            /// The btnOK item.
            /// </summary>
            [RepositoryItem("3813598d-42f5-4ae2-b41e-95efcf98c79f")]
            public virtual Ranorex.Button btnOK
            {
                get
                {
                    return _btnokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnOK item info.
            /// </summary>
            [RepositoryItemInfo("3813598d-42f5-4ae2-b41e-95efcf98c79f")]
            public virtual RepoItemInfo btnOKInfo
            {
                get
                {
                    return _btnokInfo;
                }
            }

            /// <summary>
            /// The listNameOne item.
            /// </summary>
            [RepositoryItem("ba1dcbfa-a709-4daa-80e9-13da200c8d00")]
            public virtual Ranorex.Cell listNameOne
            {
                get
                {
                    return _listnameoneInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The listNameOne item info.
            /// </summary>
            [RepositoryItemInfo("ba1dcbfa-a709-4daa-80e9-13da200c8d00")]
            public virtual RepoItemInfo listNameOneInfo
            {
                get
                {
                    return _listnameoneInfo;
                }
            }
        }

        /// <summary>
        /// The StickyDetailsAppFolder folder.
        /// </summary>
        [RepositoryFolder("07c60877-cbb9-44e9-be99-6ca1a0f4f5c4")]
        public partial class StickyDetailsAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btnaddfileInfo;
            RepoItemInfo _txtnoteboxInfo;
            RepoItemInfo _btnsendInfo;
            RepoItemInfo _btncancelInfo;
            RepoItemInfo _btncloseInfo;

            /// <summary>
            /// Creates a new StickyDetails  folder.
            /// </summary>
            public StickyDetailsAppFolder(RepoGenBaseFolder parentFolder) :
                    base("StickyDetails", "/form[@controlname='StickyDetails']", parentFolder, 30000, null, true, "07c60877-cbb9-44e9-be99-6ca1a0f4f5c4", "")
            {
                _btnaddfileInfo = new RepoItemInfo(this, "btnAddFile", "container[@controlname='StickyDetails_Fill_Panel']//button[@accessiblerole='PushButton']", 30000, null, "b45e18a3-5bc6-4639-aaeb-aaf8384a41b7");
                _txtnoteboxInfo = new RepoItemInfo(this, "txtNoteBox", "container[@controlname='StickyDetails_Fill_Panel']/element[@controlname='uteStickyMessage']/text[@controltypename='EmbeddableTextBoxWithUIPermissions']/text[@accessiblerole='Text']", 30000, null, "f5d7c246-dc66-4469-94d9-aec2222e94d5");
                _btnsendInfo = new RepoItemInfo(this, "btnSend", ".//toolbar[@accessiblename='Toolbar']/button[@accessiblename='Send ']", 30000, null, "d4bdb645-bc3a-4fd0-806f-9f28dca21c4c");
                _btncancelInfo = new RepoItemInfo(this, "btnCancel", ".//toolbar[@accessiblename='Toolbar']/button[@accessiblename='Cancel']", 30000, null, "c6686988-a147-4cf9-8f12-40e2da978d8f");
                _btncloseInfo = new RepoItemInfo(this, "btnClose", ".//toolbar[@accessiblename='Toolbar']/button[@accessiblename='Close']", 5000, null, "b30f9104-7ff2-447b-b600-ae39c897490c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("07c60877-cbb9-44e9-be99-6ca1a0f4f5c4")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("07c60877-cbb9-44e9-be99-6ca1a0f4f5c4")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btnAddFile item.
            /// </summary>
            [RepositoryItem("b45e18a3-5bc6-4639-aaeb-aaf8384a41b7")]
            public virtual Ranorex.Button btnAddFile
            {
                get
                {
                    return _btnaddfileInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnAddFile item info.
            /// </summary>
            [RepositoryItemInfo("b45e18a3-5bc6-4639-aaeb-aaf8384a41b7")]
            public virtual RepoItemInfo btnAddFileInfo
            {
                get
                {
                    return _btnaddfileInfo;
                }
            }

            /// <summary>
            /// The txtNoteBox item.
            /// </summary>
            [RepositoryItem("f5d7c246-dc66-4469-94d9-aec2222e94d5")]
            public virtual Ranorex.Text txtNoteBox
            {
                get
                {
                    return _txtnoteboxInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txtNoteBox item info.
            /// </summary>
            [RepositoryItemInfo("f5d7c246-dc66-4469-94d9-aec2222e94d5")]
            public virtual RepoItemInfo txtNoteBoxInfo
            {
                get
                {
                    return _txtnoteboxInfo;
                }
            }

            /// <summary>
            /// The btnSend item.
            /// </summary>
            [RepositoryItem("d4bdb645-bc3a-4fd0-806f-9f28dca21c4c")]
            public virtual Ranorex.Button btnSend
            {
                get
                {
                    return _btnsendInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnSend item info.
            /// </summary>
            [RepositoryItemInfo("d4bdb645-bc3a-4fd0-806f-9f28dca21c4c")]
            public virtual RepoItemInfo btnSendInfo
            {
                get
                {
                    return _btnsendInfo;
                }
            }

            /// <summary>
            /// The btnCancel item.
            /// </summary>
            [RepositoryItem("c6686988-a147-4cf9-8f12-40e2da978d8f")]
            public virtual Ranorex.Button btnCancel
            {
                get
                {
                    return _btncancelInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnCancel item info.
            /// </summary>
            [RepositoryItemInfo("c6686988-a147-4cf9-8f12-40e2da978d8f")]
            public virtual RepoItemInfo btnCancelInfo
            {
                get
                {
                    return _btncancelInfo;
                }
            }

            /// <summary>
            /// The btnClose item.
            /// </summary>
            [RepositoryItem("b30f9104-7ff2-447b-b600-ae39c897490c")]
            public virtual Ranorex.Button btnClose
            {
                get
                {
                    return _btncloseInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnClose item info.
            /// </summary>
            [RepositoryItemInfo("b30f9104-7ff2-447b-b600-ae39c897490c")]
            public virtual RepoItemInfo btnCloseInfo
            {
                get
                {
                    return _btncloseInfo;
                }
            }
        }

        /// <summary>
        /// The FindFilesFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("9c1043e8-ccb4-4e0b-9ae1-ffdf053c6795")]
        public partial class FindFilesFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _txtfindfileInfo;
            RepoItemInfo _btnokInfo;

            /// <summary>
            /// Creates a new FindFilesForm  folder.
            /// </summary>
            public FindFilesFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FindFilesForm", "/form[@controlname='FindFilesForm']", parentFolder, 30000, null, true, "9c1043e8-ccb4-4e0b-9ae1-ffdf053c6795", "")
            {
                _txtfindfileInfo = new RepoItemInfo(this, "txtFindFile", "container[@controlname='pnlBase']//text[@automationid='atxtSearch_EmbeddableTextBox']", 30000, null, "1b6ffcb0-2d71-4b3b-b8bd-ede40ae97191");
                _btnokInfo = new RepoItemInfo(this, "btnOK", ".//toolbar[@accessiblename='Toolbar']/button[@accessiblename='OK']", 30000, null, "252322fc-06e2-4b0d-a7e2-fc771cd58c60");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9c1043e8-ccb4-4e0b-9ae1-ffdf053c6795")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9c1043e8-ccb4-4e0b-9ae1-ffdf053c6795")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The txtFindFile item.
            /// </summary>
            [RepositoryItem("1b6ffcb0-2d71-4b3b-b8bd-ede40ae97191")]
            public virtual Ranorex.Text txtFindFile
            {
                get
                {
                    return _txtfindfileInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txtFindFile item info.
            /// </summary>
            [RepositoryItemInfo("1b6ffcb0-2d71-4b3b-b8bd-ede40ae97191")]
            public virtual RepoItemInfo txtFindFileInfo
            {
                get
                {
                    return _txtfindfileInfo;
                }
            }

            /// <summary>
            /// The btnOK item.
            /// </summary>
            [RepositoryItem("252322fc-06e2-4b0d-a7e2-fc771cd58c60")]
            public virtual Ranorex.Button btnOK
            {
                get
                {
                    return _btnokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnOK item info.
            /// </summary>
            [RepositoryItemInfo("252322fc-06e2-4b0d-a7e2-fc771cd58c60")]
            public virtual RepoItemInfo btnOKInfo
            {
                get
                {
                    return _btnokInfo;
                }
            }
        }

        /// <summary>
        /// The FileSelectFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("d2b12fce-5506-4dc1-b058-8f628f54b120")]
        public partial class FileSelectFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _filelistitemoneInfo;
            RepoItemInfo _btnquickfindInfo;
            RepoItemInfo _btnokInfo;

            /// <summary>
            /// Creates a new FileSelectForm  folder.
            /// </summary>
            public FileSelectFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FileSelectForm", "/form[@controlname='FileSelectForm']", parentFolder, 30000, null, true, "d2b12fce-5506-4dc1-b058-8f628f54b120", "")
            {
                _filelistitemoneInfo = new RepoItemInfo(this, "fileListItemOne", "container[@controlname='panel1']//row[@accessiblename='Band 0 row 1']/cell[@accessiblename='File']", 30000, null, "e7fb53b7-5a9a-4e55-80dc-2fd8fa9ecaee");
                _btnquickfindInfo = new RepoItemInfo(this, "btnQuickFind", ".//toolbar[@accessiblename='Toolbar']/button[@accessiblename='QuickFind']", 30000, null, "2a856528-dd0f-4460-8153-22f9af1f4867");
                _btnokInfo = new RepoItemInfo(this, "btnOK", ".//toolbar[@accessiblename='Toolbar']/button[@accessiblename='OK']", 30000, null, "9fc53555-2474-4cd2-887e-74ec5fcdf282");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d2b12fce-5506-4dc1-b058-8f628f54b120")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d2b12fce-5506-4dc1-b058-8f628f54b120")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The fileListItemOne item.
            /// </summary>
            [RepositoryItem("e7fb53b7-5a9a-4e55-80dc-2fd8fa9ecaee")]
            public virtual Ranorex.Cell fileListItemOne
            {
                get
                {
                    return _filelistitemoneInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The fileListItemOne item info.
            /// </summary>
            [RepositoryItemInfo("e7fb53b7-5a9a-4e55-80dc-2fd8fa9ecaee")]
            public virtual RepoItemInfo fileListItemOneInfo
            {
                get
                {
                    return _filelistitemoneInfo;
                }
            }

            /// <summary>
            /// The btnQuickFind item.
            /// </summary>
            [RepositoryItem("2a856528-dd0f-4460-8153-22f9af1f4867")]
            public virtual Ranorex.Button btnQuickFind
            {
                get
                {
                    return _btnquickfindInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnQuickFind item info.
            /// </summary>
            [RepositoryItemInfo("2a856528-dd0f-4460-8153-22f9af1f4867")]
            public virtual RepoItemInfo btnQuickFindInfo
            {
                get
                {
                    return _btnquickfindInfo;
                }
            }

            /// <summary>
            /// The btnOK item.
            /// </summary>
            [RepositoryItem("9fc53555-2474-4cd2-887e-74ec5fcdf282")]
            public virtual Ranorex.Button btnOK
            {
                get
                {
                    return _btnokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnOK item info.
            /// </summary>
            [RepositoryItemInfo("9fc53555-2474-4cd2-887e-74ec5fcdf282")]
            public virtual RepoItemInfo btnOKInfo
            {
                get
                {
                    return _btnokInfo;
                }
            }
        }

        /// <summary>
        /// The NoteDetailAppFolder folder.
        /// </summary>
        [RepositoryFolder("01b7c8aa-6d22-4050-b6b8-bdc0607327c4")]
        public partial class NoteDetailAppFolder : RepoGenBaseFolder
        {
            NoteFolders.MenubarFillPanelFolder _menubarfillpanel;

            /// <summary>
            /// Creates a new NoteDetail  folder.
            /// </summary>
            public NoteDetailAppFolder(RepoGenBaseFolder parentFolder) :
                    base("NoteDetail", "/form[@controlname='NoteDetail']", parentFolder, 30000, null, true, "01b7c8aa-6d22-4050-b6b8-bdc0607327c4", "")
            {
                _menubarfillpanel = new NoteFolders.MenubarFillPanelFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("01b7c8aa-6d22-4050-b6b8-bdc0607327c4")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("01b7c8aa-6d22-4050-b6b8-bdc0607327c4")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MenubarFillPanel folder.
            /// </summary>
            [RepositoryFolder("70fd598f-8922-4c70-aa85-1e64445fd365")]
            public virtual NoteFolders.MenubarFillPanelFolder MenubarFillPanel
            {
                get { return _menubarfillpanel; }
            }
        }

        /// <summary>
        /// The MenubarFillPanelFolder folder.
        /// </summary>
        [RepositoryFolder("70fd598f-8922-4c70-aa85-1e64445fd365")]
        public partial class MenubarFillPanelFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btndeleteInfo;
            RepoItemInfo _btnokInfo;
            RepoItemInfo _txtnoteboxeditInfo;
            RepoItemInfo _btncancelInfo;

            /// <summary>
            /// Creates a new MenubarFillPanel  folder.
            /// </summary>
            public MenubarFillPanelFolder(RepoGenBaseFolder parentFolder) :
                    base("MenubarFillPanel", "container[@controlname='menubar_Fill_Panel']", parentFolder, 30000, null, false, "70fd598f-8922-4c70-aa85-1e64445fd365", "")
            {
                _btndeleteInfo = new RepoItemInfo(this, "btnDelete", ".//toolbar[@accessiblename='Toolbar']/button[@accessiblename='Delete']", 30000, null, "5b0e9486-f8e8-4814-ae23-40c3bea4e0b8");
                _btnokInfo = new RepoItemInfo(this, "btnOK", ".//toolbar[@accessiblename='Toolbar']/button[@accessiblename='OK']", 30000, null, "141b0bb0-b074-4844-9f1f-db03c7ee34ec");
                _txtnoteboxeditInfo = new RepoItemInfo(this, "txtNoteBoxEdit", "container[@controlname='pnlBase']/?/?/container[@controlname='panelNoteDetail']/?/?/text[@controltypename='EmbeddableTextBoxWithUIPermissions']/text[@accessiblerole='Text']", 30000, null, "eb5a9a15-69d5-4869-8532-9f7bdb46d0f9");
                _btncancelInfo = new RepoItemInfo(this, "btnCancel", ".//toolbar[@accessiblename='Toolbar']/button[@accessiblename='Cancel']", 30000, null, "c11d766d-eb24-41b7-aa77-fbddc3f8c0d0");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("70fd598f-8922-4c70-aa85-1e64445fd365")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("70fd598f-8922-4c70-aa85-1e64445fd365")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btnDelete item.
            /// </summary>
            [RepositoryItem("5b0e9486-f8e8-4814-ae23-40c3bea4e0b8")]
            public virtual Ranorex.Button btnDelete
            {
                get
                {
                    return _btndeleteInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnDelete item info.
            /// </summary>
            [RepositoryItemInfo("5b0e9486-f8e8-4814-ae23-40c3bea4e0b8")]
            public virtual RepoItemInfo btnDeleteInfo
            {
                get
                {
                    return _btndeleteInfo;
                }
            }

            /// <summary>
            /// The btnOK item.
            /// </summary>
            [RepositoryItem("141b0bb0-b074-4844-9f1f-db03c7ee34ec")]
            public virtual Ranorex.Button btnOK
            {
                get
                {
                    return _btnokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnOK item info.
            /// </summary>
            [RepositoryItemInfo("141b0bb0-b074-4844-9f1f-db03c7ee34ec")]
            public virtual RepoItemInfo btnOKInfo
            {
                get
                {
                    return _btnokInfo;
                }
            }

            /// <summary>
            /// The txtNoteBoxEdit item.
            /// </summary>
            [RepositoryItem("eb5a9a15-69d5-4869-8532-9f7bdb46d0f9")]
            public virtual Ranorex.Text txtNoteBoxEdit
            {
                get
                {
                    return _txtnoteboxeditInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txtNoteBoxEdit item info.
            /// </summary>
            [RepositoryItemInfo("eb5a9a15-69d5-4869-8532-9f7bdb46d0f9")]
            public virtual RepoItemInfo txtNoteBoxEditInfo
            {
                get
                {
                    return _txtnoteboxeditInfo;
                }
            }

            /// <summary>
            /// The btnCancel item.
            /// </summary>
            [RepositoryItem("c11d766d-eb24-41b7-aa77-fbddc3f8c0d0")]
            public virtual Ranorex.Button btnCancel
            {
                get
                {
                    return _btncancelInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnCancel item info.
            /// </summary>
            [RepositoryItemInfo("c11d766d-eb24-41b7-aa77-fbddc3f8c0d0")]
            public virtual RepoItemInfo btnCancelInfo
            {
                get
                {
                    return _btncancelInfo;
                }
            }
        }

        /// <summary>
        /// The PromptFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("87c7bfbf-a3c5-4b39-a16a-b3b081bebf61")]
        public partial class PromptFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btnokInfo;

            /// <summary>
            /// Creates a new PromptForm  folder.
            /// </summary>
            public PromptFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("PromptForm", "/form[@controlname='PromptForm']", parentFolder, 30000, null, true, "87c7bfbf-a3c5-4b39-a16a-b3b081bebf61", "")
            {
                _btnokInfo = new RepoItemInfo(this, "btnOK", ".//toolbar[@accessiblename='Toolbar']/button[@accessiblename='OK']", 30000, null, "a1e8cfff-a196-4b6e-ab0a-6a81668a6175");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("87c7bfbf-a3c5-4b39-a16a-b3b081bebf61")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("87c7bfbf-a3c5-4b39-a16a-b3b081bebf61")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btnOK item.
            /// </summary>
            [RepositoryItem("a1e8cfff-a196-4b6e-ab0a-6a81668a6175")]
            public virtual Ranorex.Button btnOK
            {
                get
                {
                    return _btnokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnOK item info.
            /// </summary>
            [RepositoryItemInfo("a1e8cfff-a196-4b6e-ab0a-6a81668a6175")]
            public virtual RepoItemInfo btnOKInfo
            {
                get
                {
                    return _btnokInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
