///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace SmokeTest.Repositories
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Outlook_AddIn element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("b0647827-511c-40e5-94fe-1bfd60b6273a")]
    public partial class Outlook_AddIn : RepoGenBaseFolder
    {
        static Outlook_AddIn instance = new Outlook_AddIn();
        Outlook_AddInFolders.OutlookAppFolder _outlook;
        Outlook_AddInFolders.DetailedViewAppFolder _detailedview;
        Outlook_AddInFolders.OutlookSplashAppFolder _outlooksplash;
        Outlook_AddInFolders.SearchAppFolder _search;
        Outlook_AddInFolders.SearchResultAppFolder _searchresult;
        Outlook_AddInFolders.AboutFormAppFolder _aboutform;

        /// <summary>
        /// Gets the singleton class instance representing the Outlook_AddIn element repository.
        /// </summary>
        [RepositoryFolder("b0647827-511c-40e5-94fe-1bfd60b6273a")]
        public static Outlook_AddIn Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Outlook_AddIn() 
            : base("Outlook_AddIn", "/", null, 0, false, "b0647827-511c-40e5-94fe-1bfd60b6273a", ".\\RepositoryImages\\Outlook_AddInb0647827.rximgres")
        {
            _outlook = new Outlook_AddInFolders.OutlookAppFolder(this);
            _detailedview = new Outlook_AddInFolders.DetailedViewAppFolder(this);
            _outlooksplash = new Outlook_AddInFolders.OutlookSplashAppFolder(this);
            _search = new Outlook_AddInFolders.SearchAppFolder(this);
            _searchresult = new Outlook_AddInFolders.SearchResultAppFolder(this);
            _aboutform = new Outlook_AddInFolders.AboutFormAppFolder(this);
        }

#region Variables

        string _mailSub = "";

        /// <summary>
        /// Gets or sets the value of variable mailSub.
        /// </summary>
        [TestVariable("89d52fa4-36d8-4c73-9823-44d690186102")]
        public string mailSub
        {
            get { return _mailSub; }
            set { _mailSub = value; }
        }

        string _week = "";

        /// <summary>
        /// Gets or sets the value of variable week.
        /// </summary>
        [TestVariable("b648fbe7-1103-4ad1-a9d5-b312558d308d")]
        public string week
        {
            get { return _week; }
            set { _week = value; }
        }

        string _mailindex = "";

        /// <summary>
        /// Gets or sets the value of variable mailindex.
        /// </summary>
        [TestVariable("ed3b52d4-b0a2-4470-915d-0aec105d0578")]
        public string mailindex
        {
            get { return _mailindex; }
            set { _mailindex = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("b0647827-511c-40e5-94fe-1bfd60b6273a")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Outlook folder.
        /// </summary>
        [RepositoryFolder("c0ccc582-3a65-46de-8e8a-f6698ad12cac")]
        public virtual Outlook_AddInFolders.OutlookAppFolder Outlook
        {
            get { return _outlook; }
        }

        /// <summary>
        /// The DetailedView folder.
        /// </summary>
        [RepositoryFolder("79ab75a9-4129-4095-9157-e15cc0703470")]
        public virtual Outlook_AddInFolders.DetailedViewAppFolder DetailedView
        {
            get { return _detailedview; }
        }

        /// <summary>
        /// The OutlookSplash folder.
        /// </summary>
        [RepositoryFolder("85f6e642-459e-4e4f-83e2-09f8b5f37fbc")]
        public virtual Outlook_AddInFolders.OutlookSplashAppFolder OutlookSplash
        {
            get { return _outlooksplash; }
        }

        /// <summary>
        /// The Search folder.
        /// </summary>
        [RepositoryFolder("cd81e4d9-9c4b-4905-8901-2e9b72dd6cc4")]
        public virtual Outlook_AddInFolders.SearchAppFolder Search
        {
            get { return _search; }
        }

        /// <summary>
        /// The SearchResult folder.
        /// </summary>
        [RepositoryFolder("ca6c438b-50f8-4059-a587-395bd463c8da")]
        public virtual Outlook_AddInFolders.SearchResultAppFolder SearchResult
        {
            get { return _searchresult; }
        }

        /// <summary>
        /// The AboutForm folder.
        /// </summary>
        [RepositoryFolder("fec9f81f-d3b5-475d-b38e-76b23ac7d1d2")]
        public virtual Outlook_AddInFolders.AboutFormAppFolder AboutForm
        {
            get { return _aboutform; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Outlook_AddInFolders
    {
        /// <summary>
        /// The OutlookAppFolder folder.
        /// </summary>
        [RepositoryFolder("c0ccc582-3a65-46de-8e8a-f6698ad12cac")]
        public partial class OutlookAppFolder : RepoGenBaseFolder
        {
            Outlook_AddInFolders.AmicusAttorneyTasks1Folder _amicusattorneytasks1;
            Outlook_AddInFolders.MailFoldersFolder _mailfolders;
            RepoItemInfo _tabamicustasksInfo;
            RepoItemInfo _amicusattorneytasksInfo;
            RepoItemInfo _groupbyexpandeddatetodayInfo;
            RepoItemInfo _firstmailInfo;
            RepoItemInfo _txtsearchqueryInfo;
            RepoItemInfo _btnsubmitsearchInfo;
            RepoItemInfo _mailInfo;
            RepoItemInfo _treeitemgmailInfo;
            RepoItemInfo _mailpanelInfo;

            /// <summary>
            /// Creates a new Outlook  folder.
            /// </summary>
            public OutlookAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Outlook", "/form[@title<' - Outlook']", parentFolder, 30000, null, false, "c0ccc582-3a65-46de-8e8a-f6698ad12cac", "")
            {
                _amicusattorneytasks1 = new Outlook_AddInFolders.AmicusAttorneyTasks1Folder(this);
                _mailfolders = new Outlook_AddInFolders.MailFoldersFolder(this);
                _tabamicustasksInfo = new RepoItemInfo(this, "tabAmicusTasks", "container[@caption='MsoDockTop']//container[@name='Ribbon']/tabpagelist[@name='Ribbon Tabs']/tabpage[@name='Amicus Tasks']", 30000, null, "419dbcbd-cf88-4918-9ac0-ce4d15c1416f");
                _amicusattorneytasksInfo = new RepoItemInfo(this, "AmicusAttorneyTasks", "container[@caption='MsoDockTop']//container[@name='Ribbon']/container[@name='Lower Ribbon']/container[@name='Amicus Tasks']/container[@name='Amicus Attorney Tasks']", 30000, null, "e27c05d2-c78e-4d45-a474-bd1d61bf9b58");
                _groupbyexpandeddatetodayInfo = new RepoItemInfo(this, "GroupByExpandedDateToday", "element[@controlid='4704']/container[2]", 30000, null, "e2efa048-3a0c-4b7f-87b2-97dbe43097f6");
                _firstmailInfo = new RepoItemInfo(this, "FirstMail", "element[@controlid='4704']/container[2]/element[1]", 30000, true, "9971401f-63a8-485d-915e-2b999fa48767");
                _txtsearchqueryInfo = new RepoItemInfo(this, "txtSearchQuery", "?/?/container[@caption='NUIDocumentWindow']/container[@class='NetUIHWND']/element[@classname='NetUINetUI']/button[@classname='NetUIFolderBarRoot']/text[@name='Search Query']", 30000, null, "38b23c13-ca3e-4fdd-b440-a16658301bb8");
                _btnsubmitsearchInfo = new RepoItemInfo(this, "btnSubmitSearch", "?/?/container[@caption='NUIDocumentWindow']/container[@class='NetUIHWND']/element[@classname='NetUINetUI']/button[@classname='NetUIFolderBarRoot']/button[@name='Submit Search']", 30000, null, "a126acfe-9afc-480f-b3cd-88a67c0030c3");
                _mailInfo = new RepoItemInfo(this, "Mail", "element[@controlid='4704']/container[$week]/element[$mailindex]", 30000, true, "ec8f72c7-558a-4fd1-8412-0bcda82a97da");
                _treeitemgmailInfo = new RepoItemInfo(this, "TreeItemGmail", "container[@controlid='103']//tree[@name='Mail Folders']/treeitem/treeitem[@name='[Gmail]']", 30000, null, "e514fa8a-3e23-4687-aaa5-7683dc5646b4");
                _mailpanelInfo = new RepoItemInfo(this, "mailPanel", "element[@controlid='4704']", 30000, null, "e88d9c01-7b8b-454e-b03f-171a0da5375b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c0ccc582-3a65-46de-8e8a-f6698ad12cac")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c0ccc582-3a65-46de-8e8a-f6698ad12cac")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The tabAmicusTasks item.
            /// </summary>
            [RepositoryItem("419dbcbd-cf88-4918-9ac0-ce4d15c1416f")]
            public virtual Ranorex.TabPage tabAmicusTasks
            {
                get
                {
                    return _tabamicustasksInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The tabAmicusTasks item info.
            /// </summary>
            [RepositoryItemInfo("419dbcbd-cf88-4918-9ac0-ce4d15c1416f")]
            public virtual RepoItemInfo tabAmicusTasksInfo
            {
                get
                {
                    return _tabamicustasksInfo;
                }
            }

            /// <summary>
            /// The AmicusAttorneyTasks item.
            /// </summary>
            [RepositoryItem("e27c05d2-c78e-4d45-a474-bd1d61bf9b58")]
            public virtual Ranorex.Container AmicusAttorneyTasks
            {
                get
                {
                    return _amicusattorneytasksInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The AmicusAttorneyTasks item info.
            /// </summary>
            [RepositoryItemInfo("e27c05d2-c78e-4d45-a474-bd1d61bf9b58")]
            public virtual RepoItemInfo AmicusAttorneyTasksInfo
            {
                get
                {
                    return _amicusattorneytasksInfo;
                }
            }

            /// <summary>
            /// The GroupByExpandedDateToday item.
            /// </summary>
            [RepositoryItem("e2efa048-3a0c-4b7f-87b2-97dbe43097f6")]
            public virtual Ranorex.Container GroupByExpandedDateToday
            {
                get
                {
                    return _groupbyexpandeddatetodayInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The GroupByExpandedDateToday item info.
            /// </summary>
            [RepositoryItemInfo("e2efa048-3a0c-4b7f-87b2-97dbe43097f6")]
            public virtual RepoItemInfo GroupByExpandedDateTodayInfo
            {
                get
                {
                    return _groupbyexpandeddatetodayInfo;
                }
            }

            /// <summary>
            /// The FirstMail item.
            /// </summary>
            [RepositoryItem("9971401f-63a8-485d-915e-2b999fa48767")]
            public virtual Ranorex.Unknown FirstMail
            {
                get
                {
                    return _firstmailInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The FirstMail item info.
            /// </summary>
            [RepositoryItemInfo("9971401f-63a8-485d-915e-2b999fa48767")]
            public virtual RepoItemInfo FirstMailInfo
            {
                get
                {
                    return _firstmailInfo;
                }
            }

            /// <summary>
            /// The txtSearchQuery item.
            /// </summary>
            [RepositoryItem("38b23c13-ca3e-4fdd-b440-a16658301bb8")]
            public virtual Ranorex.Text txtSearchQuery
            {
                get
                {
                    return _txtsearchqueryInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txtSearchQuery item info.
            /// </summary>
            [RepositoryItemInfo("38b23c13-ca3e-4fdd-b440-a16658301bb8")]
            public virtual RepoItemInfo txtSearchQueryInfo
            {
                get
                {
                    return _txtsearchqueryInfo;
                }
            }

            /// <summary>
            /// The btnSubmitSearch item.
            /// </summary>
            [RepositoryItem("a126acfe-9afc-480f-b3cd-88a67c0030c3")]
            public virtual Ranorex.Button btnSubmitSearch
            {
                get
                {
                    return _btnsubmitsearchInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnSubmitSearch item info.
            /// </summary>
            [RepositoryItemInfo("a126acfe-9afc-480f-b3cd-88a67c0030c3")]
            public virtual RepoItemInfo btnSubmitSearchInfo
            {
                get
                {
                    return _btnsubmitsearchInfo;
                }
            }

            /// <summary>
            /// The Mail item.
            /// </summary>
            [RepositoryItem("ec8f72c7-558a-4fd1-8412-0bcda82a97da")]
            public virtual Ranorex.Unknown Mail
            {
                get
                {
                    return _mailInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Mail item info.
            /// </summary>
            [RepositoryItemInfo("ec8f72c7-558a-4fd1-8412-0bcda82a97da")]
            public virtual RepoItemInfo MailInfo
            {
                get
                {
                    return _mailInfo;
                }
            }

            /// <summary>
            /// The TreeItemGmail item.
            /// </summary>
            [RepositoryItem("e514fa8a-3e23-4687-aaa5-7683dc5646b4")]
            public virtual Ranorex.TreeItem TreeItemGmail
            {
                get
                {
                    return _treeitemgmailInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The TreeItemGmail item info.
            /// </summary>
            [RepositoryItemInfo("e514fa8a-3e23-4687-aaa5-7683dc5646b4")]
            public virtual RepoItemInfo TreeItemGmailInfo
            {
                get
                {
                    return _treeitemgmailInfo;
                }
            }

            /// <summary>
            /// The mailPanel item.
            /// </summary>
            [RepositoryItem("e88d9c01-7b8b-454e-b03f-171a0da5375b")]
            public virtual Ranorex.Unknown mailPanel
            {
                get
                {
                    return _mailpanelInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The mailPanel item info.
            /// </summary>
            [RepositoryItemInfo("e88d9c01-7b8b-454e-b03f-171a0da5375b")]
            public virtual RepoItemInfo mailPanelInfo
            {
                get
                {
                    return _mailpanelInfo;
                }
            }

            /// <summary>
            /// The AmicusAttorneyTasks1 folder.
            /// </summary>
            [RepositoryFolder("549fc0aa-202a-4fd4-8722-4b7ceb2eee34")]
            public virtual Outlook_AddInFolders.AmicusAttorneyTasks1Folder AmicusAttorneyTasks1
            {
                get { return _amicusattorneytasks1; }
            }

            /// <summary>
            /// The MailFolders folder.
            /// </summary>
            [RepositoryFolder("834ad0a2-d865-43dd-b24e-105d5a7d4273")]
            public virtual Outlook_AddInFolders.MailFoldersFolder MailFolders
            {
                get { return _mailfolders; }
            }
        }

        /// <summary>
        /// The AmicusAttorneyTasks1Folder folder.
        /// </summary>
        [RepositoryFolder("549fc0aa-202a-4fd4-8722-4b7ceb2eee34")]
        public partial class AmicusAttorneyTasks1Folder : RepoGenBaseFolder
        {
            RepoItemInfo _btnaboutInfo;
            RepoItemInfo _btnaddtofileInfo;
            RepoItemInfo _btnaddtopeopleInfo;
            RepoItemInfo _btndetailsInfo;
            RepoItemInfo _btnsearchamicusInfo;
            RepoItemInfo _netuilabelInfo;
            RepoItemInfo _txtsearchtextInfo;
            RepoItemInfo _btnviewaddtorelatedfileInfo;

            /// <summary>
            /// Creates a new AmicusAttorneyTasks1  folder.
            /// </summary>
            public AmicusAttorneyTasks1Folder(RepoGenBaseFolder parentFolder) :
                    base("AmicusAttorneyTasks1", ".//container[@name='Ribbon']/container[@name='Lower Ribbon']/container[@name='Amicus Tasks']/container[@name='Amicus Attorney Tasks']", parentFolder, 30000, null, false, "549fc0aa-202a-4fd4-8722-4b7ceb2eee34", "")
            {
                _btnaboutInfo = new RepoItemInfo(this, "btnAbout", "button[@name='About']", 30000, null, "ec6f13a4-a8fa-4706-9f06-d9009221c3e9");
                _btnaddtofileInfo = new RepoItemInfo(this, "btnAddToFile", "button[@name='Add to File']", 30000, null, "b4d302b2-83da-403b-abe9-ead74d8af29a");
                _btnaddtopeopleInfo = new RepoItemInfo(this, "btnAddToPeople", "button[@name='Add to People']", 30000, null, "dc812f88-b280-45dc-bbb6-3f4cb73e6d01");
                _btndetailsInfo = new RepoItemInfo(this, "btnDetails", "button[@name='Details']", 30000, null, "f84ff7cf-30c4-4bbb-a066-f3fc9c6e92e9");
                _btnsearchamicusInfo = new RepoItemInfo(this, "btnSearchAmicus", "button[@name='Search Amicus']", 30000, null, "30c08587-4dd4-422f-92c8-72f4d63bb3d4");
                _netuilabelInfo = new RepoItemInfo(this, "NetUILabel", "text[@classname='NetUILabel']", 30000, null, "99002b99-bc15-40d8-b7e3-cdd143184dfb");
                _txtsearchtextInfo = new RepoItemInfo(this, "txtSearchText", "text[@name='Search Text']", 30000, null, "f5d6a070-0b05-4b22-b817-52510d1a5f49");
                _btnviewaddtorelatedfileInfo = new RepoItemInfo(this, "btnViewAddToRelatedFile", "button[@name='View/Add To Related File']", 30000, null, "31a09de1-3faf-4032-a38c-d0cdead9e45e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("549fc0aa-202a-4fd4-8722-4b7ceb2eee34")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("549fc0aa-202a-4fd4-8722-4b7ceb2eee34")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btnAbout item.
            /// </summary>
            [RepositoryItem("ec6f13a4-a8fa-4706-9f06-d9009221c3e9")]
            public virtual Ranorex.Button btnAbout
            {
                get
                {
                    return _btnaboutInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnAbout item info.
            /// </summary>
            [RepositoryItemInfo("ec6f13a4-a8fa-4706-9f06-d9009221c3e9")]
            public virtual RepoItemInfo btnAboutInfo
            {
                get
                {
                    return _btnaboutInfo;
                }
            }

            /// <summary>
            /// The btnAddToFile item.
            /// </summary>
            [RepositoryItem("b4d302b2-83da-403b-abe9-ead74d8af29a")]
            public virtual Ranorex.Button btnAddToFile
            {
                get
                {
                    return _btnaddtofileInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnAddToFile item info.
            /// </summary>
            [RepositoryItemInfo("b4d302b2-83da-403b-abe9-ead74d8af29a")]
            public virtual RepoItemInfo btnAddToFileInfo
            {
                get
                {
                    return _btnaddtofileInfo;
                }
            }

            /// <summary>
            /// The btnAddToPeople item.
            /// </summary>
            [RepositoryItem("dc812f88-b280-45dc-bbb6-3f4cb73e6d01")]
            public virtual Ranorex.Button btnAddToPeople
            {
                get
                {
                    return _btnaddtopeopleInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnAddToPeople item info.
            /// </summary>
            [RepositoryItemInfo("dc812f88-b280-45dc-bbb6-3f4cb73e6d01")]
            public virtual RepoItemInfo btnAddToPeopleInfo
            {
                get
                {
                    return _btnaddtopeopleInfo;
                }
            }

            /// <summary>
            /// The btnDetails item.
            /// </summary>
            [RepositoryItem("f84ff7cf-30c4-4bbb-a066-f3fc9c6e92e9")]
            public virtual Ranorex.Button btnDetails
            {
                get
                {
                    return _btndetailsInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnDetails item info.
            /// </summary>
            [RepositoryItemInfo("f84ff7cf-30c4-4bbb-a066-f3fc9c6e92e9")]
            public virtual RepoItemInfo btnDetailsInfo
            {
                get
                {
                    return _btndetailsInfo;
                }
            }

            /// <summary>
            /// The btnSearchAmicus item.
            /// </summary>
            [RepositoryItem("30c08587-4dd4-422f-92c8-72f4d63bb3d4")]
            public virtual Ranorex.Button btnSearchAmicus
            {
                get
                {
                    return _btnsearchamicusInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnSearchAmicus item info.
            /// </summary>
            [RepositoryItemInfo("30c08587-4dd4-422f-92c8-72f4d63bb3d4")]
            public virtual RepoItemInfo btnSearchAmicusInfo
            {
                get
                {
                    return _btnsearchamicusInfo;
                }
            }

            /// <summary>
            /// The NetUILabel item.
            /// </summary>
            [RepositoryItem("99002b99-bc15-40d8-b7e3-cdd143184dfb")]
            public virtual Ranorex.Text NetUILabel
            {
                get
                {
                    return _netuilabelInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The NetUILabel item info.
            /// </summary>
            [RepositoryItemInfo("99002b99-bc15-40d8-b7e3-cdd143184dfb")]
            public virtual RepoItemInfo NetUILabelInfo
            {
                get
                {
                    return _netuilabelInfo;
                }
            }

            /// <summary>
            /// The txtSearchText item.
            /// </summary>
            [RepositoryItem("f5d6a070-0b05-4b22-b817-52510d1a5f49")]
            public virtual Ranorex.Text txtSearchText
            {
                get
                {
                    return _txtsearchtextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txtSearchText item info.
            /// </summary>
            [RepositoryItemInfo("f5d6a070-0b05-4b22-b817-52510d1a5f49")]
            public virtual RepoItemInfo txtSearchTextInfo
            {
                get
                {
                    return _txtsearchtextInfo;
                }
            }

            /// <summary>
            /// The btnViewAddToRelatedFile item.
            /// </summary>
            [RepositoryItem("31a09de1-3faf-4032-a38c-d0cdead9e45e")]
            public virtual Ranorex.Button btnViewAddToRelatedFile
            {
                get
                {
                    return _btnviewaddtorelatedfileInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnViewAddToRelatedFile item info.
            /// </summary>
            [RepositoryItemInfo("31a09de1-3faf-4032-a38c-d0cdead9e45e")]
            public virtual RepoItemInfo btnViewAddToRelatedFileInfo
            {
                get
                {
                    return _btnviewaddtorelatedfileInfo;
                }
            }
        }

        /// <summary>
        /// The MailFoldersFolder folder.
        /// </summary>
        [RepositoryFolder("834ad0a2-d865-43dd-b24e-105d5a7d4273")]
        public partial class MailFoldersFolder : RepoGenBaseFolder
        {
            RepoItemInfo _binInfo;
            RepoItemInfo _draftsInfo;
            RepoItemInfo _spamInfo;
            RepoItemInfo _starredInfo;
            RepoItemInfo _importantInfo;
            RepoItemInfo _sentmailInfo;
            RepoItemInfo _outboxInfo;
            RepoItemInfo _deleteditemsInfo;
            RepoItemInfo _junkemailInfo;

            /// <summary>
            /// Creates a new MailFolders  folder.
            /// </summary>
            public MailFoldersFolder(RepoGenBaseFolder parentFolder) :
                    base("MailFolders", ".//tree[@name='Mail Folders']", parentFolder, 30000, null, false, "834ad0a2-d865-43dd-b24e-105d5a7d4273", "")
            {
                _binInfo = new RepoItemInfo(this, "Bin", "treeitem/treeitem/treeitem[@name>'Bin:']", 30000, null, "27ae4c73-55dd-432f-a351-de1def614e26");
                _draftsInfo = new RepoItemInfo(this, "Drafts", "treeitem//treeitem[@name>'Drafts']", 30000, null, "00f19ee0-0124-4e66-8a8e-7f977bffbaf1");
                _spamInfo = new RepoItemInfo(this, "Spam", "treeitem//treeitem[@name>'Spam']", 30000, null, "236beefa-f8e0-4664-b7dd-abd58dcecd2d");
                _starredInfo = new RepoItemInfo(this, "Starred", "treeitem//treeitem[@name>'Starred']", 30000, null, "b4cdc3dc-d6ec-40ec-9d74-cdf7c9d9e850");
                _importantInfo = new RepoItemInfo(this, "Important", "treeitem//treeitem[@name>'Important']", 30000, null, "7ff51a1f-9c6a-4099-83e0-65371e0d52d2");
                _sentmailInfo = new RepoItemInfo(this, "SentMail", "treeitem//treeitem[@name>'Sent Mail']", 30000, null, "4c011f10-1106-457b-81bf-e8c9afd0ec6a");
                _outboxInfo = new RepoItemInfo(this, "Outbox", "treeitem/treeitem[@name>'Outbox']", 30000, null, "a2237b08-2ceb-4da4-95dc-bfce00fedd2f");
                _deleteditemsInfo = new RepoItemInfo(this, "DeletedItems", "treeitem//treeitem[@name='Deleted Items']", 30000, null, "d0b7a0e1-c51d-4826-9a85-1ba786ac3553");
                _junkemailInfo = new RepoItemInfo(this, "JunkEmail", "treeitem/treeitem[@name='Junk Email']", 30000, null, "c6cd82af-8d2a-4ce5-9c5d-61c2677867d7");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("834ad0a2-d865-43dd-b24e-105d5a7d4273")]
            public virtual Ranorex.Tree Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Tree>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("834ad0a2-d865-43dd-b24e-105d5a7d4273")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Bin item.
            /// </summary>
            [RepositoryItem("27ae4c73-55dd-432f-a351-de1def614e26")]
            public virtual Ranorex.TreeItem Bin
            {
                get
                {
                    return _binInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Bin item info.
            /// </summary>
            [RepositoryItemInfo("27ae4c73-55dd-432f-a351-de1def614e26")]
            public virtual RepoItemInfo BinInfo
            {
                get
                {
                    return _binInfo;
                }
            }

            /// <summary>
            /// The Drafts item.
            /// </summary>
            [RepositoryItem("00f19ee0-0124-4e66-8a8e-7f977bffbaf1")]
            public virtual Ranorex.TreeItem Drafts
            {
                get
                {
                    return _draftsInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Drafts item info.
            /// </summary>
            [RepositoryItemInfo("00f19ee0-0124-4e66-8a8e-7f977bffbaf1")]
            public virtual RepoItemInfo DraftsInfo
            {
                get
                {
                    return _draftsInfo;
                }
            }

            /// <summary>
            /// The Spam item.
            /// </summary>
            [RepositoryItem("236beefa-f8e0-4664-b7dd-abd58dcecd2d")]
            public virtual Ranorex.TreeItem Spam
            {
                get
                {
                    return _spamInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Spam item info.
            /// </summary>
            [RepositoryItemInfo("236beefa-f8e0-4664-b7dd-abd58dcecd2d")]
            public virtual RepoItemInfo SpamInfo
            {
                get
                {
                    return _spamInfo;
                }
            }

            /// <summary>
            /// The Starred item.
            /// </summary>
            [RepositoryItem("b4cdc3dc-d6ec-40ec-9d74-cdf7c9d9e850")]
            public virtual Ranorex.TreeItem Starred
            {
                get
                {
                    return _starredInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Starred item info.
            /// </summary>
            [RepositoryItemInfo("b4cdc3dc-d6ec-40ec-9d74-cdf7c9d9e850")]
            public virtual RepoItemInfo StarredInfo
            {
                get
                {
                    return _starredInfo;
                }
            }

            /// <summary>
            /// The Important item.
            /// </summary>
            [RepositoryItem("7ff51a1f-9c6a-4099-83e0-65371e0d52d2")]
            public virtual Ranorex.TreeItem Important
            {
                get
                {
                    return _importantInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Important item info.
            /// </summary>
            [RepositoryItemInfo("7ff51a1f-9c6a-4099-83e0-65371e0d52d2")]
            public virtual RepoItemInfo ImportantInfo
            {
                get
                {
                    return _importantInfo;
                }
            }

            /// <summary>
            /// The SentMail item.
            /// </summary>
            [RepositoryItem("4c011f10-1106-457b-81bf-e8c9afd0ec6a")]
            public virtual Ranorex.TreeItem SentMail
            {
                get
                {
                    return _sentmailInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The SentMail item info.
            /// </summary>
            [RepositoryItemInfo("4c011f10-1106-457b-81bf-e8c9afd0ec6a")]
            public virtual RepoItemInfo SentMailInfo
            {
                get
                {
                    return _sentmailInfo;
                }
            }

            /// <summary>
            /// The Outbox item.
            /// </summary>
            [RepositoryItem("a2237b08-2ceb-4da4-95dc-bfce00fedd2f")]
            public virtual Ranorex.TreeItem Outbox
            {
                get
                {
                    return _outboxInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Outbox item info.
            /// </summary>
            [RepositoryItemInfo("a2237b08-2ceb-4da4-95dc-bfce00fedd2f")]
            public virtual RepoItemInfo OutboxInfo
            {
                get
                {
                    return _outboxInfo;
                }
            }

            /// <summary>
            /// The DeletedItems item.
            /// </summary>
            [RepositoryItem("d0b7a0e1-c51d-4826-9a85-1ba786ac3553")]
            public virtual Ranorex.TreeItem DeletedItems
            {
                get
                {
                    return _deleteditemsInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The DeletedItems item info.
            /// </summary>
            [RepositoryItemInfo("d0b7a0e1-c51d-4826-9a85-1ba786ac3553")]
            public virtual RepoItemInfo DeletedItemsInfo
            {
                get
                {
                    return _deleteditemsInfo;
                }
            }

            /// <summary>
            /// The JunkEmail item.
            /// </summary>
            [RepositoryItem("c6cd82af-8d2a-4ce5-9c5d-61c2677867d7")]
            public virtual Ranorex.TreeItem JunkEmail
            {
                get
                {
                    return _junkemailInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The JunkEmail item info.
            /// </summary>
            [RepositoryItemInfo("c6cd82af-8d2a-4ce5-9c5d-61c2677867d7")]
            public virtual RepoItemInfo JunkEmailInfo
            {
                get
                {
                    return _junkemailInfo;
                }
            }
        }

        /// <summary>
        /// The DetailedViewAppFolder folder.
        /// </summary>
        [RepositoryFolder("79ab75a9-4129-4095-9157-e15cc0703470")]
        public partial class DetailedViewAppFolder : RepoGenBaseFolder
        {
            Outlook_AddInFolders.AmicusAttorneyTasks1Folder1 _amicusattorneytasks1;
            RepoItemInfo _tabamicustasksInfo;
            RepoItemInfo _amicusattorneytasksInfo;

            /// <summary>
            /// Creates a new DetailedView  folder.
            /// </summary>
            public DetailedViewAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DetailedView", "/form[@title>$mailSub]", parentFolder, 30000, null, false, "79ab75a9-4129-4095-9157-e15cc0703470", "")
            {
                _amicusattorneytasks1 = new Outlook_AddInFolders.AmicusAttorneyTasks1Folder1(this);
                _tabamicustasksInfo = new RepoItemInfo(this, "tabAmicusTasks", "container[@caption='MsoDockTop']//container[@name='Ribbon']/tabpagelist[@name='Ribbon Tabs']/tabpage[@name='Amicus Tasks']", 30000, null, "86bee181-fed9-4e5e-a946-2befd29afc53");
                _amicusattorneytasksInfo = new RepoItemInfo(this, "AmicusAttorneyTasks", "container[@caption='MsoDockTop']//container[@name='Ribbon']/container[@name='Lower Ribbon']/container[@name='Amicus Tasks']/container[@name='Amicus Attorney Tasks']", 30000, null, "b3a0a0c9-ff77-48aa-8702-a6ca319e6b12");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("79ab75a9-4129-4095-9157-e15cc0703470")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("79ab75a9-4129-4095-9157-e15cc0703470")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The tabAmicusTasks item.
            /// </summary>
            [RepositoryItem("86bee181-fed9-4e5e-a946-2befd29afc53")]
            public virtual Ranorex.TabPage tabAmicusTasks
            {
                get
                {
                    return _tabamicustasksInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The tabAmicusTasks item info.
            /// </summary>
            [RepositoryItemInfo("86bee181-fed9-4e5e-a946-2befd29afc53")]
            public virtual RepoItemInfo tabAmicusTasksInfo
            {
                get
                {
                    return _tabamicustasksInfo;
                }
            }

            /// <summary>
            /// The AmicusAttorneyTasks item.
            /// </summary>
            [RepositoryItem("b3a0a0c9-ff77-48aa-8702-a6ca319e6b12")]
            public virtual Ranorex.Container AmicusAttorneyTasks
            {
                get
                {
                    return _amicusattorneytasksInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The AmicusAttorneyTasks item info.
            /// </summary>
            [RepositoryItemInfo("b3a0a0c9-ff77-48aa-8702-a6ca319e6b12")]
            public virtual RepoItemInfo AmicusAttorneyTasksInfo
            {
                get
                {
                    return _amicusattorneytasksInfo;
                }
            }

            /// <summary>
            /// The AmicusAttorneyTasks1 folder.
            /// </summary>
            [RepositoryFolder("d1d1b670-3bb2-47a6-b4ff-3578a7dc6a8a")]
            public virtual Outlook_AddInFolders.AmicusAttorneyTasks1Folder1 AmicusAttorneyTasks1
            {
                get { return _amicusattorneytasks1; }
            }
        }

        /// <summary>
        /// The AmicusAttorneyTasks1Folder1 folder.
        /// </summary>
        [RepositoryFolder("d1d1b670-3bb2-47a6-b4ff-3578a7dc6a8a")]
        public partial class AmicusAttorneyTasks1Folder1 : RepoGenBaseFolder
        {
            RepoItemInfo _btnaboutInfo;
            RepoItemInfo _btnaddtofileInfo;
            RepoItemInfo _btnaddtopeopleInfo;
            RepoItemInfo _btndetailsInfo;
            RepoItemInfo _btnsearchamicusInfo;
            RepoItemInfo _netuilabelInfo;
            RepoItemInfo _txtsearchtextInfo;
            RepoItemInfo _btnviewaddtorelatedfileInfo;

            /// <summary>
            /// Creates a new AmicusAttorneyTasks1  folder.
            /// </summary>
            public AmicusAttorneyTasks1Folder1(RepoGenBaseFolder parentFolder) :
                    base("AmicusAttorneyTasks1", ".//container[@name='Ribbon']/container[@name='Lower Ribbon']/container[@name='Amicus Tasks']/container[@name='Amicus Attorney Tasks']", parentFolder, 30000, null, false, "d1d1b670-3bb2-47a6-b4ff-3578a7dc6a8a", "")
            {
                _btnaboutInfo = new RepoItemInfo(this, "btnAbout", "button[@name='About']", 30000, null, "bc808442-83a9-4119-8016-943c200e736a");
                _btnaddtofileInfo = new RepoItemInfo(this, "btnAddToFile", "button[@name='Add to File']", 30000, null, "03eb8112-45e0-4f3e-9133-02f3ec3392a8");
                _btnaddtopeopleInfo = new RepoItemInfo(this, "btnAddToPeople", "button[@name='Add to People']", 30000, null, "f5785ddc-cad3-4f4f-8c3e-10f3dccf48cd");
                _btndetailsInfo = new RepoItemInfo(this, "btnDetails", "button[@name='Details']", 30000, null, "e9ac8ab5-2c19-4745-b1d9-f9c01a211fe7");
                _btnsearchamicusInfo = new RepoItemInfo(this, "btnSearchAmicus", "button[@name='Search Amicus']", 30000, null, "964794ec-5596-4b03-a32b-23497565d9e2");
                _netuilabelInfo = new RepoItemInfo(this, "NetUILabel", "text[@classname='NetUILabel']", 30000, null, "3de288df-e1af-4677-a111-c0f385411288");
                _txtsearchtextInfo = new RepoItemInfo(this, "txtSearchText", "text[@name='Search Text']", 30000, null, "a2ce95a9-1c1c-4687-89b6-7c1701efc7d2");
                _btnviewaddtorelatedfileInfo = new RepoItemInfo(this, "btnViewAddToRelatedFile", "button[@name='View/Add To Related File']", 30000, null, "1bdd9eb7-1255-47b2-bd54-f0f625df59f3");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d1d1b670-3bb2-47a6-b4ff-3578a7dc6a8a")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d1d1b670-3bb2-47a6-b4ff-3578a7dc6a8a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btnAbout item.
            /// </summary>
            [RepositoryItem("bc808442-83a9-4119-8016-943c200e736a")]
            public virtual Ranorex.Button btnAbout
            {
                get
                {
                    return _btnaboutInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnAbout item info.
            /// </summary>
            [RepositoryItemInfo("bc808442-83a9-4119-8016-943c200e736a")]
            public virtual RepoItemInfo btnAboutInfo
            {
                get
                {
                    return _btnaboutInfo;
                }
            }

            /// <summary>
            /// The btnAddToFile item.
            /// </summary>
            [RepositoryItem("03eb8112-45e0-4f3e-9133-02f3ec3392a8")]
            public virtual Ranorex.Button btnAddToFile
            {
                get
                {
                    return _btnaddtofileInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnAddToFile item info.
            /// </summary>
            [RepositoryItemInfo("03eb8112-45e0-4f3e-9133-02f3ec3392a8")]
            public virtual RepoItemInfo btnAddToFileInfo
            {
                get
                {
                    return _btnaddtofileInfo;
                }
            }

            /// <summary>
            /// The btnAddToPeople item.
            /// </summary>
            [RepositoryItem("f5785ddc-cad3-4f4f-8c3e-10f3dccf48cd")]
            public virtual Ranorex.Button btnAddToPeople
            {
                get
                {
                    return _btnaddtopeopleInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnAddToPeople item info.
            /// </summary>
            [RepositoryItemInfo("f5785ddc-cad3-4f4f-8c3e-10f3dccf48cd")]
            public virtual RepoItemInfo btnAddToPeopleInfo
            {
                get
                {
                    return _btnaddtopeopleInfo;
                }
            }

            /// <summary>
            /// The btnDetails item.
            /// </summary>
            [RepositoryItem("e9ac8ab5-2c19-4745-b1d9-f9c01a211fe7")]
            public virtual Ranorex.Button btnDetails
            {
                get
                {
                    return _btndetailsInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnDetails item info.
            /// </summary>
            [RepositoryItemInfo("e9ac8ab5-2c19-4745-b1d9-f9c01a211fe7")]
            public virtual RepoItemInfo btnDetailsInfo
            {
                get
                {
                    return _btndetailsInfo;
                }
            }

            /// <summary>
            /// The btnSearchAmicus item.
            /// </summary>
            [RepositoryItem("964794ec-5596-4b03-a32b-23497565d9e2")]
            public virtual Ranorex.Button btnSearchAmicus
            {
                get
                {
                    return _btnsearchamicusInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnSearchAmicus item info.
            /// </summary>
            [RepositoryItemInfo("964794ec-5596-4b03-a32b-23497565d9e2")]
            public virtual RepoItemInfo btnSearchAmicusInfo
            {
                get
                {
                    return _btnsearchamicusInfo;
                }
            }

            /// <summary>
            /// The NetUILabel item.
            /// </summary>
            [RepositoryItem("3de288df-e1af-4677-a111-c0f385411288")]
            public virtual Ranorex.Text NetUILabel
            {
                get
                {
                    return _netuilabelInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The NetUILabel item info.
            /// </summary>
            [RepositoryItemInfo("3de288df-e1af-4677-a111-c0f385411288")]
            public virtual RepoItemInfo NetUILabelInfo
            {
                get
                {
                    return _netuilabelInfo;
                }
            }

            /// <summary>
            /// The txtSearchText item.
            /// </summary>
            [RepositoryItem("a2ce95a9-1c1c-4687-89b6-7c1701efc7d2")]
            public virtual Ranorex.Text txtSearchText
            {
                get
                {
                    return _txtsearchtextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txtSearchText item info.
            /// </summary>
            [RepositoryItemInfo("a2ce95a9-1c1c-4687-89b6-7c1701efc7d2")]
            public virtual RepoItemInfo txtSearchTextInfo
            {
                get
                {
                    return _txtsearchtextInfo;
                }
            }

            /// <summary>
            /// The btnViewAddToRelatedFile item.
            /// </summary>
            [RepositoryItem("1bdd9eb7-1255-47b2-bd54-f0f625df59f3")]
            public virtual Ranorex.Button btnViewAddToRelatedFile
            {
                get
                {
                    return _btnviewaddtorelatedfileInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnViewAddToRelatedFile item info.
            /// </summary>
            [RepositoryItemInfo("1bdd9eb7-1255-47b2-bd54-f0f625df59f3")]
            public virtual RepoItemInfo btnViewAddToRelatedFileInfo
            {
                get
                {
                    return _btnviewaddtorelatedfileInfo;
                }
            }
        }

        /// <summary>
        /// The OutlookSplashAppFolder folder.
        /// </summary>
        [RepositoryFolder("85f6e642-459e-4e4f-83e2-09f8b5f37fbc")]
        public partial class OutlookSplashAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new OutlookSplash  folder.
            /// </summary>
            public OutlookSplashAppFolder(RepoGenBaseFolder parentFolder) :
                    base("OutlookSplash", "/form[@title='Opening - Outlook']", parentFolder, 30000, null, false, "85f6e642-459e-4e4f-83e2-09f8b5f37fbc", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("85f6e642-459e-4e4f-83e2-09f8b5f37fbc")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("85f6e642-459e-4e4f-83e2-09f8b5f37fbc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The SearchAppFolder folder.
        /// </summary>
        [RepositoryFolder("cd81e4d9-9c4b-4905-8901-2e9b72dd6cc4")]
        public partial class SearchAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btnfindnowInfo;
            RepoItemInfo _btncancelInfo;

            /// <summary>
            /// Creates a new Search  folder.
            /// </summary>
            public SearchAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Search", "/form[@controlname='Search']", parentFolder, 30000, null, false, "cd81e4d9-9c4b-4905-8901-2e9b72dd6cc4", "")
            {
                _btnfindnowInfo = new RepoItemInfo(this, "btnFindNow", "container[@controlname='menubar_Fill_Panel']//toolbar[@accessiblename='Toolbar']/button[@accessiblename='Find Now']", 30000, null, "48026ab5-9d55-45ef-9692-8836fcc70121");
                _btncancelInfo = new RepoItemInfo(this, "btnCancel", "container[@controlname='menubar_Fill_Panel']//toolbar[@accessiblename='Toolbar']/button[@accessiblename='Cancel']", 30000, null, "7ffb0f72-849e-40b4-b0a8-61a1def3786d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("cd81e4d9-9c4b-4905-8901-2e9b72dd6cc4")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("cd81e4d9-9c4b-4905-8901-2e9b72dd6cc4")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btnFindNow item.
            /// </summary>
            [RepositoryItem("48026ab5-9d55-45ef-9692-8836fcc70121")]
            public virtual Ranorex.Button btnFindNow
            {
                get
                {
                    return _btnfindnowInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnFindNow item info.
            /// </summary>
            [RepositoryItemInfo("48026ab5-9d55-45ef-9692-8836fcc70121")]
            public virtual RepoItemInfo btnFindNowInfo
            {
                get
                {
                    return _btnfindnowInfo;
                }
            }

            /// <summary>
            /// The btnCancel item.
            /// </summary>
            [RepositoryItem("7ffb0f72-849e-40b4-b0a8-61a1def3786d")]
            public virtual Ranorex.Button btnCancel
            {
                get
                {
                    return _btncancelInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnCancel item info.
            /// </summary>
            [RepositoryItemInfo("7ffb0f72-849e-40b4-b0a8-61a1def3786d")]
            public virtual RepoItemInfo btnCancelInfo
            {
                get
                {
                    return _btncancelInfo;
                }
            }
        }

        /// <summary>
        /// The SearchResultAppFolder folder.
        /// </summary>
        [RepositoryFolder("ca6c438b-50f8-4059-a587-395bd463c8da")]
        public partial class SearchResultAppFolder : RepoGenBaseFolder
        {
            Outlook_AddInFolders.Toolbar1Folder _toolbar1;
            RepoItemInfo _tblsearchresultsInfo;
            RepoItemInfo _dockbottomInfo;

            /// <summary>
            /// Creates a new SearchResult  folder.
            /// </summary>
            public SearchResultAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SearchResult", "/form[@controlname='SearchResult']", parentFolder, 30000, null, false, "ca6c438b-50f8-4059-a587-395bd463c8da", "")
            {
                _toolbar1 = new Outlook_AddInFolders.Toolbar1Folder(this);
                _tblsearchresultsInfo = new RepoItemInfo(this, "tblSearchResults", "container[@controlname='menubar_Fill_Panel']/container[@controlname='pnlBase']//table[@accessiblename='Band 0']", 30000, null, "629398d1-bbfc-43d6-9706-e71216565d15");
                _dockbottomInfo = new RepoItemInfo(this, "DockBottom", "container[@controlname='menubar_Fill_Panel']/?/?/container[@accessiblename='DockBottom']", 30000, null, "f3098072-0126-4196-a587-387e3d9400a6");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ca6c438b-50f8-4059-a587-395bd463c8da")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ca6c438b-50f8-4059-a587-395bd463c8da")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The tblSearchResults item.
            /// </summary>
            [RepositoryItem("629398d1-bbfc-43d6-9706-e71216565d15")]
            public virtual Ranorex.Table tblSearchResults
            {
                get
                {
                    return _tblsearchresultsInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The tblSearchResults item info.
            /// </summary>
            [RepositoryItemInfo("629398d1-bbfc-43d6-9706-e71216565d15")]
            public virtual RepoItemInfo tblSearchResultsInfo
            {
                get
                {
                    return _tblsearchresultsInfo;
                }
            }

            /// <summary>
            /// The DockBottom item.
            /// </summary>
            [RepositoryItem("f3098072-0126-4196-a587-387e3d9400a6")]
            public virtual Ranorex.Container DockBottom
            {
                get
                {
                    return _dockbottomInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The DockBottom item info.
            /// </summary>
            [RepositoryItemInfo("f3098072-0126-4196-a587-387e3d9400a6")]
            public virtual RepoItemInfo DockBottomInfo
            {
                get
                {
                    return _dockbottomInfo;
                }
            }

            /// <summary>
            /// The Toolbar1 folder.
            /// </summary>
            [RepositoryFolder("e08c2fdc-d97f-4f31-911b-ea3b36a30db0")]
            public virtual Outlook_AddInFolders.Toolbar1Folder Toolbar1
            {
                get { return _toolbar1; }
            }
        }

        /// <summary>
        /// The Toolbar1Folder folder.
        /// </summary>
        [RepositoryFolder("e08c2fdc-d97f-4f31-911b-ea3b36a30db0")]
        public partial class Toolbar1Folder : RepoGenBaseFolder
        {
            RepoItemInfo _toolbarInfo;
            RepoItemInfo _btncloseInfo;
            RepoItemInfo _btngeneratedocumentInfo;
            RepoItemInfo _btnhidefromresultsInfo;
            RepoItemInfo _btnprintInfo;

            /// <summary>
            /// Creates a new Toolbar1  folder.
            /// </summary>
            public Toolbar1Folder(RepoGenBaseFolder parentFolder) :
                    base("Toolbar1", "container[@controlname='menubar_Fill_Panel']//toolbar[@accessiblename='Toolbar']", parentFolder, 30000, null, false, "e08c2fdc-d97f-4f31-911b-ea3b36a30db0", "")
            {
                _toolbarInfo = new RepoItemInfo(this, "Toolbar", "", 30000, null, "75a6247c-7840-40cd-9864-6b6ebec65603");
                _btncloseInfo = new RepoItemInfo(this, "btnClose", "button[@accessiblename='Close']", 30000, null, "d9c3d88f-80bb-4c0d-af17-1afaec70bf8d");
                _btngeneratedocumentInfo = new RepoItemInfo(this, "btnGenerateDocument", "button[@accessiblename='Generate Document']", 30000, null, "9aab45e6-5fc0-46d8-a0f6-8b0eb1f43cb4");
                _btnhidefromresultsInfo = new RepoItemInfo(this, "btnHideFromResults", "button[@accessiblename='Hide from Results']", 30000, null, "4251c66d-5ab4-40fa-baca-18927350092d");
                _btnprintInfo = new RepoItemInfo(this, "btnPrint", "button[@accessiblename='Print']", 30000, null, "3f5e2370-77ea-4fce-9b02-691dc5e97b62");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e08c2fdc-d97f-4f31-911b-ea3b36a30db0")]
            public virtual Ranorex.ToolBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ToolBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e08c2fdc-d97f-4f31-911b-ea3b36a30db0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Toolbar item.
            /// </summary>
            [RepositoryItem("75a6247c-7840-40cd-9864-6b6ebec65603")]
            public virtual Ranorex.ToolBar Toolbar
            {
                get
                {
                    return _toolbarInfo.CreateAdapter<Ranorex.ToolBar>(true);
                }
            }

            /// <summary>
            /// The Toolbar item info.
            /// </summary>
            [RepositoryItemInfo("75a6247c-7840-40cd-9864-6b6ebec65603")]
            public virtual RepoItemInfo ToolbarInfo
            {
                get
                {
                    return _toolbarInfo;
                }
            }

            /// <summary>
            /// The btnClose item.
            /// </summary>
            [RepositoryItem("d9c3d88f-80bb-4c0d-af17-1afaec70bf8d")]
            public virtual Ranorex.Button btnClose
            {
                get
                {
                    return _btncloseInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnClose item info.
            /// </summary>
            [RepositoryItemInfo("d9c3d88f-80bb-4c0d-af17-1afaec70bf8d")]
            public virtual RepoItemInfo btnCloseInfo
            {
                get
                {
                    return _btncloseInfo;
                }
            }

            /// <summary>
            /// The btnGenerateDocument item.
            /// </summary>
            [RepositoryItem("9aab45e6-5fc0-46d8-a0f6-8b0eb1f43cb4")]
            public virtual Ranorex.Button btnGenerateDocument
            {
                get
                {
                    return _btngeneratedocumentInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnGenerateDocument item info.
            /// </summary>
            [RepositoryItemInfo("9aab45e6-5fc0-46d8-a0f6-8b0eb1f43cb4")]
            public virtual RepoItemInfo btnGenerateDocumentInfo
            {
                get
                {
                    return _btngeneratedocumentInfo;
                }
            }

            /// <summary>
            /// The btnHideFromResults item.
            /// </summary>
            [RepositoryItem("4251c66d-5ab4-40fa-baca-18927350092d")]
            public virtual Ranorex.Button btnHideFromResults
            {
                get
                {
                    return _btnhidefromresultsInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnHideFromResults item info.
            /// </summary>
            [RepositoryItemInfo("4251c66d-5ab4-40fa-baca-18927350092d")]
            public virtual RepoItemInfo btnHideFromResultsInfo
            {
                get
                {
                    return _btnhidefromresultsInfo;
                }
            }

            /// <summary>
            /// The btnPrint item.
            /// </summary>
            [RepositoryItem("3f5e2370-77ea-4fce-9b02-691dc5e97b62")]
            public virtual Ranorex.Button btnPrint
            {
                get
                {
                    return _btnprintInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnPrint item info.
            /// </summary>
            [RepositoryItemInfo("3f5e2370-77ea-4fce-9b02-691dc5e97b62")]
            public virtual RepoItemInfo btnPrintInfo
            {
                get
                {
                    return _btnprintInfo;
                }
            }
        }

        /// <summary>
        /// The AboutFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("fec9f81f-d3b5-475d-b38e-76b23ac7d1d2")]
        public partial class AboutFormAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new AboutForm  folder.
            /// </summary>
            public AboutFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("AboutForm", "/form[@controlname='AboutForm']", parentFolder, 30000, null, false, "fec9f81f-d3b5-475d-b38e-76b23ac7d1d2", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("fec9f81f-d3b5-475d-b38e-76b23ac7d1d2")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("fec9f81f-d3b5-475d-b38e-76b23ac7d1d2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
