///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace SmokeTest.Repositories
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TimeSheets element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("215b7309-4c4e-40b3-a16a-4cc56ff68578")]
    public partial class TimeSheets : RepoGenBaseFolder
    {
        static TimeSheets instance = new TimeSheets();
        TimeSheetsFolders.MainFormAppFolder _mainform;
        TimeSheetsFolders.FileSelectFormAppFolder _fileselectform;
        TimeSheetsFolders.FindFilesFormAppFolder _findfilesform;
        TimeSheetsFolders.TimeEntryDetailsFormAppFolder _timeentrydetailsform;
        TimeSheetsFolders.PromptFormAppFolder _promptform;

        /// <summary>
        /// Gets the singleton class instance representing the TimeSheets element repository.
        /// </summary>
        [RepositoryFolder("215b7309-4c4e-40b3-a16a-4cc56ff68578")]
        public static TimeSheets Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TimeSheets() 
            : base("TimeSheets", "/", null, 0, false, "215b7309-4c4e-40b3-a16a-4cc56ff68578", ".\\RepositoryImages\\TimeSheets215b7309.rximgres")
        {
            _mainform = new TimeSheetsFolders.MainFormAppFolder(this);
            _fileselectform = new TimeSheetsFolders.FileSelectFormAppFolder(this);
            _findfilesform = new TimeSheetsFolders.FindFilesFormAppFolder(this);
            _timeentrydetailsform = new TimeSheetsFolders.TimeEntryDetailsFormAppFolder(this);
            _promptform = new TimeSheetsFolders.PromptFormAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("215b7309-4c4e-40b3-a16a-4cc56ff68578")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The MainForm folder.
        /// </summary>
        [RepositoryFolder("06770a82-01be-4808-b2e8-13542b61f153")]
        public virtual TimeSheetsFolders.MainFormAppFolder MainForm
        {
            get { return _mainform; }
        }

        /// <summary>
        /// The FileSelectForm folder.
        /// </summary>
        [RepositoryFolder("9c7ff0e1-6bb3-49b2-abdb-acfc29c6e504")]
        public virtual TimeSheetsFolders.FileSelectFormAppFolder FileSelectForm
        {
            get { return _fileselectform; }
        }

        /// <summary>
        /// The FindFilesForm folder.
        /// </summary>
        [RepositoryFolder("0225c3af-d53e-459d-a4fb-04efbec785e7")]
        public virtual TimeSheetsFolders.FindFilesFormAppFolder FindFilesForm
        {
            get { return _findfilesform; }
        }

        /// <summary>
        /// The TimeEntryDetailsForm folder.
        /// </summary>
        [RepositoryFolder("aee49648-b315-437a-833d-be9ec8f75a1a")]
        public virtual TimeSheetsFolders.TimeEntryDetailsFormAppFolder TimeEntryDetailsForm
        {
            get { return _timeentrydetailsform; }
        }

        /// <summary>
        /// The PromptForm folder.
        /// </summary>
        [RepositoryFolder("2b7f02df-64ac-4236-8f02-bdc8bf5e1ecf")]
        public virtual TimeSheetsFolders.PromptFormAppFolder PromptForm
        {
            get { return _promptform; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class TimeSheetsFolders
    {
        /// <summary>
        /// The MainFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("06770a82-01be-4808-b2e8-13542b61f153")]
        public partial class MainFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btntimesheetsInfo;
            RepoItemInfo _btnaddtimeentryInfo;
            RepoItemInfo _listfirstposteditemInfo;
            RepoItemInfo _btntimesheets1Info;

            /// <summary>
            /// Creates a new MainForm  folder.
            /// </summary>
            public MainFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MainForm", "/form[@controlname='MainForm']", parentFolder, 30000, null, true, "06770a82-01be-4808-b2e8-13542b61f153", "")
            {
                _btntimesheetsInfo = new RepoItemInfo(this, "btnTimeSheets", "container[@controlname='pLeft']//tree[@accessiblerole='Outline']/button[@accessiblename='Time Sheets']", 30000, null, "efb70690-bcef-4af5-b395-4f24859a9063");
                _btnaddtimeentryInfo = new RepoItemInfo(this, "btnAddTimeEntry", "?/?/form[@controlname='TimeIndexForm']/container[@controlname='menubar_Fill_Panel']//toolbar[@accessiblename='Toolbar']/button[@accessiblename='New']", 30000, null, "6da3dfde-88ca-4519-ae00-d85612d08dbd");
                _listfirstposteditemInfo = new RepoItemInfo(this, "listFirstPostedItem", "?/?/form[@controlname='TimeIndexForm']/container[@controlname='pWholePage']/?/?/container[@controlname='pUnpostedView']/?/?/element[@controlname='atgUnposted']/table[@accessiblerole='Table']/row[1]/cell[@accessiblename='File']", 30000, null, "aac7827b-fecc-467a-9ae9-c590140e15d7");
                _btntimesheets1Info = new RepoItemInfo(this, "btnTimeSheets1", "?/?/tree[@accessiblerole='Outline']/button[@accessiblename='Time Sheets']", 5000, null, "3f72aab3-d0d1-477e-8c81-f6e8bf4738da");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("06770a82-01be-4808-b2e8-13542b61f153")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("06770a82-01be-4808-b2e8-13542b61f153")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btnTimeSheets item.
            /// </summary>
            [RepositoryItem("efb70690-bcef-4af5-b395-4f24859a9063")]
            public virtual Ranorex.Button btnTimeSheets
            {
                get
                {
                    return _btntimesheetsInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnTimeSheets item info.
            /// </summary>
            [RepositoryItemInfo("efb70690-bcef-4af5-b395-4f24859a9063")]
            public virtual RepoItemInfo btnTimeSheetsInfo
            {
                get
                {
                    return _btntimesheetsInfo;
                }
            }

            /// <summary>
            /// The btnAddTimeEntry item.
            /// </summary>
            [RepositoryItem("6da3dfde-88ca-4519-ae00-d85612d08dbd")]
            public virtual Ranorex.Button btnAddTimeEntry
            {
                get
                {
                    return _btnaddtimeentryInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnAddTimeEntry item info.
            /// </summary>
            [RepositoryItemInfo("6da3dfde-88ca-4519-ae00-d85612d08dbd")]
            public virtual RepoItemInfo btnAddTimeEntryInfo
            {
                get
                {
                    return _btnaddtimeentryInfo;
                }
            }

            /// <summary>
            /// The listFirstPostedItem item.
            /// </summary>
            [RepositoryItem("aac7827b-fecc-467a-9ae9-c590140e15d7")]
            public virtual Ranorex.Cell listFirstPostedItem
            {
                get
                {
                    return _listfirstposteditemInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The listFirstPostedItem item info.
            /// </summary>
            [RepositoryItemInfo("aac7827b-fecc-467a-9ae9-c590140e15d7")]
            public virtual RepoItemInfo listFirstPostedItemInfo
            {
                get
                {
                    return _listfirstposteditemInfo;
                }
            }

            /// <summary>
            /// The btnTimeSheets1 item.
            /// </summary>
            [RepositoryItem("3f72aab3-d0d1-477e-8c81-f6e8bf4738da")]
            public virtual Ranorex.Button btnTimeSheets1
            {
                get
                {
                    return _btntimesheets1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnTimeSheets1 item info.
            /// </summary>
            [RepositoryItemInfo("3f72aab3-d0d1-477e-8c81-f6e8bf4738da")]
            public virtual RepoItemInfo btnTimeSheets1Info
            {
                get
                {
                    return _btntimesheets1Info;
                }
            }
        }

        /// <summary>
        /// The FileSelectFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("9c7ff0e1-6bb3-49b2-abdb-acfc29c6e504")]
        public partial class FileSelectFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btnquickfindInfo;
            RepoItemInfo _listfirstfoundfileInfo;

            /// <summary>
            /// Creates a new FileSelectForm  folder.
            /// </summary>
            public FileSelectFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FileSelectForm", "/form[@controlname='FileSelectForm']", parentFolder, 30000, null, true, "9c7ff0e1-6bb3-49b2-abdb-acfc29c6e504", "")
            {
                _btnquickfindInfo = new RepoItemInfo(this, "btnQuickFind", ".//toolbar[@accessiblename='Toolbar']/button[@accessiblename='QuickFind']", 30000, null, "f8b4195e-dbe6-45ec-bf6e-68cebb61f1cd");
                _listfirstfoundfileInfo = new RepoItemInfo(this, "listFirstFoundFile", "container[@controlname='panel1']//row[@accessiblename='Band 0 row 1']/cell[@accessiblename='File']", 30000, null, "7022b914-9478-451b-a51d-bf5fb507eb8b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9c7ff0e1-6bb3-49b2-abdb-acfc29c6e504")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9c7ff0e1-6bb3-49b2-abdb-acfc29c6e504")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btnQuickFind item.
            /// </summary>
            [RepositoryItem("f8b4195e-dbe6-45ec-bf6e-68cebb61f1cd")]
            public virtual Ranorex.Button btnQuickFind
            {
                get
                {
                    return _btnquickfindInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnQuickFind item info.
            /// </summary>
            [RepositoryItemInfo("f8b4195e-dbe6-45ec-bf6e-68cebb61f1cd")]
            public virtual RepoItemInfo btnQuickFindInfo
            {
                get
                {
                    return _btnquickfindInfo;
                }
            }

            /// <summary>
            /// The listFirstFoundFile item.
            /// </summary>
            [RepositoryItem("7022b914-9478-451b-a51d-bf5fb507eb8b")]
            public virtual Ranorex.Cell listFirstFoundFile
            {
                get
                {
                    return _listfirstfoundfileInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The listFirstFoundFile item info.
            /// </summary>
            [RepositoryItemInfo("7022b914-9478-451b-a51d-bf5fb507eb8b")]
            public virtual RepoItemInfo listFirstFoundFileInfo
            {
                get
                {
                    return _listfirstfoundfileInfo;
                }
            }
        }

        /// <summary>
        /// The FindFilesFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("0225c3af-d53e-459d-a4fb-04efbec785e7")]
        public partial class FindFilesFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _txtfindfileInfo;
            RepoItemInfo _btnokInfo;

            /// <summary>
            /// Creates a new FindFilesForm  folder.
            /// </summary>
            public FindFilesFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FindFilesForm", "/form[@controlname='FindFilesForm']", parentFolder, 30000, null, true, "0225c3af-d53e-459d-a4fb-04efbec785e7", "")
            {
                _txtfindfileInfo = new RepoItemInfo(this, "txtFindFile", "container[@controlname='pnlBase']//text[@automationid='atxtSearch_EmbeddableTextBox']", 30000, null, "ba81b74e-f1b2-4eda-bb6e-2e81ed7266a9");
                _btnokInfo = new RepoItemInfo(this, "btnOK", ".//toolbar[@accessiblename='Toolbar']/button[@accessiblename='OK']", 30000, null, "f3a1a325-0f68-4cf8-a9ea-e13112f864cb");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("0225c3af-d53e-459d-a4fb-04efbec785e7")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("0225c3af-d53e-459d-a4fb-04efbec785e7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The txtFindFile item.
            /// </summary>
            [RepositoryItem("ba81b74e-f1b2-4eda-bb6e-2e81ed7266a9")]
            public virtual Ranorex.Text txtFindFile
            {
                get
                {
                    return _txtfindfileInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txtFindFile item info.
            /// </summary>
            [RepositoryItemInfo("ba81b74e-f1b2-4eda-bb6e-2e81ed7266a9")]
            public virtual RepoItemInfo txtFindFileInfo
            {
                get
                {
                    return _txtfindfileInfo;
                }
            }

            /// <summary>
            /// The btnOK item.
            /// </summary>
            [RepositoryItem("f3a1a325-0f68-4cf8-a9ea-e13112f864cb")]
            public virtual Ranorex.Button btnOK
            {
                get
                {
                    return _btnokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnOK item info.
            /// </summary>
            [RepositoryItemInfo("f3a1a325-0f68-4cf8-a9ea-e13112f864cb")]
            public virtual RepoItemInfo btnOKInfo
            {
                get
                {
                    return _btnokInfo;
                }
            }
        }

        /// <summary>
        /// The TimeEntryDetailsFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("aee49648-b315-437a-833d-be9ec8f75a1a")]
        public partial class TimeEntryDetailsFormAppFolder : RepoGenBaseFolder
        {
            TimeSheetsFolders.MenubarFillPanelFolder _menubarfillpanel;

            /// <summary>
            /// Creates a new TimeEntryDetailsForm  folder.
            /// </summary>
            public TimeEntryDetailsFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("TimeEntryDetailsForm", "/form[@controlname='TimeEntryDetailsForm']", parentFolder, 30000, null, true, "aee49648-b315-437a-833d-be9ec8f75a1a", "")
            {
                _menubarfillpanel = new TimeSheetsFolders.MenubarFillPanelFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("aee49648-b315-437a-833d-be9ec8f75a1a")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("aee49648-b315-437a-833d-be9ec8f75a1a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MenubarFillPanel folder.
            /// </summary>
            [RepositoryFolder("b15cd08d-52c1-474e-974b-68622d0c934f")]
            public virtual TimeSheetsFolders.MenubarFillPanelFolder MenubarFillPanel
            {
                get { return _menubarfillpanel; }
            }
        }

        /// <summary>
        /// The MenubarFillPanelFolder folder.
        /// </summary>
        [RepositoryFolder("b15cd08d-52c1-474e-974b-68622d0c934f")]
        public partial class MenubarFillPanelFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btndeleteInfo;
            RepoItemInfo _btnokInfo;
            RepoItemInfo _txtactivitydescriptionInfo;

            /// <summary>
            /// Creates a new MenubarFillPanel  folder.
            /// </summary>
            public MenubarFillPanelFolder(RepoGenBaseFolder parentFolder) :
                    base("MenubarFillPanel", "container[@controlname='menubar_Fill_Panel']", parentFolder, 30000, null, false, "b15cd08d-52c1-474e-974b-68622d0c934f", "")
            {
                _btndeleteInfo = new RepoItemInfo(this, "btnDelete", ".//toolbar[@accessiblename='Toolbar']/button[@accessiblename='Delete']", 30000, null, "8f9294a3-faa6-49b3-a8c1-2ed8eac5bbed");
                _btnokInfo = new RepoItemInfo(this, "btnOK", ".//toolbar[@accessiblename='Toolbar']/button[@accessiblename='OK']", 30000, null, "4f20d236-7378-421e-86e0-e62e616ab5e4");
                _txtactivitydescriptionInfo = new RepoItemInfo(this, "txtActivityDescription", "container[@controlname='pnlBase']//container[@controlname='panel1']/?/?/element[@controlname='uteDescription']/?/?/text[@accessiblerole='Text']", 30000, null, "6bd3a6ae-0de8-4776-bceb-8c88ec630ec2");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b15cd08d-52c1-474e-974b-68622d0c934f")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b15cd08d-52c1-474e-974b-68622d0c934f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btnDelete item.
            /// </summary>
            [RepositoryItem("8f9294a3-faa6-49b3-a8c1-2ed8eac5bbed")]
            public virtual Ranorex.Button btnDelete
            {
                get
                {
                    return _btndeleteInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnDelete item info.
            /// </summary>
            [RepositoryItemInfo("8f9294a3-faa6-49b3-a8c1-2ed8eac5bbed")]
            public virtual RepoItemInfo btnDeleteInfo
            {
                get
                {
                    return _btndeleteInfo;
                }
            }

            /// <summary>
            /// The btnOK item.
            /// </summary>
            [RepositoryItem("4f20d236-7378-421e-86e0-e62e616ab5e4")]
            public virtual Ranorex.Button btnOK
            {
                get
                {
                    return _btnokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnOK item info.
            /// </summary>
            [RepositoryItemInfo("4f20d236-7378-421e-86e0-e62e616ab5e4")]
            public virtual RepoItemInfo btnOKInfo
            {
                get
                {
                    return _btnokInfo;
                }
            }

            /// <summary>
            /// The txtActivityDescription item.
            /// </summary>
            [RepositoryItem("6bd3a6ae-0de8-4776-bceb-8c88ec630ec2")]
            public virtual Ranorex.Text txtActivityDescription
            {
                get
                {
                    return _txtactivitydescriptionInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The txtActivityDescription item info.
            /// </summary>
            [RepositoryItemInfo("6bd3a6ae-0de8-4776-bceb-8c88ec630ec2")]
            public virtual RepoItemInfo txtActivityDescriptionInfo
            {
                get
                {
                    return _txtactivitydescriptionInfo;
                }
            }
        }

        /// <summary>
        /// The PromptFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("2b7f02df-64ac-4236-8f02-bdc8bf5e1ecf")]
        public partial class PromptFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btnyesInfo;

            /// <summary>
            /// Creates a new PromptForm  folder.
            /// </summary>
            public PromptFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("PromptForm", "/form[@controlname='PromptForm']", parentFolder, 30000, null, true, "2b7f02df-64ac-4236-8f02-bdc8bf5e1ecf", "")
            {
                _btnyesInfo = new RepoItemInfo(this, "btnYes", ".//toolbar[@accessiblename='Toolbar']/button[@accessiblename='Yes']", 30000, null, "dc8e7913-f4ea-44e2-b251-1bc736f023ad");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2b7f02df-64ac-4236-8f02-bdc8bf5e1ecf")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2b7f02df-64ac-4236-8f02-bdc8bf5e1ecf")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btnYes item.
            /// </summary>
            [RepositoryItem("dc8e7913-f4ea-44e2-b251-1bc736f023ad")]
            public virtual Ranorex.Button btnYes
            {
                get
                {
                    return _btnyesInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnYes item info.
            /// </summary>
            [RepositoryItemInfo("dc8e7913-f4ea-44e2-b251-1bc736f023ad")]
            public virtual RepoItemInfo btnYesInfo
            {
                get
                {
                    return _btnyesInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
