///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace SmokeTest.Repositories.Premium
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the EventDetails element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("ec074c12-60f6-407f-be31-b44f3c4ac001")]
    public partial class EventDetails : RepoGenBaseFolder
    {
        static EventDetails instance = new EventDetails();
        EventDetailsFolders.EventDetailFormAppFolder _eventdetailform;
        EventDetailsFolders.AppointmentOverlapDialogAppFolder _appointmentoverlapdialog;

        /// <summary>
        /// Gets the singleton class instance representing the EventDetails element repository.
        /// </summary>
        [RepositoryFolder("ec074c12-60f6-407f-be31-b44f3c4ac001")]
        public static EventDetails Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public EventDetails() 
            : base("EventDetails", "/", null, 0, false, "ec074c12-60f6-407f-be31-b44f3c4ac001", ".\\RepositoryImages\\EventDetailsec074c12.rximgres")
        {
            _eventdetailform = new EventDetailsFolders.EventDetailFormAppFolder(this);
            _appointmentoverlapdialog = new EventDetailsFolders.AppointmentOverlapDialogAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("ec074c12-60f6-407f-be31-b44f3c4ac001")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The EventDetailForm folder.
        /// </summary>
        [RepositoryFolder("88830301-b9f2-45ca-bb75-55a9bf7b3c82")]
        public virtual EventDetailsFolders.EventDetailFormAppFolder EventDetailForm
        {
            get { return _eventdetailform; }
        }

        /// <summary>
        /// The AppointmentOverlapDialog folder.
        /// </summary>
        [RepositoryFolder("bc0ac824-ede8-4224-bb55-de9ac345f055")]
        public virtual EventDetailsFolders.AppointmentOverlapDialogAppFolder AppointmentOverlapDialog
        {
            get { return _appointmentoverlapdialog; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class EventDetailsFolders
    {
        /// <summary>
        /// The EventDetailFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("88830301-b9f2-45ca-bb75-55a9bf7b3c82")]
        public partial class EventDetailFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _titleInfo;
            RepoItemInfo _okbtnInfo;

            /// <summary>
            /// Creates a new EventDetailForm  folder.
            /// </summary>
            public EventDetailFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("EventDetailForm", "/form[@controlname='EventDetailForm']", parentFolder, 30000, null, true, "88830301-b9f2-45ca-bb75-55a9bf7b3c82", "")
            {
                _titleInfo = new RepoItemInfo(this, "Title", ".//element[@controlname='txtTitle']/text", 30000, null, "d9ae15ed-83c2-4784-aae7-a70b1f8b2f0b");
                _okbtnInfo = new RepoItemInfo(this, "OkBtn", ".//button[@name='OK']", 30000, null, "1e2ac88f-5d58-4066-a59e-01e8e96808fc");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("88830301-b9f2-45ca-bb75-55a9bf7b3c82")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("88830301-b9f2-45ca-bb75-55a9bf7b3c82")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Title item.
            /// </summary>
            [RepositoryItem("d9ae15ed-83c2-4784-aae7-a70b1f8b2f0b")]
            public virtual Ranorex.Text Title
            {
                get
                {
                    return _titleInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Title item info.
            /// </summary>
            [RepositoryItemInfo("d9ae15ed-83c2-4784-aae7-a70b1f8b2f0b")]
            public virtual RepoItemInfo TitleInfo
            {
                get
                {
                    return _titleInfo;
                }
            }

            /// <summary>
            /// The OkBtn item.
            /// </summary>
            [RepositoryItem("1e2ac88f-5d58-4066-a59e-01e8e96808fc")]
            public virtual Ranorex.Button OkBtn
            {
                get
                {
                    return _okbtnInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The OkBtn item info.
            /// </summary>
            [RepositoryItemInfo("1e2ac88f-5d58-4066-a59e-01e8e96808fc")]
            public virtual RepoItemInfo OkBtnInfo
            {
                get
                {
                    return _okbtnInfo;
                }
            }
        }

        /// <summary>
        /// The AppointmentOverlapDialogAppFolder folder.
        /// </summary>
        [RepositoryFolder("bc0ac824-ede8-4224-bb55-de9ac345f055")]
        public partial class AppointmentOverlapDialogAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _radiookInfo;
            RepoItemInfo _okbtnInfo;

            /// <summary>
            /// Creates a new AppointmentOverlapDialog  folder.
            /// </summary>
            public AppointmentOverlapDialogAppFolder(RepoGenBaseFolder parentFolder) :
                    base("AppointmentOverlapDialog", "/form[@controlname='AppointmentOverlapDialog']", parentFolder, 30000, null, true, "bc0ac824-ede8-4224-bb55-de9ac345f055", "")
            {
                _radiookInfo = new RepoItemInfo(this, "RadioOK", ".//radiobutton[@text='It''s OK']", 30000, null, "19e5a5c3-905b-44ab-b575-1393e00f611c");
                _okbtnInfo = new RepoItemInfo(this, "OkBtn", ".//button[@name='OK']", 30000, null, "46e96077-f853-4975-a69d-562f6a0a6ad1");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("bc0ac824-ede8-4224-bb55-de9ac345f055")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("bc0ac824-ede8-4224-bb55-de9ac345f055")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RadioOK item.
            /// </summary>
            [RepositoryItem("19e5a5c3-905b-44ab-b575-1393e00f611c")]
            public virtual Ranorex.RadioButton RadioOK
            {
                get
                {
                    return _radiookInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The RadioOK item info.
            /// </summary>
            [RepositoryItemInfo("19e5a5c3-905b-44ab-b575-1393e00f611c")]
            public virtual RepoItemInfo RadioOKInfo
            {
                get
                {
                    return _radiookInfo;
                }
            }

            /// <summary>
            /// The OkBtn item.
            /// </summary>
            [RepositoryItem("46e96077-f853-4975-a69d-562f6a0a6ad1")]
            public virtual Ranorex.Button OkBtn
            {
                get
                {
                    return _okbtnInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The OkBtn item info.
            /// </summary>
            [RepositoryItemInfo("46e96077-f853-4975-a69d-562f6a0a6ad1")]
            public virtual RepoItemInfo OkBtnInfo
            {
                get
                {
                    return _okbtnInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
