///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace SmokeTest.Repositories.Premium
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Preferences element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("1fe12d41-786a-4c53-98a2-c7ba0cd425e8")]
    public partial class Preferences : RepoGenBaseFolder
    {
        static Preferences instance = new Preferences();
        PreferencesFolders.MainFormAppFolder _mainform;
        PreferencesFolders.GeneralPreferencesFormAppFolder _generalpreferencesform;
        PreferencesFolders.EmailPreferencesFormAppFolder _emailpreferencesform;
        PreferencesFolders.PromptFormAppFolder _promptform;

        /// <summary>
        /// Gets the singleton class instance representing the Preferences element repository.
        /// </summary>
        [RepositoryFolder("1fe12d41-786a-4c53-98a2-c7ba0cd425e8")]
        public static Preferences Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Preferences() 
            : base("Preferences", "/", null, 0, false, "1fe12d41-786a-4c53-98a2-c7ba0cd425e8", ".\\RepositoryImages\\Preferences1fe12d41.rximgres")
        {
            _mainform = new PreferencesFolders.MainFormAppFolder(this);
            _generalpreferencesform = new PreferencesFolders.GeneralPreferencesFormAppFolder(this);
            _emailpreferencesform = new PreferencesFolders.EmailPreferencesFormAppFolder(this);
            _promptform = new PreferencesFolders.PromptFormAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("1fe12d41-786a-4c53-98a2-c7ba0cd425e8")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The MainForm folder.
        /// </summary>
        [RepositoryFolder("b9a82f60-19c0-4379-9e4c-c1c2e71f4bb6")]
        public virtual PreferencesFolders.MainFormAppFolder MainForm
        {
            get { return _mainform; }
        }

        /// <summary>
        /// The GeneralPreferencesForm folder.
        /// </summary>
        [RepositoryFolder("bea9971f-6b2b-4fc3-a039-98b032aa9102")]
        public virtual PreferencesFolders.GeneralPreferencesFormAppFolder GeneralPreferencesForm
        {
            get { return _generalpreferencesform; }
        }

        /// <summary>
        /// The EmailPreferencesForm folder.
        /// </summary>
        [RepositoryFolder("8f89f9d5-6bb3-4d24-9785-550bec029a33")]
        public virtual PreferencesFolders.EmailPreferencesFormAppFolder EmailPreferencesForm
        {
            get { return _emailpreferencesform; }
        }

        /// <summary>
        /// The PromptForm folder.
        /// </summary>
        [RepositoryFolder("bc5b262c-9b08-4061-b61d-1a018c35ee93")]
        public virtual PreferencesFolders.PromptFormAppFolder PromptForm
        {
            get { return _promptform; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class PreferencesFolders
    {
        /// <summary>
        /// The MainFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("b9a82f60-19c0-4379-9e4c-c1c2e71f4bb6")]
        public partial class MainFormAppFolder : RepoGenBaseFolder
        {
            PreferencesFolders.PreferencesFormFolder _preferencesform;
            RepoItemInfo _preferencesform1Info;
            RepoItemInfo _preferencesInfo;
            RepoItemInfo _emailInfo;
            RepoItemInfo _calendarcontactsInfo;
            RepoItemInfo _officemoduleInfo;
            RepoItemInfo _officemoduleheaderInfo;

            /// <summary>
            /// Creates a new MainForm  folder.
            /// </summary>
            public MainFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MainForm", "/form[@controlname='MainForm']", parentFolder, 5000, null, true, "b9a82f60-19c0-4379-9e4c-c1c2e71f4bb6", "")
            {
                _preferencesform = new PreferencesFolders.PreferencesFormFolder(this);
                _preferencesform1Info = new RepoItemInfo(this, "PreferencesForm1", "?/?/form[@controlname='PreferencesForm']/container[@controlname='roundedPanelControl']/container[@controlname='panelScroll']", 30000, null, "8d684eba-a662-47cc-8a75-81babbd90865");
                _preferencesInfo = new RepoItemInfo(this, "Preferences", "container[@controlname='pLeft']//container[@controltypename='UltraExplorerBarContainerControl' and @instance='0']/?/?/container[@controlname='OfficeControlPanel']/?/?/container[@controlname='panelParent']/container[@controltypename='Panel' and @instance='1']/?/?/text[@accessiblename='Preferences']", 5000, null, "e8070780-ea94-40d3-b0f8-705ceb778f02");
                _emailInfo = new RepoItemInfo(this, "Email", "?/?/form[@controlname='PreferencesForm']//element[@controlname='amlblGeneralEmail']/text[@accessiblerole='StaticText']", 5000, null, "cbbae7a3-84c7-42bd-bc53-a5a606c50c26");
                _calendarcontactsInfo = new RepoItemInfo(this, "CalendarContacts", "?/?/form[@controlname='PreferencesForm']//element[@controlname='amlblGeneralOutlookLink']/text[@accessiblerole='StaticText']", 5000, null, "f9a4d701-e8b7-468b-a742-e4a7f6bd6467");
                _officemoduleInfo = new RepoItemInfo(this, "OfficeModule", "container[@controlname='pLeft']//container[@name='Office']", 30000, null, "d2a47121-362f-434c-8f1d-236b0154cfeb");
                _officemoduleheaderInfo = new RepoItemInfo(this, "OfficeModuleHeader", "container[@controlname='pLeft']//container[@controltypename='UltraExplorerBarContainerControl' and @instance='0']/container[@controlname='controlPanelWrapper']/?/?/text[@accessiblename='Office']", 30000, null, "32e9d3c2-bb77-47c7-8c58-58006e26c75f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b9a82f60-19c0-4379-9e4c-c1c2e71f4bb6")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b9a82f60-19c0-4379-9e4c-c1c2e71f4bb6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The PreferencesForm1 item.
            /// </summary>
            [RepositoryItem("8d684eba-a662-47cc-8a75-81babbd90865")]
            public virtual Ranorex.Container PreferencesForm1
            {
                get
                {
                    return _preferencesform1Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The PreferencesForm1 item info.
            /// </summary>
            [RepositoryItemInfo("8d684eba-a662-47cc-8a75-81babbd90865")]
            public virtual RepoItemInfo PreferencesForm1Info
            {
                get
                {
                    return _preferencesform1Info;
                }
            }

            /// <summary>
            /// The Preferences item.
            /// </summary>
            [RepositoryItem("e8070780-ea94-40d3-b0f8-705ceb778f02")]
            public virtual Ranorex.Text Preferences
            {
                get
                {
                    return _preferencesInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Preferences item info.
            /// </summary>
            [RepositoryItemInfo("e8070780-ea94-40d3-b0f8-705ceb778f02")]
            public virtual RepoItemInfo PreferencesInfo
            {
                get
                {
                    return _preferencesInfo;
                }
            }

            /// <summary>
            /// The Email item.
            /// </summary>
            [RepositoryItem("cbbae7a3-84c7-42bd-bc53-a5a606c50c26")]
            public virtual Ranorex.Text Email
            {
                get
                {
                    return _emailInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Email item info.
            /// </summary>
            [RepositoryItemInfo("cbbae7a3-84c7-42bd-bc53-a5a606c50c26")]
            public virtual RepoItemInfo EmailInfo
            {
                get
                {
                    return _emailInfo;
                }
            }

            /// <summary>
            /// The CalendarContacts item.
            /// </summary>
            [RepositoryItem("f9a4d701-e8b7-468b-a742-e4a7f6bd6467")]
            public virtual Ranorex.Text CalendarContacts
            {
                get
                {
                    return _calendarcontactsInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The CalendarContacts item info.
            /// </summary>
            [RepositoryItemInfo("f9a4d701-e8b7-468b-a742-e4a7f6bd6467")]
            public virtual RepoItemInfo CalendarContactsInfo
            {
                get
                {
                    return _calendarcontactsInfo;
                }
            }

            /// <summary>
            /// The OfficeModule item.
            /// </summary>
            [RepositoryItem("d2a47121-362f-434c-8f1d-236b0154cfeb")]
            public virtual Ranorex.Container OfficeModule
            {
                get
                {
                    return _officemoduleInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The OfficeModule item info.
            /// </summary>
            [RepositoryItemInfo("d2a47121-362f-434c-8f1d-236b0154cfeb")]
            public virtual RepoItemInfo OfficeModuleInfo
            {
                get
                {
                    return _officemoduleInfo;
                }
            }

            /// <summary>
            /// The OfficeModuleHeader item.
            /// </summary>
            [RepositoryItem("32e9d3c2-bb77-47c7-8c58-58006e26c75f")]
            public virtual Ranorex.Text OfficeModuleHeader
            {
                get
                {
                    return _officemoduleheaderInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The OfficeModuleHeader item info.
            /// </summary>
            [RepositoryItemInfo("32e9d3c2-bb77-47c7-8c58-58006e26c75f")]
            public virtual RepoItemInfo OfficeModuleHeaderInfo
            {
                get
                {
                    return _officemoduleheaderInfo;
                }
            }

            /// <summary>
            /// The PreferencesForm folder.
            /// </summary>
            [RepositoryFolder("51a9509f-d199-47be-831d-9bcc53aa483d")]
            public virtual PreferencesFolders.PreferencesFormFolder PreferencesForm
            {
                get { return _preferencesform; }
            }
        }

        /// <summary>
        /// The PreferencesFormFolder folder.
        /// </summary>
        [RepositoryFolder("51a9509f-d199-47be-831d-9bcc53aa483d")]
        public partial class PreferencesFormFolder : RepoGenBaseFolder
        {
            RepoItemInfo _myprofileInfo;
            RepoItemInfo _myworkgroupInfo;
            RepoItemInfo _defaultsonloginInfo;
            RepoItemInfo _toolbarsInfo;
            RepoItemInfo _spellcheckInfo;
            RepoItemInfo _dailiespagesInfo;
            RepoItemInfo _todayspracticeInfo;
            RepoItemInfo _filesdisplayInfo;
            RepoItemInfo _filesnewentriesInfo;
            RepoItemInfo _calendardisplayInfo;
            RepoItemInfo _calendarnewentriesInfo;
            RepoItemInfo _calendarotherInfo;
            RepoItemInfo _peopledisplayInfo;
            RepoItemInfo _peoplenewentriesInfo;
            RepoItemInfo _managementInfo;
            RepoItemInfo _documentassemblyInfo;
            RepoItemInfo _billingratesInfo;
            RepoItemInfo _timenewentriesInfo;
            RepoItemInfo _timerInfo;
            RepoItemInfo _formattingInfo;
            RepoItemInfo _activitycodesInfo;
            RepoItemInfo _fiscalInfo;
            RepoItemInfo _generalInfo;
            RepoItemInfo _messagesInfo;
            RepoItemInfo _defaultsInfo;

            /// <summary>
            /// Creates a new PreferencesForm  folder.
            /// </summary>
            public PreferencesFormFolder(RepoGenBaseFolder parentFolder) :
                    base("PreferencesForm", "?/?/form[@controlname='PreferencesForm']", parentFolder, 5000, null, false, "51a9509f-d199-47be-831d-9bcc53aa483d", "")
            {
                _myprofileInfo = new RepoItemInfo(this, "MyProfile", ".//element[@controlname='amlblGeneralMyProfile']/text[@accessiblerole='StaticText']", 5000, null, "bdf654ef-5b45-4cb7-a675-e014d0a6ed76");
                _myworkgroupInfo = new RepoItemInfo(this, "MyWorkgroup", ".//element[@controlname='amlblGeneralMyWorkgroup']/text[@accessiblerole='StaticText']", 5000, null, "8fbf422a-d071-4b96-b085-874206506cc6");
                _defaultsonloginInfo = new RepoItemInfo(this, "DefaultsOnLogin", ".//element[@controlname='amlblMyAppDefaultsOnLogin']/text[@accessiblerole='StaticText']", 5000, null, "f8a82c45-71a0-447c-a11a-6d6c8b96280e");
                _toolbarsInfo = new RepoItemInfo(this, "Toolbars", ".//element[@controlname='amlblMyAppGraphics']/text[@accessiblerole='StaticText']", 5000, null, "3da96d11-f3da-479b-b86d-e7e649980a55");
                _spellcheckInfo = new RepoItemInfo(this, "SpellCheck", ".//element[@controlname='amlblSpellCheck']/text[@accessiblerole='StaticText']", 5000, null, "01f79284-e8f9-427e-a9d6-0cc067dfe06e");
                _dailiespagesInfo = new RepoItemInfo(this, "DailiesPages", ".//element[@controlname='amlblDailiesPages']/text[@accessiblerole='StaticText']", 5000, null, "7b54a7fb-bbfa-484d-bc7a-7d054c5512ec");
                _todayspracticeInfo = new RepoItemInfo(this, "TodaysPractice", ".//element[@controlname='amlblTodaysPractice']/text[@accessiblerole='StaticText']", 5000, null, "06845597-6890-4cb9-8460-e08a58cfa6eb");
                _filesdisplayInfo = new RepoItemInfo(this, "FilesDisplay", ".//element[@controlname='amlblFilesDisplay']/text[@accessiblerole='StaticText']", 5000, null, "3031251f-2c38-4ac0-af25-e226fe85d0f1");
                _filesnewentriesInfo = new RepoItemInfo(this, "FilesNewEntries", ".//element[@controlname='amlblFilesNewEntries']/text[@accessiblerole='StaticText']", 5000, null, "73aff468-cd69-47d8-b5cc-ed6439c604ab");
                _calendardisplayInfo = new RepoItemInfo(this, "CalendarDisplay", ".//element[@controlname='amlblCalendarDisplay']/text[@accessiblerole='StaticText']", 5000, null, "cd34b429-d223-4311-a3bb-6f96c65c1aef");
                _calendarnewentriesInfo = new RepoItemInfo(this, "CalendarNewEntries", ".//element[@controlname='amlblCalendarNewEntries']/text[@accessiblerole='StaticText']", 5000, null, "ab2cab22-e570-4116-9e38-223503984341");
                _calendarotherInfo = new RepoItemInfo(this, "CalendarOther", ".//element[@controlname='amlblCalendarOther']/text[@accessiblerole='StaticText']", 5000, null, "fde81265-6280-4857-af5f-93f5a527f9a4");
                _peopledisplayInfo = new RepoItemInfo(this, "PeopleDisplay", ".//element[@controlname='amlblPeopleDisplay']/text[@accessiblerole='StaticText']", 5000, null, "78717a41-3037-43e4-a7e8-6dcc5dff0796");
                _peoplenewentriesInfo = new RepoItemInfo(this, "PeopleNewEntries", ".//element[@controlname='amlblPeopleNewEntries']/text[@accessiblerole='StaticText']", 5000, null, "621a0c44-3b7f-4dc9-b1e1-c9e4fa5d1a14");
                _managementInfo = new RepoItemInfo(this, "Management", ".//element[@controlname='amlblManagement']/text[@accessiblerole='StaticText']", 5000, null, "f8c8e163-3e6e-47cf-8bc9-f40933f2132f");
                _documentassemblyInfo = new RepoItemInfo(this, "DocumentAssembly", ".//element[@controlname='amlblDocumentAssembly']/text[@accessiblerole='StaticText']", 5000, null, "e8cff8b4-3af0-4182-8276-3c7d3858ee1d");
                _billingratesInfo = new RepoItemInfo(this, "BillingRates", ".//element[@controlname='amlblTimeBillingRates']/text[@accessiblerole='StaticText']", 5000, null, "caf44723-297d-448d-ac7d-1aa266b644d8");
                _timenewentriesInfo = new RepoItemInfo(this, "TimeNewEntries", ".//element[@controlname='amlblTimeNewEntries']/text[@accessiblerole='StaticText']", 5000, null, "4b8de679-31ff-4a86-881c-9a88f4041c08");
                _timerInfo = new RepoItemInfo(this, "Timer", ".//element[@controlname='amlblTimeTimer']/text[@accessiblerole='StaticText']", 5000, null, "b204d13a-872b-48d7-a802-f2924aa83f74");
                _formattingInfo = new RepoItemInfo(this, "Formatting", ".//element[@controlname='amlblTimeFormatting']/text[@accessiblerole='StaticText']", 5000, null, "e9653e86-2c18-4982-bc85-c9e25c289a73");
                _activitycodesInfo = new RepoItemInfo(this, "ActivityCodes", ".//element[@controlname='amlblTimeActivityCodes']/text[@accessiblerole='StaticText']", 5000, null, "fce08a3f-7f7f-492c-bf66-07c14baec5fe");
                _fiscalInfo = new RepoItemInfo(this, "Fiscal", ".//element[@controlname='amlblTimeStatistics']/text[@accessiblerole='StaticText']", 5000, null, "963b7afb-dd77-4606-afdb-3932f2f4c69c");
                _generalInfo = new RepoItemInfo(this, "General", ".//element[@controlname='amlblGeneral']/text[@accessiblerole='StaticText']", 5000, null, "535f0fa4-fd5f-482a-93da-915fcd16795a");
                _messagesInfo = new RepoItemInfo(this, "Messages", ".//element[@controlname='amlblMessages']/text[@accessiblerole='StaticText']", 5000, null, "0773a48b-9809-43c9-9888-2c4e4987e390");
                _defaultsInfo = new RepoItemInfo(this, "Defaults", ".//element[@controlname='amlblDefaults']/text[@accessiblerole='StaticText']", 5000, null, "49b0dc2b-240e-48be-88d9-abde2fedc3e0");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("51a9509f-d199-47be-831d-9bcc53aa483d")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("51a9509f-d199-47be-831d-9bcc53aa483d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MyProfile item.
            /// </summary>
            [RepositoryItem("bdf654ef-5b45-4cb7-a675-e014d0a6ed76")]
            public virtual Ranorex.Text MyProfile
            {
                get
                {
                    return _myprofileInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The MyProfile item info.
            /// </summary>
            [RepositoryItemInfo("bdf654ef-5b45-4cb7-a675-e014d0a6ed76")]
            public virtual RepoItemInfo MyProfileInfo
            {
                get
                {
                    return _myprofileInfo;
                }
            }

            /// <summary>
            /// The MyWorkgroup item.
            /// </summary>
            [RepositoryItem("8fbf422a-d071-4b96-b085-874206506cc6")]
            public virtual Ranorex.Text MyWorkgroup
            {
                get
                {
                    return _myworkgroupInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The MyWorkgroup item info.
            /// </summary>
            [RepositoryItemInfo("8fbf422a-d071-4b96-b085-874206506cc6")]
            public virtual RepoItemInfo MyWorkgroupInfo
            {
                get
                {
                    return _myworkgroupInfo;
                }
            }

            /// <summary>
            /// The DefaultsOnLogin item.
            /// </summary>
            [RepositoryItem("f8a82c45-71a0-447c-a11a-6d6c8b96280e")]
            public virtual Ranorex.Text DefaultsOnLogin
            {
                get
                {
                    return _defaultsonloginInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The DefaultsOnLogin item info.
            /// </summary>
            [RepositoryItemInfo("f8a82c45-71a0-447c-a11a-6d6c8b96280e")]
            public virtual RepoItemInfo DefaultsOnLoginInfo
            {
                get
                {
                    return _defaultsonloginInfo;
                }
            }

            /// <summary>
            /// The Toolbars item.
            /// </summary>
            [RepositoryItem("3da96d11-f3da-479b-b86d-e7e649980a55")]
            public virtual Ranorex.Text Toolbars
            {
                get
                {
                    return _toolbarsInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Toolbars item info.
            /// </summary>
            [RepositoryItemInfo("3da96d11-f3da-479b-b86d-e7e649980a55")]
            public virtual RepoItemInfo ToolbarsInfo
            {
                get
                {
                    return _toolbarsInfo;
                }
            }

            /// <summary>
            /// The SpellCheck item.
            /// </summary>
            [RepositoryItem("01f79284-e8f9-427e-a9d6-0cc067dfe06e")]
            public virtual Ranorex.Text SpellCheck
            {
                get
                {
                    return _spellcheckInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SpellCheck item info.
            /// </summary>
            [RepositoryItemInfo("01f79284-e8f9-427e-a9d6-0cc067dfe06e")]
            public virtual RepoItemInfo SpellCheckInfo
            {
                get
                {
                    return _spellcheckInfo;
                }
            }

            /// <summary>
            /// The DailiesPages item.
            /// </summary>
            [RepositoryItem("7b54a7fb-bbfa-484d-bc7a-7d054c5512ec")]
            public virtual Ranorex.Text DailiesPages
            {
                get
                {
                    return _dailiespagesInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The DailiesPages item info.
            /// </summary>
            [RepositoryItemInfo("7b54a7fb-bbfa-484d-bc7a-7d054c5512ec")]
            public virtual RepoItemInfo DailiesPagesInfo
            {
                get
                {
                    return _dailiespagesInfo;
                }
            }

            /// <summary>
            /// The TodaysPractice item.
            /// </summary>
            [RepositoryItem("06845597-6890-4cb9-8460-e08a58cfa6eb")]
            public virtual Ranorex.Text TodaysPractice
            {
                get
                {
                    return _todayspracticeInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TodaysPractice item info.
            /// </summary>
            [RepositoryItemInfo("06845597-6890-4cb9-8460-e08a58cfa6eb")]
            public virtual RepoItemInfo TodaysPracticeInfo
            {
                get
                {
                    return _todayspracticeInfo;
                }
            }

            /// <summary>
            /// The FilesDisplay item.
            /// </summary>
            [RepositoryItem("3031251f-2c38-4ac0-af25-e226fe85d0f1")]
            public virtual Ranorex.Text FilesDisplay
            {
                get
                {
                    return _filesdisplayInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FilesDisplay item info.
            /// </summary>
            [RepositoryItemInfo("3031251f-2c38-4ac0-af25-e226fe85d0f1")]
            public virtual RepoItemInfo FilesDisplayInfo
            {
                get
                {
                    return _filesdisplayInfo;
                }
            }

            /// <summary>
            /// The FilesNewEntries item.
            /// </summary>
            [RepositoryItem("73aff468-cd69-47d8-b5cc-ed6439c604ab")]
            public virtual Ranorex.Text FilesNewEntries
            {
                get
                {
                    return _filesnewentriesInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FilesNewEntries item info.
            /// </summary>
            [RepositoryItemInfo("73aff468-cd69-47d8-b5cc-ed6439c604ab")]
            public virtual RepoItemInfo FilesNewEntriesInfo
            {
                get
                {
                    return _filesnewentriesInfo;
                }
            }

            /// <summary>
            /// The CalendarDisplay item.
            /// </summary>
            [RepositoryItem("cd34b429-d223-4311-a3bb-6f96c65c1aef")]
            public virtual Ranorex.Text CalendarDisplay
            {
                get
                {
                    return _calendardisplayInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The CalendarDisplay item info.
            /// </summary>
            [RepositoryItemInfo("cd34b429-d223-4311-a3bb-6f96c65c1aef")]
            public virtual RepoItemInfo CalendarDisplayInfo
            {
                get
                {
                    return _calendardisplayInfo;
                }
            }

            /// <summary>
            /// The CalendarNewEntries item.
            /// </summary>
            [RepositoryItem("ab2cab22-e570-4116-9e38-223503984341")]
            public virtual Ranorex.Text CalendarNewEntries
            {
                get
                {
                    return _calendarnewentriesInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The CalendarNewEntries item info.
            /// </summary>
            [RepositoryItemInfo("ab2cab22-e570-4116-9e38-223503984341")]
            public virtual RepoItemInfo CalendarNewEntriesInfo
            {
                get
                {
                    return _calendarnewentriesInfo;
                }
            }

            /// <summary>
            /// The CalendarOther item.
            /// </summary>
            [RepositoryItem("fde81265-6280-4857-af5f-93f5a527f9a4")]
            public virtual Ranorex.Text CalendarOther
            {
                get
                {
                    return _calendarotherInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The CalendarOther item info.
            /// </summary>
            [RepositoryItemInfo("fde81265-6280-4857-af5f-93f5a527f9a4")]
            public virtual RepoItemInfo CalendarOtherInfo
            {
                get
                {
                    return _calendarotherInfo;
                }
            }

            /// <summary>
            /// The PeopleDisplay item.
            /// </summary>
            [RepositoryItem("78717a41-3037-43e4-a7e8-6dcc5dff0796")]
            public virtual Ranorex.Text PeopleDisplay
            {
                get
                {
                    return _peopledisplayInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The PeopleDisplay item info.
            /// </summary>
            [RepositoryItemInfo("78717a41-3037-43e4-a7e8-6dcc5dff0796")]
            public virtual RepoItemInfo PeopleDisplayInfo
            {
                get
                {
                    return _peopledisplayInfo;
                }
            }

            /// <summary>
            /// The PeopleNewEntries item.
            /// </summary>
            [RepositoryItem("621a0c44-3b7f-4dc9-b1e1-c9e4fa5d1a14")]
            public virtual Ranorex.Text PeopleNewEntries
            {
                get
                {
                    return _peoplenewentriesInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The PeopleNewEntries item info.
            /// </summary>
            [RepositoryItemInfo("621a0c44-3b7f-4dc9-b1e1-c9e4fa5d1a14")]
            public virtual RepoItemInfo PeopleNewEntriesInfo
            {
                get
                {
                    return _peoplenewentriesInfo;
                }
            }

            /// <summary>
            /// The Management item.
            /// </summary>
            [RepositoryItem("f8c8e163-3e6e-47cf-8bc9-f40933f2132f")]
            public virtual Ranorex.Text Management
            {
                get
                {
                    return _managementInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Management item info.
            /// </summary>
            [RepositoryItemInfo("f8c8e163-3e6e-47cf-8bc9-f40933f2132f")]
            public virtual RepoItemInfo ManagementInfo
            {
                get
                {
                    return _managementInfo;
                }
            }

            /// <summary>
            /// The DocumentAssembly item.
            /// </summary>
            [RepositoryItem("e8cff8b4-3af0-4182-8276-3c7d3858ee1d")]
            public virtual Ranorex.Text DocumentAssembly
            {
                get
                {
                    return _documentassemblyInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The DocumentAssembly item info.
            /// </summary>
            [RepositoryItemInfo("e8cff8b4-3af0-4182-8276-3c7d3858ee1d")]
            public virtual RepoItemInfo DocumentAssemblyInfo
            {
                get
                {
                    return _documentassemblyInfo;
                }
            }

            /// <summary>
            /// The BillingRates item.
            /// </summary>
            [RepositoryItem("caf44723-297d-448d-ac7d-1aa266b644d8")]
            public virtual Ranorex.Text BillingRates
            {
                get
                {
                    return _billingratesInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The BillingRates item info.
            /// </summary>
            [RepositoryItemInfo("caf44723-297d-448d-ac7d-1aa266b644d8")]
            public virtual RepoItemInfo BillingRatesInfo
            {
                get
                {
                    return _billingratesInfo;
                }
            }

            /// <summary>
            /// The TimeNewEntries item.
            /// </summary>
            [RepositoryItem("4b8de679-31ff-4a86-881c-9a88f4041c08")]
            public virtual Ranorex.Text TimeNewEntries
            {
                get
                {
                    return _timenewentriesInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TimeNewEntries item info.
            /// </summary>
            [RepositoryItemInfo("4b8de679-31ff-4a86-881c-9a88f4041c08")]
            public virtual RepoItemInfo TimeNewEntriesInfo
            {
                get
                {
                    return _timenewentriesInfo;
                }
            }

            /// <summary>
            /// The Timer item.
            /// </summary>
            [RepositoryItem("b204d13a-872b-48d7-a802-f2924aa83f74")]
            public virtual Ranorex.Text Timer
            {
                get
                {
                    return _timerInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Timer item info.
            /// </summary>
            [RepositoryItemInfo("b204d13a-872b-48d7-a802-f2924aa83f74")]
            public virtual RepoItemInfo TimerInfo
            {
                get
                {
                    return _timerInfo;
                }
            }

            /// <summary>
            /// The Formatting item.
            /// </summary>
            [RepositoryItem("e9653e86-2c18-4982-bc85-c9e25c289a73")]
            public virtual Ranorex.Text Formatting
            {
                get
                {
                    return _formattingInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Formatting item info.
            /// </summary>
            [RepositoryItemInfo("e9653e86-2c18-4982-bc85-c9e25c289a73")]
            public virtual RepoItemInfo FormattingInfo
            {
                get
                {
                    return _formattingInfo;
                }
            }

            /// <summary>
            /// The ActivityCodes item.
            /// </summary>
            [RepositoryItem("fce08a3f-7f7f-492c-bf66-07c14baec5fe")]
            public virtual Ranorex.Text ActivityCodes
            {
                get
                {
                    return _activitycodesInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ActivityCodes item info.
            /// </summary>
            [RepositoryItemInfo("fce08a3f-7f7f-492c-bf66-07c14baec5fe")]
            public virtual RepoItemInfo ActivityCodesInfo
            {
                get
                {
                    return _activitycodesInfo;
                }
            }

            /// <summary>
            /// The Fiscal item.
            /// </summary>
            [RepositoryItem("963b7afb-dd77-4606-afdb-3932f2f4c69c")]
            public virtual Ranorex.Text Fiscal
            {
                get
                {
                    return _fiscalInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Fiscal item info.
            /// </summary>
            [RepositoryItemInfo("963b7afb-dd77-4606-afdb-3932f2f4c69c")]
            public virtual RepoItemInfo FiscalInfo
            {
                get
                {
                    return _fiscalInfo;
                }
            }

            /// <summary>
            /// The General item.
            /// </summary>
            [RepositoryItem("535f0fa4-fd5f-482a-93da-915fcd16795a")]
            public virtual Ranorex.Text General
            {
                get
                {
                    return _generalInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The General item info.
            /// </summary>
            [RepositoryItemInfo("535f0fa4-fd5f-482a-93da-915fcd16795a")]
            public virtual RepoItemInfo GeneralInfo
            {
                get
                {
                    return _generalInfo;
                }
            }

            /// <summary>
            /// The Messages item.
            /// </summary>
            [RepositoryItem("0773a48b-9809-43c9-9888-2c4e4987e390")]
            public virtual Ranorex.Text Messages
            {
                get
                {
                    return _messagesInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Messages item info.
            /// </summary>
            [RepositoryItemInfo("0773a48b-9809-43c9-9888-2c4e4987e390")]
            public virtual RepoItemInfo MessagesInfo
            {
                get
                {
                    return _messagesInfo;
                }
            }

            /// <summary>
            /// The Defaults item.
            /// </summary>
            [RepositoryItem("49b0dc2b-240e-48be-88d9-abde2fedc3e0")]
            public virtual Ranorex.Text Defaults
            {
                get
                {
                    return _defaultsInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Defaults item info.
            /// </summary>
            [RepositoryItemInfo("49b0dc2b-240e-48be-88d9-abde2fedc3e0")]
            public virtual RepoItemInfo DefaultsInfo
            {
                get
                {
                    return _defaultsInfo;
                }
            }
        }

        /// <summary>
        /// The GeneralPreferencesFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("bea9971f-6b2b-4fc3-a039-98b032aa9102")]
        public partial class GeneralPreferencesFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonokInfo;
            RepoItemInfo _generalpreferencesformInfo;
            RepoItemInfo _titlebarInfo;

            /// <summary>
            /// Creates a new GeneralPreferencesForm  folder.
            /// </summary>
            public GeneralPreferencesFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("GeneralPreferencesForm", "/form[@controltext='Preferences']", parentFolder, 5000, null, true, "bea9971f-6b2b-4fc3-a039-98b032aa9102", "")
            {
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", ".//toolbar[@accessiblename='Toolbar']/button[@accessiblename='OK' and @enabled='True' and @accessiblestate='Focusable']", 5000, null, "737c9d4c-6593-4ccc-a43f-1ea3efc91e23");
                _generalpreferencesformInfo = new RepoItemInfo(this, "GeneralPreferencesForm", "", 30000, null, "ce3dbf95-8bd2-4bb3-88b2-404d03acc97e");
                _titlebarInfo = new RepoItemInfo(this, "TitleBar", "titlebar[@accessiblerole='TitleBar']", 30000, null, "f6a2b7f1-fa44-497c-9d5a-9b1ef0fbf09e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("bea9971f-6b2b-4fc3-a039-98b032aa9102")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("bea9971f-6b2b-4fc3-a039-98b032aa9102")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("737c9d4c-6593-4ccc-a43f-1ea3efc91e23")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("737c9d4c-6593-4ccc-a43f-1ea3efc91e23")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }

            /// <summary>
            /// The GeneralPreferencesForm item.
            /// </summary>
            [RepositoryItem("ce3dbf95-8bd2-4bb3-88b2-404d03acc97e")]
            public virtual Ranorex.Form GeneralPreferencesForm
            {
                get
                {
                    return _generalpreferencesformInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The GeneralPreferencesForm item info.
            /// </summary>
            [RepositoryItemInfo("ce3dbf95-8bd2-4bb3-88b2-404d03acc97e")]
            public virtual RepoItemInfo GeneralPreferencesFormInfo
            {
                get
                {
                    return _generalpreferencesformInfo;
                }
            }

            /// <summary>
            /// The TitleBar item.
            /// </summary>
            [RepositoryItem("f6a2b7f1-fa44-497c-9d5a-9b1ef0fbf09e")]
            public virtual Ranorex.TitleBar TitleBar
            {
                get
                {
                    return _titlebarInfo.CreateAdapter<Ranorex.TitleBar>(true);
                }
            }

            /// <summary>
            /// The TitleBar item info.
            /// </summary>
            [RepositoryItemInfo("f6a2b7f1-fa44-497c-9d5a-9b1ef0fbf09e")]
            public virtual RepoItemInfo TitleBarInfo
            {
                get
                {
                    return _titlebarInfo;
                }
            }
        }

        /// <summary>
        /// The EmailPreferencesFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("8f89f9d5-6bb3-4d24-9785-550bec029a33")]
        public partial class EmailPreferencesFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _closeInfo;
            RepoItemInfo _buttontoolbarwizardtoolstoolclInfo;

            /// <summary>
            /// Creates a new EmailPreferencesForm  folder.
            /// </summary>
            public EmailPreferencesFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("EmailPreferencesForm", "/form[@controlname='EmailPreferencesForm']", parentFolder, 5000, null, true, "8f89f9d5-6bb3-4d24-9785-550bec029a33", "")
            {
                _closeInfo = new RepoItemInfo(this, "Close", ".//toolbar[@accessiblename='Toolbar']/button[@accessiblename='Close ']", 5000, null, "b9d64f5c-cd9c-41b2-9ca2-16db60e86ae3");
                _buttontoolbarwizardtoolstoolclInfo = new RepoItemInfo(this, "ButtonToolbarWIZARDToolsToolCL", "?/?/?/button[@name='Close ' and @controltype='Button']", 30000, null, "0ca01454-1e39-40d2-80df-5ff5d2c6dfae");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8f89f9d5-6bb3-4d24-9785-550bec029a33")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8f89f9d5-6bb3-4d24-9785-550bec029a33")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("b9d64f5c-cd9c-41b2-9ca2-16db60e86ae3")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("b9d64f5c-cd9c-41b2-9ca2-16db60e86ae3")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }

            /// <summary>
            /// The ButtonToolbarWIZARDToolsToolCL item.
            /// </summary>
            [RepositoryItem("0ca01454-1e39-40d2-80df-5ff5d2c6dfae")]
            public virtual Ranorex.Button ButtonToolbarWIZARDToolsToolCL
            {
                get
                {
                    return _buttontoolbarwizardtoolstoolclInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonToolbarWIZARDToolsToolCL item info.
            /// </summary>
            [RepositoryItemInfo("0ca01454-1e39-40d2-80df-5ff5d2c6dfae")]
            public virtual RepoItemInfo ButtonToolbarWIZARDToolsToolCLInfo
            {
                get
                {
                    return _buttontoolbarwizardtoolstoolclInfo;
                }
            }
        }

        /// <summary>
        /// The PromptFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("bc5b262c-9b08-4061-b61d-1a018c35ee93")]
        public partial class PromptFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonokInfo;

            /// <summary>
            /// Creates a new PromptForm  folder.
            /// </summary>
            public PromptFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("PromptForm", "/form[@controlname='PromptForm']", parentFolder, 5000, null, true, "bc5b262c-9b08-4061-b61d-1a018c35ee93", "")
            {
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", ".//toolbar[@accessiblename='Toolbar']/button[@accessiblename='OK']", 5000, null, "89367da5-0a25-43d8-9f9a-812cf5a935e7");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("bc5b262c-9b08-4061-b61d-1a018c35ee93")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("bc5b262c-9b08-4061-b61d-1a018c35ee93")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("89367da5-0a25-43d8-9f9a-812cf5a935e7")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("89367da5-0a25-43d8-9f9a-812cf5a935e7")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
