///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SmokeTest.Recordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CalendarDayViewChangeEvent recording.
    /// </summary>
    [TestModule("0c5c95d9-7ead-49a3-bbdd-de1388006921", ModuleType.Recording, 1)]
    public partial class CalendarDayViewChangeEvent : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::SmokeTest.Repositories.SmokeTestRepository repository.
        /// </summary>
        public static global::SmokeTest.Repositories.SmokeTestRepository repo = global::SmokeTest.Repositories.SmokeTestRepository.Instance;

        static CalendarDayViewChangeEvent instance = new CalendarDayViewChangeEvent();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CalendarDayViewChangeEvent()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CalendarDayViewChangeEvent Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='To Do's') on item 'MainForm.ToDos'.", repo.MainForm.ToDosInfo, new RecordItemIndex(0));
            Validate.AttributeEqual(repo.MainForm.ToDosInfo, "Text", "To Do's");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainForm.ToDos' at Center.", repo.MainForm.ToDosInfo, new RecordItemIndex(1));
            repo.MainForm.ToDos.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AmicusAttorneyXWin.MenuItemToDosItemsMenuItemIn' at 75;13.", repo.AmicusAttorneyXWin.MenuItemToDosItemsMenuItemInInfo, new RecordItemIndex(2));
            repo.AmicusAttorneyXWin.MenuItemToDosItemsMenuItemIn.Click("75;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Appoinment') on item 'MainForm.ToDos'.", repo.MainForm.ToDosInfo, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.MainForm.ToDosInfo, "Text", "Appoinment");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
