///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SmokeTest.Recordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording7 recording.
    /// </summary>
    [TestModule("9c07c516-d8f1-4bb6-aa58-7f5b86b4137c", ModuleType.Recording, 1)]
    public partial class Recording7 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::SmokeTest.Repositories.SmokeTestRepository repository.
        /// </summary>
        public static global::SmokeTest.Repositories.SmokeTestRepository repo = global::SmokeTest.Repositories.SmokeTestRepository.Instance;

        static Recording7 instance = new Recording7();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording7()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording7 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainForm.TextEditorEditArea1' at 134;7.", repo.MainForm.TextEditorEditArea1Info, new RecordItemIndex(0));
            repo.MainForm.TextEditorEditArea1.Click("134;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainForm.TextEditorEditArea1' at 126;8.", repo.MainForm.TextEditorEditArea1Info, new RecordItemIndex(1));
            repo.MainForm.TextEditorEditArea1.Click("126;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FileDetailForm.Trust' at 57;8.", repo.FileDetailForm.TrustInfo, new RecordItemIndex(2));
            repo.FileDetailForm.Trust.Click("57;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FileDetailForm.ButtonToolbarToolbarToolsToolS' at 45;8.", repo.FileDetailForm.ButtonToolbarToolbarToolsToolSInfo, new RecordItemIndex(3));
            repo.FileDetailForm.ButtonToolbarToolbarToolsToolS.Click("45;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'MainForm.TextEditorEditArea1' at 184;8.", repo.MainForm.TextEditorEditArea1Info, new RecordItemIndex(4));
            repo.MainForm.TextEditorEditArea1.Click(System.Windows.Forms.MouseButtons.Right, "184;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AmicusAttorneyXWin1.TrustReceipt' at 141;9.", repo.AmicusAttorneyXWin1.TrustReceiptInfo, new RecordItemIndex(5));
            repo.AmicusAttorneyXWin1.TrustReceipt.Click("141;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TrustDetailBaseForm.ButtonToolbarToolbarBaseDesignerToo' at 36;11.", repo.TrustDetailBaseForm.ButtonToolbarToolbarBaseDesignerTooInfo, new RecordItemIndex(6));
            repo.TrustDetailBaseForm.ButtonToolbarToolbarBaseDesignerToo.Click("36;11");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
