///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SmokeTest.Recordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The VoidRec recording.
    /// </summary>
    [TestModule("a5144659-7568-4cfb-89a1-bb97b37685a6", ModuleType.Recording, 1)]
    public partial class VoidRec : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::SmokeTest.Repositories.SmokeTestRepository repository.
        /// </summary>
        public static global::SmokeTest.Repositories.SmokeTestRepository repo = global::SmokeTest.Repositories.SmokeTestRepository.Instance;

        static VoidRec instance = new VoidRec();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public VoidRec()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static VoidRec Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainForm.BILLING1' at 74;14.", repo.MainForm.BILLING1Info, new RecordItemIndex(0));
            repo.MainForm.BILLING1.Click("74;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainForm.ContainerGroup18' at 114;4.", repo.MainForm.ContainerGroup18Info, new RecordItemIndex(1));
            repo.MainForm.ContainerGroup18.Click("114;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainForm.TreeItem0' at 8;12.", repo.MainForm.TreeItem0Info, new RecordItemIndex(2));
            repo.MainForm.TreeItem0.Click("8;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'MainForm.TextEditorEditArea2' at 170;9.", repo.MainForm.TextEditorEditArea2Info, new RecordItemIndex(3));
            repo.MainForm.TextEditorEditArea2.DoubleClick("170;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ReceivePaymentForm.ButtonToolbarToolbarBaseDesignerToo' at 57;17.", repo.ReceivePaymentForm.ButtonToolbarToolbarBaseDesignerTooInfo, new RecordItemIndex(4));
            repo.ReceivePaymentForm.ButtonToolbarToolbarBaseDesignerToo.Click("57;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PromptForm.ButtonToolbarToolbarBaseDesignerToo' at 36;17.", repo.PromptForm.ButtonToolbarToolbarBaseDesignerTooInfo, new RecordItemIndex(5));
            repo.PromptForm.ButtonToolbarToolbarBaseDesignerToo.Click("36;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PromptForm.ButtonToolbarToolbarBaseDesignerToo1' at 29;20.", repo.PromptForm.ButtonToolbarToolbarBaseDesignerToo1Info, new RecordItemIndex(6));
            repo.PromptForm.ButtonToolbarToolbarBaseDesignerToo1.Click("29;20");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainForm.TreeItem0' at 13;14.", repo.MainForm.TreeItem0Info, new RecordItemIndex(7));
            repo.MainForm.TreeItem0.Click("13;14");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
